T["cs"] = {
  "age_forms": [
    "už {n}!",
    "teď už {n}!",
    "teď {n}! 🎂",
    "už {n}! 🎂"
  ],
  "album_btn_copy": "📋 Kopírovat",
  "album_cap_and": "&",
  "album_cap_dressup": "náš vystrojený pár",
  "album_cap_group": "společné foto · všichni 🎉",
  "album_cap_selfie": "selfie z fotokoutku",
  "album_cap_with": "s",
  "album_empty_sub": "Aspen zatím nic nevyfotila — projdi se po loftu a album se začne plnit.",
  "album_empty_title": "zatím žádné fotky",
  "album_recap_back": "Zpět do celého alba",
  "album_recap_group": "všichni společně",
  "album_recap_open": "Zobrazit rekapitulaci párty",
  "album_recap_portraits": "portréty",
  "album_recap_rooms": "po celém loftu",
  "album_recap_selfies": "naše selfie",
  "album_recap_sub": "Kontaktní arch z téhle párty.",
  "album_recap_title": "dnešní večer v loftu",
  "album_room_balcony": "na balkoně",
  "album_room_cuddly": "v cuddly-puddly",
  "album_room_garden": "v zahradě/party",
  "album_room_kitchen": "u baru",
  "album_room_office": "v pracovně",
  "album_search_none": "nikdo tohoto jména na fotkách není.",
  "album_search_ph": "hledat ve fotkách…",
  "app_album": "album",
  "app_browser": "prohlížeč",
  "app_calculator": "kalkulačka",
  "app_calendar": "kalendář",
  "app_call": "volání",
  "app_cards": "slovníček",
  "app_chat": "chat",
  "app_chrome": "chrome",
  "app_classics": "klasika",
  "app_clock": "hodiny",
  "app_cocktails": "koktejly",
  "app_code": "kód",
  "app_console": "konzole",
  "app_currency": "měna",
  "app_dressup": "oblékačka",
  "app_firefox": "firefox",
  "app_flashlight": "baterka",
  "app_hn": "zprávy",
  "app_life": "život",
  "app_linux": "linux",
  "app_mail": "maily",
  "app_messages": "zprávy",
  "app_mines": "hledání min",
  "app_music": "hudba",
  "app_notes": "vzkazy",
  "app_pacman": "hackman",
  "app_photobooth": "fotokoutek",
  "app_prince": "princ",
  "app_python": "python",
  "app_quiz": "kvíz",
  "app_shoot": "shoot",
  "app_snake": "had",
  "app_tattoo": "tetování",
  "app_video": "video",
  "app_weather": "počasí",
  "arcade_offer_flair": "Nový rekord! Flair Catch servíruje další kolo. 🍸",
  "arcade_offer_invaders": "Nový rekord! Alien Resources má volné místo. 👾",
  "arcade_offer_pacman": "Nový rekord! Hack-Man vstoupil do chatu. ᗧ",
  "arcade_offer_tetris": "Nový rekord! Block Party se rozsvěcí. 🧱",
  "balcony_audience_callout": "Úsměv — máme publikum! 👀",
  "balcony_marketa_groceries": "Nákupy má na starost ona.",
  "bd_msg_a": "Dnes slaví {name} — všechno nejlepší! 🎂",
  "bd_msg_b": "{name} má dnes narozeniny!! 🥳",
  "bd_msg_c": "{name} má dnes velký den 🎂🎈",
  "bd_msg_d": "Hodně štěstí, zdraví 🎶 dnes slaví {name}! 🎉🎈",
  "bd_toast_a": "🎂 ",
  "bd_toast_b": "narozeniny má {name}",
  "bedroom_glass_draw": "Remíza — kliknutím na políčko vyčistíte hrací plochu",
  "bedroom_glass_loss": "Vitráž vyhrála — kliknutím na políčko vyčistíte hrací plochu",
  "bedroom_glass_win": "Vyhráli jste — kliknutím na políčko vyčistíte hrací plochu",
  "bedroom_ttt_start_caption": "Kliknutím na libovolné políčko spustíte piškvorky",
  "box_trip_pick_title": "vitamíny",
  "boxlock_ctx_unlock": "Odemknout",
  "boxlock_fail_click": "Klikni na datum nahoře.",
  "boxlock_fail_date": "Je to jedno z dat našich svateb, zkus to znovu.",
  "boxlock_fail_jul": "10. července 2027 — Praha.",
  "boxlock_fail_may": "1. května 2027 — Edmonton.",
  "boxlock_submit": "ODEMKNOUT",
  "browser_deeper": "musíme jít hlouběji…",
  "browser_loading": "načítání…",
  "browser_noframe": "když zůstane prázdná, stránka se odmítá nastěhovat do obrázkového rámečku — většina velkých stránek to tak má",
  "browser_omni_ph": "Hledat nebo zadat adresu",
  "butterfly_broken_caption": "Proto nemůžeme mít krásná křídla.",
  "butterfly_chase_progress": "Hon na motýly: {score}/10 · {seconds} s",
  "butterfly_chase_timeout": "Motýli uletěli. 🦋",
  "butterfly_chase_tip": "Klikni na kteréhokoli motýla a spusť honičku. 🦋",
  "butterfly_chase_win": "Motýli chyceni. Nikomu se nic nestalo. 🦋",
  "cal_bbq": "🍖 den grilování",
  "cal_bicycle_day": "Den na kole (LSD)",
  "cal_bipolar_day": "🧲 Světový den bipolární poruchy",
  "cal_brunch": "🍳 zahradní brunch",
  "cal_dl_e": "Stáhnout termíny v Edmontonu (.ics)",
  "cal_dl_p": "Stáhnout termíny v Praze (.ics)",
  "cal_download": "Stáhnout .ics",
  "cal_e_d1": "1. 5. · 16:00–04:00",
  "cal_e_d1_what": "svatba & oslava",
  "cal_e_d2": "2. 5. · 16:00–22:00",
  "cal_e_d2_what": "grilování v loftu",
  "cal_edmonton": "Edmonton",
  "cal_gcal": "GCal",
  "cal_ics_e1": "markéta ∞ behdad — svatba v Edmontonu",
  "cal_ics_e2": "markéta ∞ behdad — grilovačka v loftu · Edmonton",
  "cal_ics_p1": "markéta ∞ behdad — zahradní slavnost v Praze",
  "cal_ics_p2": "markéta ∞ behdad — zahradní brunch v Praze",
  "cal_lubeck": "Lübeck",
  "cal_marijuana_day": "420 (marihuana)",
  "cal_mushroom_day": "Mezinárodní den hub",
  "cal_p_d1": "10. 7. · 15:00–03:00",
  "cal_p_d1_what": "zahradní oslava",
  "cal_p_d2": "11. 7. · 11:00–15:00",
  "cal_p_d2_what": "zahradní brunch",
  "cal_polyamory_day": "Světový den polyamorie",
  "cal_prague": "Praha",
  "cal_search_meteor": "meteorický roj",
  "cal_search_none": "hledání neodpovídají žádné události.",
  "cal_search_placeholder": "hledat události…",
  "cal_tehran": "Teherán",
  "calc_backspace": "Smazat poslední číslici",
  "calc_error": "Chyba",
  "california_place": "Kalifornie",
  "call_incoming": "Příchozí videohovor…",
  "can_streak_text": "Pěkná série hodů! 🥫",
  "cards_hint": "klepnutím otočíš kartu",
  "cdb_conn": "do",
  "cdb_edmonton": "Edmonton",
  "cdb_edmonton_to": "Edmontonu",
  "cdb_prague": "Praha",
  "cdb_prague_to": "Prahy",
  "cdb_today": "{city} je dnes!",
  "cdb_tomorrow": "{city} už zítra!",
  "cdb_week_1": "týden",
  "cdb_week_m": "týdnů",
  "cdb_week_n": "týdny",
  "chat_action_failed": "Teď se mi to nepodařilo. Zkus to znovu.",
  "chat_error": "Něco se pokazilo. Zkus to znovu.",
  "chat_placeholder": "Zeptej se na loft…",
  "chat_retry": "Zkusit znovu",
  "chat_thinking": "Přemýšlím…",
  "chat_unavailable": "Chat zatím není připojený.",
  "chat_welcome": "Ahoj! Jsem Charlie, tvůj svatební průvodce. Znám tenhle loft a vím, jak to tu funguje. Zeptej se mě na cokoli.",
  "cheers_text": "Na zdraví! 🥂",
  "cinema_screen_off": "projektor je vypnutý",
  "cinema_screen_short": "vysychá…",
  "cinema_short_gag": "Projektor přežil. Záruka ne.",
  "cinema_title": "Na co se podíváme?",
  "ck_featured": "náš drink",
  "ck_gallery": "bar",
  "ck_ingredients": "ingredience",
  "ck_order": "🍸 Objednat",
  "ck_signature": "naše vlastní specialita",
  "ck_steps": "postup",
  "classics_back": "‹ hry",
  "classics_choose": "Vyberte klasiku",
  "classics_mines": "Hledání min",
  "classics_mines_sub": "nespusťte prsten",
  "classics_solitaire": "Solitaire",
  "classics_solitaire_sub": "trocha trpělivosti",
  "clk_jump_label": "Přejít na čas",
  "clk_playtime": "V loftu jsi už",
  "code_email_intro": "Ahoj Markéto a Behdade!\n\nPodívejte, co jsem vytvořil(a) v loftu — spusťte to v aplikaci kód na počítači v pracovně:",
  "code_email_subject": "Podívejte, co jsem vytvořil(a)!",
  "console_hint": "Otevřít rozbalovací konzoli",
  "console_hint_close": "Zavřít rozbalovací konzoli",
  "console_laser": "bzzzt — červená tečka je venku a sleduje kurzor. laser.set(false) ji odvolá. hodně štěstí, kočko.",
  "console_welcome": "   loftová konzole — opravdový JavaScript; typované API Loft je připravené jako `loft`. zkuste: help · ? klávesové zkratky",
  "contact": "Dotazy? Napište nám:",
  "credits_codesigner": "spolutvůrkyně designu",
  "credits_codesigner_translator": "spolutvůrkyně designu | český překlad",
  "credits_killed": "TITULKY UKONČENY",
  "credits_licenses": "Licenční informace jsou přiloženy k softwaru.",
  "credits_open_source": "Open-source software",
  "credits_qa": "vedoucí testování",
  "credits_survives": "vděčnost přežívá.",
  "credits_tester": "tester",
  "credits_testers": "Testeři",
  "credits_thanks": "s poděkováním",
  "credits_title": "Titulky",
  "cue_calendar_body": "zapiš si nás do kalendáře 📅 1. května · 10. července",
  "cue_cocktails_body": "celé menu máš v telefonu, když vybíráš 🍸",
  "cue_mail_body": "koukl(a) jsi do pošty? 💌 máš tam dopis",
  "cur_offline": "· kurz offline",
  "datenav_reset": "Vrátit datum na dnešek",
  "datenav_reset_time": "Vrátit čas na teď",
  "desk_date": "1. května",
  "desk_search_apps": "hledat aplikace…",
  "desk_to": "do",
  "df_bsod_main": "Počítač narazil na problém a je zapotřebí restartovat.",
  "dial_call": "Volat",
  "dial_fam_california": "patty a děti",
  "dial_fam_lueb": "madla a rodina",
  "dial_fam_prague": "markétini rodiče",
  "dial_fam_tehran": "behdadova rodina",
  "dial_pick_title": "komu voláme?",
  "dj_pick_title": "vyber si písničku",
  "dollhouse_locked": "?",
  "dollhouse_title": "Loft 🗺️",
  "du_bouquet": "kytice",
  "du_copy": "Kopírovat",
  "du_download": "Stáhnout",
  "du_earrings": "náušnice",
  "du_flowercrown": "věneček",
  "du_monocle": "monokl",
  "du_mustache": "knír",
  "du_necktie": "kravata",
  "du_partyhats": "party čepice",
  "du_save": "Uložit",
  "du_shades": "sluneční brýle",
  "du_tophats": "cylindry",
  "du_veil": "závoj",
  "ed_city": "Edmonton",
  "ed_date1": "So 1. května · 16–4 h",
  "ed_date2": "Ne 2. května · 16–22 h",
  "ed_desc1": "Obřad, večeře, koncert, tanec a afterparty.",
  "ed_desc2": "BBQ v loftu.",
  "entrance_intercom_reply": "„Alo?“",
  "entrance_windows_all_off": "Celý dům šel spát.",
  "entrance_windows_all_on": "Všechna okna svítí. Účet za elektřinu nikdo neřeší.",
  "entrance_windows_uv": "Celý dům se snaží spát. A kvůli tobě nemůže.",
  "eq_off_note": "Tenhle prohlížeč přehrává písničky napřímo — ekvalizér tu nemá za co tahat. Zkus to na jiném zařízení 🎚",
  "extinguisher_reset": "Tak přece. A je to. Hra resetována.",
  "extinguisher_warning": "Radši ne.",
  "fal_intro": "Otevřeš Díván namátkou. Háfiz odpovídá:",
  "fal_lines": [
    "Ztracený Josef se vrátí do Kanaánu — netruchli.<br>Z domu smutku bude jednou růžová zahrada — netruchli.",
    "Nuže, šenkýři, nalej pohár a podej jej dál —<br>láska se zprvu zdála snadná, a pak přišly těžkosti.",
    "Zasaď strom přátelství — ponese, po čem srdce touží.<br>Vytrhni výhonek nepřátelství — ponese žal bez počtu."
  ],
  "fern_found": "Květ kapradí. Stál jsi tady o půlnoci té jediné noci, kdy se otevírá. V tom to celé je — a prý to nosí štěstí.",
  "fern_legend": "Kapradí. Prý kvete jednu půlnoc do roka — dnes v noci, jestli té pověsti věříš — a kdo najde květ, dojde štěstí.",
  "flight_note": "Edmonton → Praha — asi 10 týdnů (a jeden oceán) od sebe.",
  "fun_ali": "závodní cyklista",
  "fun_alireza": "vytrvalostní běžec",
  "fun_ashraf": "taky miluje vrhcáby",
  "fun_aspen": "nejlepší svatební fotografka",
  "fun_athena": "<em>Zebel-khan</em>",
  "fun_ayushi": "stand-up komička v praxi.",
  "fun_baharak": "mladší sestra, víc netřeba",
  "fun_bahareh": "šílený smysl pro detail",
  "fun_baka": "ráda sleduje sport",
  "fun_behdad": "nejlepší kamarád Clauda a Codexu.",
  "fun_chinnell": "nemá v plánu dospět",
  "fun_danbern": "Irene vyrostla na jeho albech pro děti",
  "fun_danesh": "nejlepší vlasy",
  "fun_daniel": "opravuje kostely",
  "fun_elisabeth": "leze a maluje",
  "fun_farhang": "triatlonista",
  "fun_felix": "rád sportuje",
  "fun_goli": "dvojnice Lady Gaga",
  "fun_hamid": "Behdadův <em>adoptovaný syn</em>",
  "fun_hannah": "gymnastka. učí se hrát na piano.",
  "fun_irene": "už se učí Python",
  "fun_jay": "filozof / Ježíš",
  "fun_lauren": "Farhangova šéfka",
  "fun_madla": "hraje na kytaru",
  "fun_mahzad": "architektka a malířka",
  "fun_marie": "inženýrka a psycholožka",
  "fun_marketa": "sport, čtení, psaní, jazyky, hudba — na co si vzpomeneš",
  "fun_mohsen": "miluje vrhcáby!",
  "fun_navid": "znalec řecké mytologie",
  "fun_oritshimoni": "hudebnice na cestách",
  "fun_patricia": "nadýchané vlasy",
  "fun_patricia_daughter": "okouzlující oči",
  "fun_patricia_son": "miluje <em>Ladu</em>",
  "fun_payman": "vášnivý čtenář",
  "fun_pouria": "sbírá koníčky",
  "fun_rafi": "skvělý vypravěč",
  "fun_robert": "hraje na klavír",
  "fun_robin": "znalec dinosaurů",
  "fun_sina": "nejlepší techno",
  "fun_spencer": "mluví korejsky",
  "fun_whistler": "Uplave 1km bez zastavení",
  "game_alien_title": "ALIEN RESOURCES",
  "game_best": "REKORD",
  "game_cleared": "HOTOVO!",
  "game_flair_title": "FLAIR CATCH",
  "game_new": "NOVÁ HRA",
  "game_over": "KONEC HRY",
  "game_paused": "POZASTAVENO",
  "game_play_again": "HRÁT ZNOVU",
  "game_ready": "PŘIPRAVEN!",
  "game_score": "SKÓRE",
  "gm_toast_ali_1": "Na vás dva —",
  "gm_toast_ali_2": "ať je vždy co slavit. 🥂",
  "gm_toast_farhang_1": "Jedna svatba nestačila,",
  "gm_toast_farhang_2": "tak na lásku — rovnou dvakrát! 💞",
  "hn_by": "od",
  "hn_comments": "komentářů",
  "hn_comments_error": "komentáře se nepodařilo načíst.",
  "hn_comments_heading": "Komentáře",
  "hn_comments_loading": "načítám komentáře…",
  "hn_comments_partial": "Některé komentáře se nepodařilo načíst.",
  "hn_error": "Hacker News není dostupný — zkontroluj připojení.",
  "hn_external_intro": "Tento příspěvek je na webu {source}. Otevři originál v nové záložce; diskuse z Hacker News je níže.",
  "hn_loading": "načítám příspěvky…",
  "hn_no_comments": "zatím bez komentářů.",
  "hn_open_hn": "Otevřít na Hacker News",
  "hn_open_original": "Otevřít originál",
  "hn_points": "bodů",
  "hn_source": "zdroj",
  "hn_story": "Příspěvek",
  "hn_top_stories": "Hlavní příspěvky",
  "hp_nudge": "🎧 nasaď si je — párty zní nejlíp přes sluchátka",
  "hunt": {
    "act_b0": "Den skončil — ale obloha ne. Klikni na slunce a dívej se, jak zapadá. 🌇",
    "act_b2": "Čas spát. Zhasni — vypínač je u dveří.",
    "act_b2_redirect": "Ne lampu — ten malý vypínač u dveří. 👉",
    "act_b3": "…tak to nebyl vypínač. 🎉 Překvapení — v loftu tiché noci nevedeme.",
    "act_p1": "<em>Pouria</em> je zpátky za barem — dojdi si pro drink, cos ráno vynechal(a). 🍸",
    "act_p2": "<em>DJ Sina</em> a <em>DJ Danesh</em> si předávají pult. Zahrada tančí — zůstaň na další. 💃",
    "act_p3": "Vyfoť se do alba — použij fotokoutek v telefonu<span class=\"kbd-hint\">, stačí zmáčknout <kbd>c</kbd></span>, nebo ten na PC. 📷",
    "arcade_hint": "Pohybuj křeslem nebo použij ← → a zamiř; mezerník vystřelí. 👾",
    "balcony": "Bude grilovačka 🔥🍖🌽🍷",
    "bathroom_bubbles_done": "Bubble-gun · čas!",
    "bathroom_bubbles_start": "Bubble-gun · 20 sekund. Klikni nebo tažením zamiř stoličku.",
    "bathroom_mirror_doodle": "Koupelna · teď můžeš kreslit do zbylé páry.",
    "bathroom_mirror_reveal": "Koupelna · m∞b, napsané do páry.",
    "bedroom_ttt_turn_caption": "Jsi na tahu · okno volá",
    "bedroom_ttt_wait_caption": "Vitráž je na tahu · a má plán",
    "cine_anywhere": "Hrajte si, kamkoli se zatouláte.",
    "cine_arcade": "Zahrajte si něco, co palbu opětuje.",
    "cine_below": "Otevřete dveře. Sejděte dolů.",
    "cine_camp": "Zůstaňte, dokud nevyjdou hvězdy.",
    "cine_chapter_camp": "Zůstaňte přes noc",
    "cine_chapter_jump": "Zkuste něco nečekaného",
    "cine_chapter_open": "Otevřete další dveře",
    "cine_chapter_party": "Nechte pokoj zaplnit",
    "cine_chapter_road": "Vydejte se na západ",
    "cine_chapter_round": "Zkuste další kolo",
    "cine_chapter_soft": "Objevte měkkou stránku",
    "cine_chapter_unlock": "Sledujte nápovědy",
    "cine_chapter_wander": "Toulejte se kdekoli",
    "cine_clues": "Sledujte nápovědy. Otevřete další pokoj.",
    "cine_final_detail": "Hry, odbočky a jedna cesta na západ",
    "cine_final_kicker": "Sledujte nápovědy · Prozkoumejte každý pokoj",
    "cine_final_note": "Zbytek je na vás.",
    "cine_final_title": "Uvidíte, kam vás loft zavede",
    "cine_more": "Vždycky je tu ještě něco k vyzkoušení.",
    "cine_open": "Zkoušejte loft na přeskáčku.",
    "cine_party": "Někdy se pokoj zaplní sám.",
    "cine_phone": "Otevřete si prokrastinaci do kapsy.",
    "cine_road": "Vydejte se dlouhou cestou na západ.",
    "cine_round": "Zkuste ještě jedno kolo.",
    "cine_signoff": "Převezměte ovládání. Objevte zbytek.",
    "cine_soft": "Objevte měkkou stránku.",
    "cine_title": "Prozkoumejte loft",
    "cine_title_kicker": "Pojďte si na chvíli hrát",
    "cine_title_sub": "Zkoušejte · otevírejte · toulejte se · objevujte",
    "clickme": "KLIKNI!",
    "complete": "Prošli jste celým loftem ♥",
    "cuddly": "Pohraj si s Octi, otevři balkonové dveře, přetáhni deku.",
    "cuddly_door": "Teď otevři balkonové dveře.",
    "cuddly_hint": "Nejdřív si pohraj s Octi.",
    "cuddly_outlet_visit": "Někdo se zastavil v cuddly-puddly. 👋",
    "cuddly_pull": "Teď přetáhni libovolnou deku.",
    "df_about_quip": "Zkoušeli jste realitu vypnout a zapnout?",
    "df_browser_quip": "Ajaj! Panel to vzdal.",
    "df_calendar_quip": "Tvé dny jsou sečteny.",
    "df_call_lost": "SPOJENÍ PŘERUŠENO",
    "df_call_quip": "Ty za to nemůžeš. Zlobí připojení.",
    "df_chat_quip": "Charlie odešel z chatu.",
    "df_classics_quip": "Vyber si kartu. Jakoukoli.",
    "df_clock_quip": "Čas vypršel.",
    "df_code_quip": "Zpátky k základům.",
    "df_console_quip": "undefined není funkce.",
    "df_doom_quip": "kill -9 — dokonalé vítězství.",
    "df_help_quip1": "Jsi volný(á). Teď je to na tobě.",
    "df_help_quip2": "Máš tušení, co se stane teď?",
    "df_life_quip": "Smyslem života je hra samotná.",
    "df_linux_q1": "Nejdřív si tě nevšímají…",
    "df_linux_q2": "…a pak vyhraješ.",
    "df_mail_quip": "Nemáš žádnou poštu.",
    "df_mines_quip": "Našel(a) jsi je.",
    "df_music_quip": "Dál už jen ticho.",
    "df_pacman_quip": "Konec hry. Vlož dalšího ducha.",
    "df_photobooth_quip": "Nikdo nemrkl.",
    "df_python_quip1": "To je jen škrábnutí!",
    "df_python_quip2": "Je to jenom povrchové škrábnutí!",
    "df_snake_quip": "KONEC HRY · Sežralo to proces.",
    "df_solitaire_quip": "Došla trpělivost.",
    "df_system_quip": "Systém ukončen. Chyby přežily.",
    "df_tattoo_quip": "Bez výčitek.",
    "df_video_butterfly_quip": "Barvy stekly. Motýl zůstal.",
    "df_video_quip": "Tancuj, jako by se díval celý svět.",
    "df_video_rose_quip": "Růže opadá. Píseň zůstává.",
    "df_weather_quip": "Počasí pod psa.",
    "dj_danesh": [
      "Za pult jde <em>DJ Danesh</em>. 🎧",
      "<em>DJ Danesh</em> jde roztočit hvězdná kola. 🎧"
    ],
    "dj_sina": [
      "Za pult jde <em>DJ Sina</em>. 🎧",
      "<em>DJ Sina</em> s sebou veze hity tutový. 🎧"
    ],
    "entrance_drive_auto": "Automat · řiď, zrychluj a brzdi.",
    "entrance_drive_auto_desktop": "Automat · ↑ zrychluje · ↓ brzdí · mezerník drží rychlost.",
    "entrance_drive_auto_drive_interlock": "Před zařazením D zpomal pod 10 km/h.",
    "entrance_drive_auto_neutral_hint": "Automat je v N · pro jízdu zařaď D.",
    "entrance_drive_auto_park_hint": "Automat je v P · pro jízdu zařaď D.",
    "entrance_drive_auto_park_interlock": "Před zařazením P zastav.",
    "entrance_drive_auto_reverse_interlock": "Před zařazením zpátečky zpomal pod 10 km/h.",
    "entrance_drive_close": "Zavřít palubní desku",
    "entrance_drive_coach_auto_gear_desktop": "Shift + ↑ / ↓ nebo táhni či klikni pákou do D",
    "entrance_drive_coach_auto_gear_title": "Zařaď D",
    "entrance_drive_coach_auto_gear_touch": "Přesuň páku dolů z P na D",
    "entrance_drive_coach_auto_pedals_desktop": "↑ zrychluje · ↓ brzdí",
    "entrance_drive_coach_auto_pedals_touch": "Modrý řídí · růžový zrychluje/brzdí · střed drží rychlost",
    "entrance_drive_coach_cruise_text": "Stiskni mezerník pro udržení rychlosti.",
    "entrance_drive_coach_cruise_title": "Tempomat",
    "entrance_drive_coach_gear_desktop": "Shift + ↑ / ↓ řadí rychlosti",
    "entrance_drive_coach_gear_title": "Řaď",
    "entrance_drive_coach_gear_touch": "Podrž řadicí páku a tažením zvol rychlost",
    "entrance_drive_coach_ignition_text": "Stiskni Enter nebo klikni na klíček a nastartuj.",
    "entrance_drive_coach_ignition_title": "Nastartuj auto",
    "entrance_drive_coach_pedals_desktop": "↑ zrychluje · ↓ brzdí",
    "entrance_drive_coach_pedals_title": "Teď jeď",
    "entrance_drive_coach_pedals_touch": "Modrý řídí · růžový zrychluje/brzdí · střed drží rychlost",
    "entrance_drive_coach_steer_desktop": "Směr řídíš šipkami ← →",
    "entrance_drive_coach_steer_title": "Řiď",
    "entrance_drive_coach_steer_touch": "Posouvej modrý ovladač nebo táhni volantem",
    "entrance_drive_cruise_active": "Tempomat drží {speed} km/h · mezerník nastaví novou rychlost · brzda ho zruší.",
    "entrance_drive_ignition_hint": "Nastartuj motor. Klíček je vlevo.",
    "entrance_drive_manual": "Jeďme s manuálem.",
    "entrance_drive_manual_desktop": "Manuál · ↑ zrychluje · ↓ brzdí · mezerník drží rychlost.",
    "entrance_drive_mode_auto": "Automatická převodovka.",
    "entrance_drive_mode_manual": "Manuální převodovka.",
    "entrance_drive_neutral_hint": "Jeďme s manuálem · zařaď rychlost.",
    "entrance_drive_rev_shift_auto": "Zařaď D a rozjeď se.",
    "entrance_drive_rev_shift_manual": "Zařaď jedničku a rozjeď se.",
    "entrance_drive_roadtrip_button_hint": "Klikni nahoře na Výlet a vyraz na cestu.",
    "entrance_drive_shift_down": "Shift ↓ · zařaď nižší rychlost.",
    "entrance_drive_shift_up": "Shift ↑ · chce to další rychlost.",
    "entrance_drive_stalled": "Chcíplo ti to. Nastartuj ho znovu.",
    "entrance_drive_status_auto": "Automat, {gear}",
    "entrance_drive_status_manual": "Manuál, {gear}",
    "entrance_drive_touch_accel": "PLYN",
    "entrance_drive_touch_brake": "BRZDA",
    "entrance_roadtrip_abraham_arrival": "Pojďme se na noc utábořit.",
    "entrance_roadtrip_abraham_exit": "Odbočka k jezeru Abraham před tebou · sjeď doprava.",
    "entrance_roadtrip_arrest_centerline_line": "dvojitá plná · pokuta {fine} · {points} b. · {total}/15",
    "entrance_roadtrip_arrest_centerline_title": "POKUTA ZA PLNOU ČÁRU",
    "entrance_roadtrip_arrest_impaired_line": "{fine} · {points} b. · {total}/15",
    "entrance_roadtrip_arrest_impaired_title": "ŘÍZENÍ POD VLIVEM",
    "entrance_roadtrip_arrest_kicker": "SILNIČNÍ KONTROLA",
    "entrance_roadtrip_arrest_line": "+{over} · {fine} · {points} b. · {total}/15",
    "entrance_roadtrip_arrest_shout_engine": "VYPNĚTE MOTOR!",
    "entrance_roadtrip_arrest_shout_hands": "RUCE SKRZ VOLANT!",
    "entrance_roadtrip_arrest_shout_keys": "PUSŤE KLÍČE!",
    "entrance_roadtrip_arrest_ticket_line": "+{over} · pokuta {fine} · {points} b. · {total}/15",
    "entrance_roadtrip_arrest_ticket_title": "POKUTA ZA RYCHLOST",
    "entrance_roadtrip_arrest_title": "PŘEDVOLÁNÍ K SOUDU",
    "entrance_roadtrip_banff_arrival": "Silnice na Banff · hory, zatáčky, limit 90.",
    "entrance_roadtrip_banff_exit": "Sjezd na Banff před tebou · silnice zatáčí doprava.",
    "entrance_roadtrip_camp_arrival": "Gratulujeme! Dojeli jste na konec hry. <span class=\"camp-rsvp-cta\">Teď běžte vyplnit účast!</span>",
    "entrance_roadtrip_camp_attended_time": "Páni, to byl ale loftový den! {time} v loftu. <span class=\"camp-rsvp-cta\">Poděl se o svůj čas v potvrzení účasti.</span>",
    "entrance_roadtrip_camp_behdad_aria": "Rozesmát Behdada",
    "entrance_roadtrip_camp_finale": "Páni, to byl ale loftový den! <span class=\"camp-rsvp-cta\">Teď hurá na potvrzení účasti!</span>",
    "entrance_roadtrip_camp_fire_close": "Zavřít stavbu ohně",
    "entrance_roadtrip_camp_fire_igniting": "Oheň se rozhořívá…",
    "entrance_roadtrip_camp_fire_invite": "To je ale krásné tábořiště! Pojďme rozdělat oheň.",
    "entrance_roadtrip_camp_fire_light": "Zapálit",
    "entrance_roadtrip_camp_fire_no_logs": "Troud i podpal vyhořely. Před zapálením přidej polena.",
    "entrance_roadtrip_camp_fire_no_tinder": "Sirka zhasla. Nejdřív přidej troud.",
    "entrance_roadtrip_camp_fire_no_twigs": "Troud vyhořel. Potřeboval podpal.",
    "entrance_roadtrip_camp_fire_stack": "Naskládané",
    "entrance_roadtrip_camp_fire_teepee": "Týpí",
    "entrance_roadtrip_camp_fire_tinder": "Troud",
    "entrance_roadtrip_camp_fire_title": "Založ oheň",
    "entrance_roadtrip_camp_fire_twigs": "Třísky",
    "entrance_roadtrip_camp_food_warning": "Nikdy nenechávejte přes noc jídlo venku.",
    "entrance_roadtrip_camp_lake_aria": "Hodit žabku přes jezero Abraham",
    "entrance_roadtrip_camp_marketa_aria": "Rozesmát Markétu",
    "entrance_roadtrip_camp_pine_aria": "Shodit šišku",
    "entrance_roadtrip_camp_poplar_aria": "Rozhýbat oči na topolech",
    "entrance_roadtrip_camp_sign": "KEMP",
    "entrance_roadtrip_camp_sleep_prompt": "Připozdívá se. Uhasme oheň a pojďme spát.",
    "entrance_roadtrip_camp_tent_aria": "Otevřít nebo zavřít stan",
    "entrance_roadtrip_camping": "Kemp",
    "entrance_roadtrip_centerline": "Přejezd přes středovou čáru · −2 body.",
    "entrance_roadtrip_collision": "Náraz zezadu · ztráta 10–40 bodů, kombo od začátku.",
    "entrance_roadtrip_continue": "Pokračovat",
    "entrance_roadtrip_court_fine": "pokutu určí soud",
    "entrance_roadtrip_crash": "Čelní srážka · −100 bodů, roztříštěné sklo a zhaslý motor.",
    "entrance_roadtrip_demerit_label": "TRESTNÉ BODY",
    "entrance_roadtrip_demerit_suspended": " · řidičák pozastaven na {time}",
    "entrance_roadtrip_demerit_warning": " · varování",
    "entrance_roadtrip_drive": "Dálnice · mezerník nastaví tempomat · Enter pozastaví · vyhýbej se provozu a sbírej ♥️, 🍄, 💋, 🐸 a ∞.",
    "entrance_roadtrip_escape": "Zvěř unikla · +{points} b · kombo {combo}×.",
    "entrance_roadtrip_exit": "Opustit dálnici",
    "entrance_roadtrip_frog": "🐸 sebrána · +{points} b · kombo {combo}×.",
    "entrance_roadtrip_grade_legend": "Legenda dálnice",
    "entrance_roadtrip_grade_regular": "Výletový mazák",
    "entrance_roadtrip_grade_scenic": "Vyhlídková jízda",
    "entrance_roadtrip_grade_sunday": "Vyhlídková jízda",
    "entrance_roadtrip_heart": "♥️ sebráno · +{points} b · kombo {combo}×.",
    "entrance_roadtrip_hedgehog_collision": "Lehký střet s ježkem · ztráta 2–8 bodů, kombo od začátku.",
    "entrance_roadtrip_inf": "Vzácné ∞ sebráno · +{points} b · kombo {combo}×.",
    "entrance_roadtrip_invite_accept": "Vyjet na dálnici",
    "entrance_roadtrip_invite_title": "Jedeme na výlet!",
    "entrance_roadtrip_kiss": "💋 sebráno · +{points} b · kombo {combo}×.",
    "entrance_roadtrip_mushroom": "🍄 sebrána · +{points} b · kombo {combo}×.",
    "entrance_roadtrip_new": "Nový",
    "entrance_roadtrip_notebook_aria": "Otevřít Markétin zápisník",
    "entrance_roadtrip_notebook_close": "Zavřít Markétin zápisník",
    "entrance_roadtrip_notebook_draft": "Bezděčně vytvořili kruh. Absurdní, pomyslela si Parvaneh a rozhlédla se po ostatních, kteří si vyměňovali nejisté pohledy. Jeden z těch prvních horkých dnů na začátku léta, kdy si spálí kůži. Za mlada se honila za prvními spalujícími paprsky pro jarní opálení, ale posledních pár let chtěla svou kůži chránit za každou cenu. Přesunula se do stínu, aby unikla slunci, které rychle stoupalo k vrcholu. Ostatním zjevně nevadilo. Samozřejmě – Íránci.",
    "entrance_roadtrip_notebook_title": "Kapitola 1",
    "entrance_roadtrip_pass": "Těsné, ale čisté · +{points} b · kombo {combo}×.",
    "entrance_roadtrip_pause_line": "Pokračuj v hraní jakoukoli klávesou · Esc ukončí jízdu.",
    "entrance_roadtrip_pause_title": "POZASTAVENO",
    "entrance_roadtrip_points_short": "b",
    "entrance_roadtrip_police_arrest": "Zastaveno · policista přichází k okénku řidiče.",
    "entrance_roadtrip_police_capture": "Policie tě dohnala · vůz nuceně zpomaluje.",
    "entrance_roadtrip_police_centerline_pursuit": "Zůstal(a) jsi za dvojitou plnou čárou · zajeď k pravé krajnici a zastav.",
    "entrance_roadtrip_police_centerline_ticket": "Přejezd dvojité plné čáry · pokuta {fine} · {points} trestné body · {total}/15{status}.",
    "entrance_roadtrip_police_clear": "Policie za tebou · rychlost v toleranci.",
    "entrance_roadtrip_police_court_refused": "Nezastavil(a) jsi · {fine} · {points} trestných bodů · {total}/15{status} · jízda končí.",
    "entrance_roadtrip_police_court_stopped": "Zastaveno · policie zajíždí před tebe.",
    "entrance_roadtrip_police_escape": "Policie se vzdaluje · drž přes 215 a setřes ji.",
    "entrance_roadtrip_police_escaped": "Policie setřesena · siréna utichá.",
    "entrance_roadtrip_police_impaired_pursuit": "Zpozorována nebezpečná jízda pod vlivem · zajeď k pravé krajnici a zastav.",
    "entrance_roadtrip_police_impaired_summons": "Nebezpečná jízda pod vlivem · {fine} · {points} trestných bodů · {total}/15{status} · ztráta 250 herních bodů.",
    "entrance_roadtrip_police_pull_over": "Policie za tebou · zajeď k pravé krajnici a zastav.",
    "entrance_roadtrip_police_pursuit": "Naměřeno {speed} km/h · zajeď k pravé krajnici a zastav.",
    "entrance_roadtrip_police_refused": "Nezastavení · pokuta {fine} · {points} b. · {total}/15{status} · −1 000 bodů.",
    "entrance_roadtrip_police_stopped": "Zastaveno · policie zajíždí za tebou.",
    "entrance_roadtrip_police_summons": "Překročení o {over} km/h · {fine} · {points} trestných bodů · {total}/15{status}.",
    "entrance_roadtrip_police_ticket": "Překročení o {over} km/h · pokuta {fine} · {points} trestné body · {total}/15{status}.",
    "entrance_roadtrip_police_warning": "Trojí probliknutí · policie před tebou. Hlídej si rychlost.",
    "entrance_roadtrip_rabbit_collision": "Lehký střet se zajícem · ztráta 2–8 bodů, kombo od začátku.",
    "entrance_roadtrip_reenter": "Výlet",
    "entrance_roadtrip_resume": "Jízda pozastavena · pokračuj volantem nebo pedálem.",
    "entrance_roadtrip_route_abraham": "Jezero Abraham",
    "entrance_roadtrip_route_banff": "Banff",
    "entrance_roadtrip_route_calgary": "Calgary",
    "entrance_roadtrip_route_stage_1": "ÚSEK 1",
    "entrance_roadtrip_route_stage_2": "ÚSEK 2",
    "entrance_roadtrip_route_stage_3": "ÚSEK 3",
    "entrance_roadtrip_route_title": "Vyber cíl cesty",
    "entrance_roadtrip_stargazing_ad_infinitum": "—ad infinitum.",
    "entrance_roadtrip_stargazing_behdad_1a": "Říká se, že všechno dobré jednou končí—",
    "entrance_roadtrip_stargazing_behdad_1b": "ale tohle je teprve začátek…",
    "entrance_roadtrip_stargazing_behdad_2": "Dokud neskončí i to.",
    "entrance_roadtrip_stargazing_cassiopeia": "Kasiopeja",
    "entrance_roadtrip_stargazing_continue": "Velká moudrost utržena.",
    "entrance_roadtrip_stargazing_hint": "Klikni na zářící hvězdu nebo tahem obkresli každé souhvězdí.",
    "entrance_roadtrip_stargazing_invite": "Obloha je jasná. Klikni na ni a podívej se nahoru.",
    "entrance_roadtrip_stargazing_marketa_1a": "…a špatné věci také končí—",
    "entrance_roadtrip_stargazing_marketa_1b": "což je také dobře.",
    "entrance_roadtrip_stargazing_marketa_quote_1": "Když něco skončí,",
    "entrance_roadtrip_stargazing_marketa_quote_2": "něco dalšího začne",
    "entrance_roadtrip_stargazing_title": "Pozorování hvězd",
    "entrance_roadtrip_stargazing_ursa_major": "Velká medvědice",
    "entrance_roadtrip_stargazing_ursa_minor": "Malá medvědice",
    "entrance_roadtrip_stew_barley": "Ječmen",
    "entrance_roadtrip_stew_beans": "Fazole",
    "entrance_roadtrip_stew_beef": "Hovězí",
    "entrance_roadtrip_stew_burnt_serve": "Tímhle by šla opravit dálnice.",
    "entrance_roadtrip_stew_carrots": "Mrkev",
    "entrance_roadtrip_stew_celery": "Celer",
    "entrance_roadtrip_stew_chicken": "Kuřecí",
    "entrance_roadtrip_stew_chilies_first": "Thajské",
    "entrance_roadtrip_stew_chilies_second": "chilli",
    "entrance_roadtrip_stew_cook": "Vařit",
    "entrance_roadtrip_stew_cooking_feedback": "Jídlo se vaří v kotlíku nad ohněm.",
    "entrance_roadtrip_stew_coriander": "Koriandr",
    "entrance_roadtrip_stew_crate": "JÍDLO",
    "entrance_roadtrip_stew_curry_first": "Kari",
    "entrance_roadtrip_stew_curry_second": "pasta",
    "entrance_roadtrip_stew_garlic": "Česnek",
    "entrance_roadtrip_stew_ginger": "Zázvor",
    "entrance_roadtrip_stew_invite": "Pojďme uvařit něco dobrého v kotlíku.",
    "entrance_roadtrip_stew_lamb": "Jehněčí",
    "entrance_roadtrip_stew_missing": "Přidej jeden protein a jeden základ.",
    "entrance_roadtrip_stew_mushrooms": "Houby",
    "entrance_roadtrip_stew_no_fire": "Před vařením založ oheň.",
    "entrance_roadtrip_stew_onion": "Cibule",
    "entrance_roadtrip_stew_overcooked_feedback": "Jídlo se převařilo. Klikni na kotlík a začni znovu.",
    "entrance_roadtrip_stew_pasta": "Těstoviny",
    "entrance_roadtrip_stew_pepper_first": "Černý",
    "entrance_roadtrip_stew_pepper_second": "pepř",
    "entrance_roadtrip_stew_pork": "Vepřové",
    "entrance_roadtrip_stew_potatoes": "Brambory",
    "entrance_roadtrip_stew_protein": "PROTEIN",
    "entrance_roadtrip_stew_raw_serve": "Ještě syrové. Poklici dolů, trpělivost nahoru.",
    "entrance_roadtrip_stew_ready_feedback": "Jídlo je hotové. Servíruj, dokud je akorát.",
    "entrance_roadtrip_stew_reset": "Začít znovu",
    "entrance_roadtrip_stew_rice": "Rýže",
    "entrance_roadtrip_stew_salt": "Sůl",
    "entrance_roadtrip_stew_serve": "Servírovat",
    "entrance_roadtrip_stew_served_feedback": "Dvě teplé misky a dva velmi spokojení táborníci.",
    "entrance_roadtrip_stew_starch": "ZÁKLAD",
    "entrance_roadtrip_stew_tofu": "Tofu",
    "entrance_roadtrip_stew_tomato_first": "Rajčatový",
    "entrance_roadtrip_stew_tomato_second": "protlak",
    "entrance_roadtrip_suspended": "Řidičák pozastaven · výlet je dočasně nedostupný.",
    "entrance_roadtrip_suspended_short": "Pozastaveno · {time}",
    "entrance_roadtrip_transport_paused": "Pokračuj v hraní jakoukoli klávesou · Esc ukončí jízdu.",
    "entrance_roadtrip_unlocked": "Všech 10 pokojů je prozkoumaných · dáme si výlet?",
    "entrance_roadtrip_wildlife_collision": "Střet se zvěří · ztráta 20–60 bodů, kombo od začátku.",
    "explore_balcony": "Toulej se — balkon je to nejlepší. 🌅",
    "explore_cuddly": "Toulej se — zavrtej se a prozkoumávej. 🐙",
    "explore_garden": "Toulej se — zahrada je plná detailů. 🌿",
    "explore_kitchen": "Toulej se — kuchyně skrývá nejen kafe. ☕",
    "explore_office": "Toulej se — pracovna je spíš hra než práce. 🖥️",
    "flair_hint": "Pohybuj Pouriou a chytej ozdoby 🍋; vyhni se vose 🐝.",
    "garden": "Zalij kytku, zahraj na nástroj, zapal svíčky.",
    "garden_need_candles": "Teď zapal svíčky.",
    "garden_need_music": "Teď zahraj na nástroj.",
    "garden_need_music_candles": "Zahraj na nástroj a zapal svíčky.",
    "garden_need_water": "Teď zalij kytku.",
    "garden_need_water_candles": "Zalij kytku a zapal svíčky.",
    "garden_need_water_music": "Zalij kytku a zahraj na nástroj.",
    "garden_party": "Párty jede — správna věc, tanec volá.",
    "intro": "Cvičte se v umění toulání bez cíle.",
    "intro_guide": "Nápovědy a pokyny se objevují tady.",
    "intro_guide_nav": "Navigace je tady.",
    "kitchen": "Zapni La Maz → spusť El Maz → uvař kafe.",
    "kitchen_again": "Jen do toho — udělej si další espresso. ☕",
    "kitchen_bar": "Bar je otevřený — sleduj, jak <em>Pouria</em> míchá drink. Nebo si nějaký objednej. 🍸",
    "kitchen_bar_night": "Bar je otevřený. Řekni si <em>Pouriovi</em> o drink… 🍸",
    "kitchen_brew": "Teď uvař espresso.",
    "kitchen_grind": "Teď namel kafe.",
    "kitchen_grinder_empty": "Mlýnku došlo zrnkové kafe.",
    "kitchen_grinder_refill": "Zásobník je zase plný — čerstvá zrna. ☕",
    "kitchen_need_grind": "Nejdřív umel kafe.",
    "kitchen_need_knockout": "Nejdřív vyklepej staré kafe.",
    "kitchen_need_power": "Nejdřív zapni kávovar.",
    "kitchen_need_tamp": "Teď kafe upěchuj.",
    "kitchen_sip": "Dej si. ☕",
    "kitchen_warming_up": "Nejdřív ho nech zahřát.",
    "lower_bathroom": "Koupelna · pohraj si s vybavením.",
    "lower_bedroom": "Ložnice · okno volá.",
    "lower_cinema": "Kino · vyber si film.",
    "lower_dungeon": "Žalář · stará hra se probudila.",
    "lower_entrance": "Fancy-Stupid! · klikni na silnici a usedni za volant.",
    "lower_entrance_before_party": "Auto si můžeš zatím jen vyzkoušet · nejdřív dokonči horní stopovačku a odemkni párty.",
    "lower_entrance_locked": "Auto si můžeš zatím jen vyzkoušet · výlet se odemkne po návštěvě všech 10 pokojů.",
    "lower_entrance_ready": "Všech 10 pokojů navštíveno · klikni na silnici a vyraz na výlet.",
    "octi_escape_hint": "Sleduj, kam se Octi schová, a pak klikni na polštář.",
    "octi_escape_invite": "Octi pokukuje po polštářích. Zmáčkni ji ještě jednou. 🐙",
    "octi_escape_one": "Máš ji. Zbývají dvě skrýše.",
    "octi_escape_two": "Znovu. Ještě poslední skrýš.",
    "octi_escape_win": "Chycena! Octi odcupitá zpátky na truhlu. 🐙",
    "octi_escape_wrong": "Jen polštář. Octi znovu vykukuje…",
    "office": "Nejdřív zavolej do Prahy — na notebooku.",
    "office_block_party": "Zkus rozsvícená okna na balkoně.",
    "office_call": "Nejdřív zavolej do Prahy — na notebooku.",
    "office_computer": "Pohraj si se stolním počítačem (ne s notebookem).",
    "office_find": "Najdi vitrážového motýla.",
    "office_hangup": "Teď zavěs.",
    "office_hint": "Až skončíš, zhasni světla.",
    "party_ended": "Párty prozatím skončila, hra ne. Loft i aplikace jsou pořád tvoje.",
    "party_exit_hint": "Vypínač ukončí párty, ne hru. Aplikace zůstávají otevřené.",
    "party_rooms_complete": "Viděl(a) jsi všech 10 místností. Ideální den na výlet!",
    "party_rooms_incomplete": "Prozkoumáno: {n} z 10 místností. Zkoumej dál.",
    "party_switch_coach": "Až nastane čas, ukonči párty tady.",
    "prince_dark": "Není dost světla.",
    "prince_gate_secret": "Žalář · za mříží zamrkalo něco s korunkou.",
    "recovery_continue": "▶ Pokračovat",
    "recovery_days": "před {n} d",
    "recovery_hours": "před {n} h",
    "recovery_just_now": "právě teď",
    "recovery_meta": "Uloženo {room} · {age}",
    "recovery_minutes": "před {n} min",
    "recovery_restart": "↻ Začít znovu",
    "recovery_title": "Vítej zpátky",
    "room_progress": "Navštíveno: {n}/10 · zkoumej dál.",
    "room_visit_bathroom_few": "Tady je koupelna. Zbývají ještě {n} místnosti.",
    "room_visit_bathroom_many": "Tady je koupelna. Zbývá ještě {n} místností.",
    "room_visit_bathroom_one": "Tady je koupelna. Zbývá ještě 1 místnost.",
    "room_visit_bedroom_few": "Tady je ložnice, kdyby sis potřeboval odpočinout. Zbývají ještě {n} místnosti.",
    "room_visit_bedroom_many": "Tady je ložnice, kdyby sis potřeboval odpočinout. Zbývá ještě {n} místností.",
    "room_visit_bedroom_one": "Tady je ložnice, kdyby sis potřeboval odpočinout. Zbývá ještě 1 místnost.",
    "room_visit_cinema_few": "Tady je kino. Zbývají ještě {n} místnosti.",
    "room_visit_cinema_many": "Tady je kino. Zbývá ještě {n} místností.",
    "room_visit_cinema_one": "Tady je kino. Zbývá ještě 1 místnost.",
    "room_visit_complete": "To je celý loft. Vyjdi před dům.",
    "room_visit_complete_party": "To je celý loft. Vyjdi na ulici.",
    "room_visit_dungeon_few": "Tohle je žalář. Sem jdeš sám(a). Zbývají ještě {n} místnosti.",
    "room_visit_dungeon_many": "Tohle je žalář. Sem jdeš sám(a). Zbývá ještě {n} místností.",
    "room_visit_dungeon_one": "Tohle je žalář. Sem jdeš sám(a). Zbývá ještě 1 místnost.",
    "room_visit_entrance_complete": "Celý loft je prozkoumaný. Silnice čeká hned venku.",
    "room_visit_entrance_complete_party": "Celý loft je prozkoumaný. Silnice čeká hned venku.",
    "room_visit_entrance_few": "Tady je hlavní vchod. Před výletem prozkoumej ještě {n} místnosti.",
    "room_visit_entrance_many": "Tady je hlavní vchod. Před výletem prozkoumej ještě {n} místností.",
    "room_visit_entrance_one": "Tady je hlavní vchod. Před výletem prozkoumej ještě 1 místnost.",
    "tetris_game_over": "Konec hry · Enter: hrát znovu · Esc: ukončit.",
    "tetris_hint": "Kliknutím otáčej; tažením posouvej nebo shazuj. Klávesy: ← → ↑, mezerník.",
    "tetris_touch_game_over": "Konec hry · Klepni: hrát znovu · ×: ukončit.",
    "tetris_touch_hint": "Klepnutím otáčej; tažením posouvej nebo shazuj. × ukončí hru."
  },
  "hunt_title": "Den v loftu",
  "install_dismiss": "Zavřít",
  "install_ios_hint": "Klepni na Sdílet, pak „Přidat na plochu“",
  "install_label": "Nainstalovat appku",
  "kbd_arrows": "předchozí / další místnost",
  "kbd_console": "otevřít / zavřít konzoli",
  "kbd_d": "den ↔ noc",
  "kbd_devices": "monitor / notebook / telefon",
  "kbd_digits": "místnost nahoře",
  "kbd_enter": "pokračovat v hádance · pozastavit výlet",
  "kbd_esc": "zavřít / zpět · výlet nejdřív pozastaví, pak zruší",
  "kbd_f": "celá obrazovka",
  "kbd_g": "další zpráva v telefonu",
  "kbd_kitten": "přepnout kotě",
  "kbd_lower_digits": "místnost dole",
  "kbd_manual": "Herní manuál",
  "kbd_n": "další skladba (tanec / klavírní sonáta / píseň)",
  "kbd_party": "spustit párty",
  "kbd_qm": "tento seznam",
  "kbd_roadtrip": "odemknout všechny místnosti pro výlet",
  "kbd_s": "změna sezóny",
  "kbd_shift_arrows": "předchozí / další významný den",
  "kbd_shift_updown": "hodiny +30 / −30 min",
  "kbd_slash": "otevřít / zavřít zprávy",
  "kbd_space": "akce ve hře / média · nastavit tempomat",
  "kbd_t": "další trip",
  "kbd_tab": "otevřít / zavřít pohled na celý loft",
  "kbd_title": "Klávesové zkratky",
  "kbd_trips": "rajský plyn · houbičky · LSD · žába · dmt · molly · k. · iboga",
  "kbd_u": "přepnout UV / černé světlo",
  "kbd_vertical": "sestoupit / vrátit se",
  "kbd_watch": "kdo tu je? (soupis lidí v místnosti)",
  "laptop_amour": "Láska",
  "laptop_calling": "Volání…",
  "laptop_connecting": "Spojuji…",
  "laptop_ctx_end": "Ukončit hovor",
  "laptop_ctx_translate": "Přeložit",
  "laptop_date": "10. července",
  "laptop_lplace": "Lübeck",
  "laptop_place": "Praha",
  "laptop_sweet1": "Novinky:",
  "laptop_sweet2": "zbytek našich",
  "laptop_sweet3": "životů ♥",
  "life_blinker": "blikač",
  "life_gen": "GEN",
  "life_glider": "kluzák",
  "life_help_copy": "Hra pro neexistujícího hráče: po nakreslení počátečního vzoru pravidla běží sama. Buňka se narodí se 3 sousedy a přežije s 2 nebo 3. Nakresli buňky, pak spusť hru, jdi krok po kroku, změň rychlost nebo zkus vzor. Mezerník pozastaví hru. <a href=\"https://cs.wikipedia.org/wiki/Conwayova_hra_%C5%BEivota\" target=\"_blank\" rel=\"noopener\">Wikipedie</a>.",
  "life_help_title": "Conwayova Hra života",
  "life_pulsar": "pulsar",
  "linux_fail": "linux se nenabootoval — offline, nebo se zaseklo stahování. zavři a znovu otevři.",
  "linux_hint": "zkus: hb-shape /root/test.ttf 'markéta ∞ behdad' · hb-info /root/test.ttf — ženichova sázecí knihovna sází (a prosvěcuje) svatební písmo Fraunces.",
  "linux_loading": "bootujeme linux… ~9 MB, jen napoprvé",
  "linux_wait": "pořád bootujeme… prompt se ukáže, až jádro naběhne.",
  "linux_welcome": "loftový linux — celé x86 PC přímo tady ve stránce (v86/WebAssembly), bootuje skutečné jádro.",
  "lower_portal_insist": "Trvám na tom.",
  "lower_portal_unlock": "Odemknout",
  "lower_rooms_clue": "Loft možná pár pokojů schoval před očima.",
  "madla_fam": "Madla",
  "madla_place": "noční služba, Německo",
  "mail_back": "‹ Doručená",
  "mail_body_lore": "ahoj.\nbudeme se brát — dvakrát: 1. května 2027 v Edmontonu a 10. července 2027 v Praze.\npřijeďte na jednu, přijeďte na obě — všichni naši blízcí jsou vítáni, v malém i ve velkém.\nmezi oslavami se loftu stýská po návštěvách. — m ∞ b",
  "mail_body_rsvp": "gauč vám drží místo.\nklikněte na odpovědět a zbavte nás napětí.",
  "mail_body_spam": "to jsme my. ti žhaví nezadaní jsme my.\nbudeme se brát.\nodhlásit odběr můžete na svatbě.",
  "mail_cancel": "Zrušit",
  "mail_cc": "Kopie",
  "mail_compose": "Napsat",
  "mail_compose_subject": "pozdrav z loftu",
  "mail_from_lore": "markéta ∞ behdad",
  "mail_from_rsvp": "loft",
  "mail_from_spam": "naprosto-seriozni-slevy",
  "mail_inbox_title": "doručená",
  "mail_message": "Zpráva",
  "mail_reply_body": "Ahoj Markéto a Behdade!\n\nAno! Počítejte se mnou — Edmonton / Praha / obojí.\n\n",
  "mail_reply_btn": "Odpovědět",
  "mail_reply_subject": "Re: budete tam?",
  "mail_send": "Odeslat",
  "mail_subj_lore": "takže, bereme se dvakrát",
  "mail_subj_rsvp": "budete tam?",
  "mail_subj_spam": "ŽHAVÍ NEZADANÍ PŘÍMO VE VAŠEM LOFTU 🔥",
  "mail_subject": "Předmět",
  "mail_to": "Komu",
  "marketa_url": "https://marketajakesova.ca/cs/",
  "meteor_deltaaquariids": "🌠 delta akvaridy",
  "meteor_draconids": "🌠 drakonidy",
  "meteor_geminids": "🌠 geminidy",
  "meteor_leonids": "🌠 leonidy",
  "meteor_lyrids": "🌠 lyridy",
  "meteor_orionids": "🌠 orionidy",
  "meteor_perseids": "🌠 perseidy",
  "meteor_quadrantids": "🌠 kvadrantidy",
  "meteor_taurids": "🌠 tauridy",
  "meteor_ursids": "🌠 ursidy",
  "mines_lose": "Spustili jste prsten!<br>(Stejně k tomu jednou dojít muselo.)",
  "mines_win": "Prsten zůstává překvapením.",
  "mix_campari": "Campari",
  "mix_curacao": "Modré curaçao",
  "mix_gin": "Gin",
  "mix_house": "Domácí míchanice",
  "mix_vermouth": "Sladký vermut",
  "mol_caption": "máme chemii",
  "mol_caption_ethanol": "Realita je iluze způsobená nedostatkem alkoholu.",
  "mol_caption_thc": "To je táák hustý, kámo.",
  "mol_name_acid": "LSD",
  "mol_name_dmt": "N,N-DMT",
  "mol_name_ethanol": "Etanol",
  "mol_name_froggies": "5-MeO-DMT",
  "mol_name_iboga": "Ibogain",
  "mol_name_ketamine": "Ketamin",
  "mol_name_molly": "MDMA",
  "mol_name_nitrous": "Oxid dusný",
  "mol_name_shrooms": "Psilocybin",
  "mol_name_thc": "THC",
  "mol_street_acid": "kyselina",
  "mol_street_dmt": "DMT",
  "mol_street_ethanol": "chlast",
  "mol_street_froggies": "žabičky",
  "mol_street_iboga": "iboga",
  "mol_street_ketamine": "k",
  "mol_street_molly": "molly",
  "mol_street_nitrous": "rajský plyn",
  "mol_street_shrooms": "houbičky",
  "mol_street_thc": "tráva",
  "mom_bouquet": "Házení kytice",
  "mom_cake": "Krájení dortu",
  "mom_chairlift": "Zvedání na židlích (hora)",
  "mom_firstdance": "První tanec",
  "mom_groupphoto": "Společné foto",
  "mom_slowdance": "Pomalý tanec",
  "mom_sparklers": "Prskavky na rozloučenou",
  "mom_toasts": "Přípitky",
  "mon_about_home": "místě, kterému my (Markéta & behdad) říkáme domov.",
  "mon_about_party": "a najděte oslavu.",
  "mon_about_title": "Vítejte v The Loft",
  "mon_about_wander": "Procházejte se, uvařte si kávu, poznejte naše blízké",
  "mon_ctx_copy": "Kopírovat",
  "mon_ctx_cut": "Vyjmout",
  "mon_ctx_kill": "Ukončit aplikaci",
  "mon_ctx_open": "Otevřít",
  "mon_ctx_paste": "Vložit",
  "mon_ctx_reset_eq": "Obnovit ekvalizér",
  "mon_ctx_select_all": "Vybrat vše",
  "mon_ctx_stop": "Zastavit",
  "mon_ctx_uninstall": "Odinstalovat",
  "mon_help_click": "Klikni na všechno! Pravé tlačítko nabízí další možnosti.",
  "mon_help_clue": "Sleduj nápovědu nad scénou.",
  "mon_help_keyboard": "Stiskni ? pro úplný seznam ovládání.",
  "mon_help_manual": "Herní manuál ↗",
  "mon_help_title": "Nápověda",
  "mon_lock_behdad": "Behdad",
  "mon_lock_blue": "Markétina modrá bekovka",
  "mon_lock_marketa": "Markéta",
  "mon_lock_pink": "Behdadova růžová placatá čepice",
  "mon_lock_prompt": "Přiřaďte čepice nebo dvakrát stiskněte Caps Lock.",
  "mon_lock_title": "CAPS LOCK",
  "mon_lock_unlocked": "odemčeno",
  "mon_reboot_gag": "Zkusili jste zavřít všechna okna?",
  "mon_shutdown_gag": "Krásný večer v loftu!",
  "mon_sleep_gag": "Je čas si zdřímnout.. Zzz...",
  "mon_sys_credits": "Titulky",
  "mon_sys_help": "Nápověda",
  "mon_sys_lock": "Zamknout",
  "mon_sys_reboot": "Restartovat",
  "mon_sys_shutdown": "Vypnout",
  "mon_sys_sleep": "Uspat",
  "mon_sys_system": "Systém",
  "mon_sys_tagline_1": "The Loft: kde se setkává umělá a vyšší inteligence.",
  "mon_sys_title": "Loft OS",
  "mon_sys_website": "O nás",
  "mon_system_info_browser": "Prohlížeč",
  "mon_system_info_full": "Plné detaily",
  "mon_system_info_graphics": "Grafika",
  "mon_system_info_hardware": "Hardware",
  "mon_system_info_input": "Ovládání",
  "mon_system_info_limitations": "Známá omezení",
  "mon_system_info_measuring": "Měříme…",
  "mon_system_info_motion_reduced": "Omezený pohyb",
  "mon_system_info_motion_standard": "Běžný pohyb",
  "mon_system_info_performance": "Výkon",
  "mon_system_info_pointer": "Ukazatel",
  "mon_system_info_ready": "Bez známých potíží",
  "mon_system_info_recommendation": "Nejlépe funguje v nejnovějším Chromu pro počítače.",
  "mon_system_info_reduced": "Omezené detaily",
  "mon_system_info_status": "Stav",
  "mon_system_info_title": "Systémové informace",
  "mon_system_info_touch": "Dotyk + ukazatel",
  "mon_system_info_unreported": "Nezjištěno",
  "mon_system_info_upgrade": "Doporučujeme aktualizovat",
  "msg_action_coach": "Zkus šipky",
  "msg_album_body": "přibyla nová fotka — dáme další selfie!",
  "msg_albumfull_body": "cvakám celý večer 📸 album se ti plní — mrkni na něj",
  "msg_ali_from": "Ali",
  "msg_ali_love_body": "<em>Habibi</em>s, mám vás všechny rád!",
  "msg_alireza_from": "Alireza",
  "msg_aspen_banter_body": "jestli mě uvidíš schovanou za kytkou, dělej dál přesně to, co tě rozesmálo 📸",
  "msg_aspen_from": "Aspen",
  "msg_athena_banter_body": "hlášení k programu: jsme přesně načas, pokud se nikdo nepodívá na program. ✨",
  "msg_athena_from": "Athena",
  "msg_ayushi_from": "Ayushi",
  "msg_badge_coach": "Nová zpráva. Klepni a přečti si ji.",
  "msg_baharak_from": "Baharak",
  "msg_bahareh_from": "Bahareh",
  "msg_bbq_body": "jdeme roztopit gril 🔥🍔",
  "msg_bbq_cheer_madla_body": "běžím — schovej mi opečené tofu 🔥",
  "msg_bbq_cheer_pouria_body": "pozdě, už držím talíř 🍽️",
  "msg_behdad_aspen_reply_body": "Aspen se pěkně rozvětvuje. 🌿",
  "msg_behdad_from": "behdad",
  "msg_behdad_to_marketa_from": "behdad → markéta",
  "msg_bouquet_body": "házení kytice!! kdo ji chytí?? 💐",
  "msg_cake_body": "dort je venku!! pojďte ho nakrojit vy dva 🍰🔪",
  "msg_chairlift_body": "sežeňte židle — a jde se nahoru!! HORA! 🪑🎉",
  "msg_charlie_body_a": "Ahoj, tady Charlie. Tenhle loft znám docela dobře — zeptej se mě na cokoli nebo si přijď popovídat. 💬",
  "msg_charlie_body_b": "Potřebuješ nápovědu, navigaci nebo trochu společnosti? Napiš mi. —Charlie 💬",
  "msg_charlie_body_c": "Zdravím z počítače. Jsem Charlie; znám loft, jeho obyvatele i většinu tajemství. 💬",
  "msg_charlie_body_d": "Hledáš cestu, odpověď, nebo záminku zmizet z parketu? Jsem tu. —Charlie 💬",
  "msg_charlie_body_e": "Jsem Charlie. Zeptej se mě na svatbu, loft nebo na to, co se tu právě semlelo. 💬",
  "msg_charlie_body_f": "Psst. Když je tenhle loft trochu matoucí, nejspíš vím, co se děje. Nejspíš. —Charlie 💬",
  "msg_charlie_from": "Charlie",
  "msg_chinnell_from": "Chinnell",
  "msg_copy": "Kopírovat",
  "msg_danesh_body": "kámo, ten tvůj dav je TAAAAK ŽHAVEJ! 🔥",
  "msg_danesh_from": "DJ Danesh",
  "msg_downstairs_bathroom_body": "Kde je toaleta?",
  "msg_downstairs_bedroom_body": "Potřebuju si na minutku lehnout.",
  "msg_downstairs_cinema_ask_body": "Slyšel(a) jsem, že máte skvělé domácí kino.",
  "msg_downstairs_cinema_reply_body": "Pojď se podívat!",
  "msg_downstairs_dungeon_body": "Daaeee, v zahradě jsou dveře do kobky.",
  "msg_downstairs_entrance_body": "Nechceš vyrazit na výlet?",
  "msg_downstairs_roadtrip_go_body": "Jedeme!",
  "msg_downstairs_roadtrip_journey_body": "Cesta je cíl.",
  "msg_downstairs_roadtrip_where_body": "Kam?",
  "msg_dusk_body": "zatmění na balkoně 🌑 přijdeš ven?",
  "msg_empty": "Zatím žádné zprávy — svatební parta sem během dne napíše.",
  "msg_farhang_banter_body": "mám mikrofon a očividně nade mnou není žádný dospělý dozor. 🎤",
  "msg_farhang_from": "Farhang",
  "msg_fireworks_body": "ČAS NA FINÁLE 🎆 pojď ven na balkon!",
  "msg_firstdance_body": "Připraveni na první tanec? 💃",
  "msg_flair_body": "Potřebuju pauzu 🍸",
  "msg_fresh_air_body": "Nechceš na čerstvý vzduch?",
  "msg_group_body": "tak tančíš, nebo co?? 💃",
  "msg_group_from": "Svatební parta",
  "msg_groupphoto_body": "📸 všichni na společné foto! pojďte k sobě 🤗",
  "msg_hamid_bbq_done_body": "gril poražen. pod mým dohledem nikdo neodejde hladový 🔥✅",
  "msg_hamid_food_body": "gril je otevřený — první várka je hotová, pojďte si pro ni, dokud je teplá 🔥🍔🌽",
  "msg_hamid_from": "Hamid",
  "msg_hamid_verse2_body": "<em>رفتم تو آب، آب اومده تا سرِ زانوم.</em>",
  "msg_hamid_verse_body": "<em>من پسرِ باادبِ میرزامشیرم</em>",
  "msg_hannah_banter_body": "oficiální gymnastická známka pro tenhle parket: 10/10 🤸",
  "msg_hannah_from": "Hannah",
  "msg_hannah_piano_body_a": "<em>daee joon</em>, můžu si zahrát na piano?",
  "msg_hannah_piano_body_b": "Mami, můžu si zahrát na piano?",
  "msg_hannah_piano_body_c": "Tati, můžu si zahrát na piano?",
  "msg_heat_body": "Mohl by někdo přinést něco studeného? 🧊",
  "msg_input_placeholder": "Napsat svatební partě…",
  "msg_invaders_body": "Irene, viděla jsi v pracovně mimozemšťany? 👾",
  "msg_irene_banter_body": "zkontrolovala jsem to: párty není validní Python, ale stejně běží 🐍",
  "msg_irene_from": "Irene",
  "msg_irene_games_body": "<em>daeeee</em> nudím se. můžu si na počítači zahrát hry?",
  "msg_jay_bbq_satisfied_body": "Z moci mně svěřené tímto oficiálně prohlašuji svůj hlad za ukojený. 🌿⚖️",
  "msg_jay_from": "Jay",
  "msg_jukebox_body": "přání jsou otevřená 🎧 klikni a vyber další písničku",
  "msg_kidsasleep_body_a": "děti konečně spí 😴",
  "msg_kidsasleep_body_b": "děti KONEČNĚ usnuly 😴 ať tě ani nenapadne je vzbudit",
  "msg_kidsloose_body_a": "děti jsou zase na svobodě! 🙃",
  "msg_kidsloose_body_b": "a už jsou zase vzhůru 🙃 pošlete posily",
  "msg_lanterns_body": "pustíme lampiony přání 🏮 něco si přej ✨",
  "msg_lastdance_body": "poslední tanec — chyťte si svého člověka 💞",
  "msg_lastsong_body": "poslední písnička! ať stojí za to 🎧",
  "msg_madla_from": "Madla",
  "msg_mahzad_from": "Mahzad",
  "msg_mark_all_read_short": "✓ vše",
  "msg_mark_read": "Označit jako přečtené.",
  "msg_mark_unread": "Označit jako nepřečtené.",
  "msg_marketa_from": "markéta",
  "msg_marketa_to_behdad_from": "markéta → behdad",
  "msg_mb_body": "potvrdil(a) jsi už účast? 😉 žádný tlak. (trochu tlaku.)",
  "msg_mb_from": "markéta & behdad",
  "msg_new_divider": "Nové",
  "msg_patricia_from": "Patricia",
  "msg_pouria_banter_body": "dnešní nový koníček: připomínat všem, ať pijí vodu 💧",
  "msg_pouria_body": "bar je zase otevřený 🍸 padej sem",
  "msg_pouria_farhang_body": "Farhang, <em>chetori chaghal?</em>",
  "msg_pouria_from": "Pouria",
  "msg_reply": "Odpovědět…",
  "msg_replying_to": "Odpovídáš {name}",
  "msg_search_none": "žádné zprávy neodpovídají hledání.",
  "msg_search_placeholder": "hledat zprávy…",
  "msg_sina_from": "Sina",
  "msg_slowdance_body": "tak DJi, teď něco pomalého — chyťte si svého člověka 🥰🕯️",
  "msg_smores_body": "kdo chce opékat marshmallows? 🔥🍫",
  "msg_sparklers_body": "✨ prskavky dopředu na rozloučenou — udělejte tunel!",
  "msg_spencer_from": "Spencer",
  "msg_storm_body": "blíží se bouřka! ⛈️",
  "msg_sunrise_body": "počkat, to už je východ slunce?! 😳☀️ protáhli jsme to celou noc",
  "msg_sunset_baharak_awake_body": "Hannah! ty taky — proč jsi ještě vzhůru?! 😳",
  "msg_sunset_bahareh_awake_body": "Irene! proč jsi ještě vzhůru?! 😳",
  "msg_sunset_bed_body": "Jdu spát. Poslední vzhůru ať vypne párty — vypínač je na zdi. 😴",
  "msg_sunset_body": "ten západ slunce je NESKUTEČNÝ 🌅 pojď na balkon",
  "msg_sunset_hannah_tattoo_body": "můžu ti nakreslit další tetování? ✍️🖋️",
  "msg_sunset_irene_code_body": "můžu na počítači v Pythonu nakreslit něco želvou? 🐢🐍🎨",
  "msg_sunset_magicbox_body": "neeeeeeeeeebo… kouzelná krabice a jedeme dál? 👀✨",
  "msg_toasts_body": "🥂 čas na přípitek! vezmi si skleničku — Ali a Farhang chtějí říct pár slov",
  "msg_trip_body_a": "Čas na vitamíny? 💊",
  "msg_trip_body_b": "kdo má nějaké párty pomocníky? 😜",
  "msg_trip_body_c": "kouzelná krabice volá… 🍄✨",
  "msg_trip_body_d": "mrkne někdo na kouzelnou krabici? 👀",
  "msg_trip_body_e": "párty výbava je v kouzelné krabici 🎁",
  "msg_trip_body_f": "dáme si malý výlet? 🌈",
  "msg_unread_only_short": "nové",
  "msg_visit_ali_a": "hele, jste vy dva doma? jsme hned za rohem 🍷",
  "msg_visit_alireza_a": "doma? vezeme suvenýry z cesty ✈️",
  "msg_visit_ayushi_a": "jste doma? jsem poblíž a chystám velkolepý příchod ✨",
  "msg_visit_baharak_a": "<em>salám azíz</em>, jste doma? mám s sebou Paymana a Hannah 🌸",
  "msg_visit_bahareh_a": "jste doma, <em>azíz</em>? Irene se na vás moc těší 👧",
  "msg_visit_body_a": "jste doma? 🏠",
  "msg_visit_body_b": "jste doma, hrdličky? 💕",
  "msg_visit_body_c": "chcete návštěvu? 👀",
  "msg_visit_body_d": "ťuk ťuk — jste tam? ✊",
  "msg_visit_body_e": "jsme kousek, jste doma? 🚶",
  "msg_visit_body_f": "kafe platíte vy, jestli jste doma ☕",
  "msg_visit_body_g": "chybíte nám — jste teď doma? 🥺",
  "msg_visit_body_h": "krátká zastávka? jste doma? 🔔",
  "msg_visit_body_i": "máte pro nás otevřeno? 🚪",
  "msg_visit_farhang_a": "doma? s Lauren jsme hned za rohem 🎩",
  "msg_visit_hamid_a": "hele, jste doma? s Athenou bychom se rádi stavili 💛",
  "msg_visit_madla_a": "ahoj! jste doma? jsme tu všichni i s myškami 🐭",
  "msg_visit_patricia_a": "doma? děti se na vás dva strašně těší! 🧒👶",
  "msg_visit_spencer_a": "ahoj!! jste doma? rádi bychom se stavili 🤗",
  "msg_you_from": "Ty",
  "name_patricia_daughter": "Patriciina dcera",
  "name_patricia_son": "Patriciin syn",
  "notes_email_intro": "Ahoj Markéto a Behdade!\n\nTady je vzkaz z vašeho loftu:",
  "notes_email_subject": "Malý vzkaz z vašeho loftu 💌",
  "notes_placeholder": "nechte nám pár slov…",
  "notes_send": "Gmail",
  "notes_send_lead": "Poslat nám",
  "notes_send_mail": "E-mail",
  "notes_write_lead": "napište nám vzkaz",
  "np": {
    "aqua": "Zvuky akvária",
    "bandari": "Bandari",
    "bhangra": "Bhangra",
    "bulgar": "Klezmer bulgar",
    "coffee": "Pomalá káva",
    "cumbia": "Cumbia",
    "disco": "Disco",
    "dupak": "Dupák",
    "furiant": "Český furiant",
    "horah": "Hora",
    "polka": "Polka",
    "salsa": "Salsa",
    "swing": "Swing",
    "tango": "Tango",
    "techno": "Techno",
    "totoro": "Lesní déšť",
    "waltz": "Valčík",
    "workout": "Rytmus na cvičení"
  },
  "occ_banner_bbq": "🍖 Den grilování",
  "occ_banner_brunch": "🍳 Zahradní brunch",
  "occ_banner_wed_edm": "💍 Svatba v Edmontonu",
  "occ_banner_wed_prg": "💍 Svatba v Praze",
  "occ_invite_bbq": "dnes grilujeme na balkoně 🍖 přijď na BBQ!",
  "occ_invite_brunch": "dnes zahradní brunch v Praze 🍳 přijď za rodinou!",
  "occ_invite_wed_edm": "dnes je naše svatba v Edmontonu! 💍 přijď to s námi oslavit",
  "occ_invite_wed_prg": "dnes je naše svatba v Praze! 💍 přijď to s námi oslavit",
  "occasion_activate": "spustit tento den",
  "office_pouf_sock_found": "Dvě medaile — a ztracená ponožka. Samozřejmě.",
  "pacman_kill": "DUCHOVÉ VYHRÁLI",
  "pacman_win": "BLUDIŠTĚ HOTOVO",
  "pb_btn_cancel": "Zrušit",
  "pb_btn_download": "⬇ Stáhnout",
  "pb_btn_email": "E-mail",
  "pb_btn_gmail": "Gmail",
  "pb_btn_retake": "↺ Znovu",
  "pb_confirm_no": "Zrušit",
  "pb_confirm_q": "Otevřít fotokoutek?",
  "pb_confirm_yes": "📷 Zapnout kameru",
  "pb_email_body": "Ahoj Markéto a Behdade!\n\nTeď sem vlož fotku — máš ji ve schránce (Ctrl/Cmd+V).\n\nUvidíme se na svatbě!",
  "pb_email_subject": "Fotka z vašeho fotokoutku v loftu 📸",
  "pb_err_1": "kamera tu není",
  "pb_err_2": "nic se neděje 🙂",
  "pb_err_ok": "OK",
  "pb_frame_heading": "Svatební rámeček",
  "pb_frame_hearts": "∞ srdíčka",
  "pb_frame_married": "Přijdu!",
  "pb_frame_married_text": "přijdu!",
  "pb_frame_none": "Bez rámečku",
  "pb_frame_stamp": "Uvidíme se 2027",
  "pb_frame_stamp_text": "uvidíme se 2027",
  "pb_fx_acid": "Acid",
  "pb_fx_bw": "Černobílá",
  "pb_fx_dream": "Zasněná",
  "pb_fx_infra": "Infra",
  "pb_fx_kaleido": "Kaleidoskop",
  "pb_fx_neon": "Neon",
  "pb_fx_night": "Noční vidění",
  "pb_fx_normal": "Normální",
  "pb_fx_poster": "Plakát",
  "pb_fx_psy": "Psychedelie",
  "pb_fx_sepia": "Sépie",
  "pb_fx_vapor": "Vaporwave",
  "pb_hint_copied": "Fotka zkopírována do schránky — vlož ji do e-mailu 📋",
  "pb_hint_nocopy": "klikni na Stáhnout a přilož ji k e-mailu ⬇",
  "pb_panel_lead": "Líbí se ti? Pošli nám ji 💌",
  "pb_pick_hint": "vyber si ✨",
  "pb_strip_caption": "fotokoutek v loftu",
  "phone_dialer_title": "kontakty",
  "phone_lock_title": "Odemknout",
  "phone_notification_many": "{count} oznámení",
  "phone_notification_one": "1 oznámení",
  "phone_recents_empty": "Žádné nedávno otevřené aplikace.",
  "phone_recents_title": "Nedávné aplikace",
  "phone_signal_1": "Jste příliš daleko od Edmontonu.",
  "phone_signal_2": "Jste daleko od Edmontonu.",
  "phone_signal_3": "Trochu daleko od Edmontonu.",
  "phone_signal_4": "Dost blízko Edmontonu.",
  "photo_pose_callout_1": "Sýr! 🧀",
  "photo_pose_callout_2": "Úsměv! 📸",
  "photo_pose_callout_3": "Všichni sem! 👀",
  "piano_close": "Zavřít piano",
  "piano_coach_1": "Hraj s námi — nebo kanál pozastav",
  "piano_coach_2": "a hraj sólo.",
  "plant_overwatered": "Přelito. Kořeny plánují pomstu. 🪰",
  "portrait_action": "Zkusit na šířku",
  "portrait_body": "Nejlépe se hraje na šířku nebo na větším zařízení.",
  "portrait_title": "Otočte telefon",
  "pr_city": "Praha",
  "pr_date1": "So 10. července · 15–3 h",
  "pr_date2": "Ne 11. července · 11–15 h",
  "pr_desc1": "Zahradní slavnost: aperitiv, hudba, večeře, tanec a afterparty.",
  "pr_desc2": "Brunch na chalupě.",
  "pr_desc_half": "+ možnost přespání.",
  "prince_kill_line": "písek v přesýpacích hodinách došel.",
  "prince_kill_title": "JAFFAR VÍTĚZÍ",
  "prince_wall_label": "probudit prince",
  "py_busy": "ještě žvýkám ten předchozí…",
  "py_fail": "Python se nepodařilo načíst — offline, nebo se stahování přerušilo. zavřete a otevřete znovu.",
  "py_fonttools": "fontTools {v} je už naimportovaný — ženich trval na svém.",
  "py_loading": "přivoláváme hada… ~15 MB, jen napoprvé",
  "py_ready": "Python {v} připraven. zkuste: 2+2 · import turtle",
  "py_uharfbuzz": "uharfbuzz {v} je naimportovaný jako hb — ženichova vlastní sázecí knihovna, teď v Pythonu.",
  "py_wait": "had je pořád na cestě…",
  "py_welcome": "loftový python — opravdový CPython, přímo tady ve stránce (Pyodide/WebAssembly).",
  "quiz_again": "Vyplnit kvíz znovu",
  "quiz_continue": "Pokračovat",
  "quiz_lead": "Nejvíc jsi jako",
  "quiz_none": "Nic z toho",
  "quiz_q1": "Svatební afterparty — kde skončíš?",
  "quiz_q1a1": "Na parketu až do svítání",
  "quiz_q1a2": "V hlubokém hovoru v tichém koutě",
  "quiz_q1a3": "Za foťákem, lovím okamžiky",
  "quiz_q1a4": "U baru, míchám všem drinky",
  "quiz_q1a5": "Hlídám místnost a její lidi",
  "quiz_q2": "Vyberte části dokonalého víkendu, které vám sedí.",
  "quiz_q2a1": "Dlouhá jízda na kole nebo běh",
  "quiz_q2a2": "V klubíčku s dobrou knihou",
  "quiz_q2a3": "Malování nebo stavění něčeho",
  "quiz_q2a4": "Maraton deskových her",
  "quiz_q2a5": "Procházka venku, kde se může stát cokoliv",
  "quiz_q3": "Tvůj skrytý talent?",
  "quiz_q3a1": "V backgammonu nikdy neprohraju",
  "quiz_q3a2": "Zahraju ti melodii",
  "quiz_q3a3": "Nejlepší vlasy v místnosti",
  "quiz_q3a4": "Víc jazyků, než dokážu spočítat",
  "quiz_q3a5": "Umím situaci opravit, zorganizovat nebo zachránit",
  "quiz_q4": "Vyberte soundtracky, které byste rádi slyšeli.",
  "quiz_q4a1": "Techno až do východu slunce",
  "quiz_q4a2": "Živá kytara a piano",
  "quiz_q4a3": "Hymny pop divy",
  "quiz_q4a4": "Podcast o filozofii",
  "quiz_q4a5": "Teplá akustická píseň, kterou si všichni zazpívají",
  "quiz_q5": "Jak by tě popsali přátelé?",
  "quiz_q5a1": "Posedlý(á) drobnými detaily",
  "quiz_q5a2": "Nekonečně zvědavý(á)",
  "quiz_q5a3": "Soutěživý(á) až do morku kostí",
  "quiz_q5a4": "Kreativní duše",
  "quiz_q5a5": "Člověk, kterému se volá, když je potřeba pomoc",
  "quiz_q6": "Který popis rodiny na vás sedí? Vyberte vše, co platí.",
  "quiz_q6a1": "Nemám tu děti — jsem tu na rozhovory dospělých",
  "quiz_q6a2": "Jsem rodič jednoho zdejšího dítěte",
  "quiz_q6a3": "Jsem rodič dvou zdejších dětí",
  "quiz_q6a4": "Jsem jedno z dětí",
  "quiz_q6a5": "Jsem rodič nebo prarodič této širší rodiny",
  "quiz_q7": "Vyberte, co vám zní podobně.",
  "quiz_q7a1": "Zvědavé dítě s foťákem nebo zápisníkem",
  "quiz_q7a2": "Malý člověk, který raději běhá nebo staví",
  "quiz_q7a3": "Rodinný vypravěč",
  "quiz_q7a4": "Člověk, který místnost zútulní",
  "quiz_q7a5": "Hudebník, posluchač nebo tichý pozorovatel",
  "quiz_q8": "Co byste přinesli na oslavu?",
  "quiz_q8a1": "Absurdní slovní hříčku nebo tátův vtip",
  "quiz_q8a2": "Foťák a cit pro dobrý okamžik",
  "quiz_q8a3": "Kytaru, piano nebo přání písničky",
  "quiz_q8a4": "Plán, jak zabavit děti",
  "quiz_q8a5": "Drink, něco k zakousnutí nebo vřelé přivítání",
  "quiz_qword": "Otázka",
  "quiz_select_hint": "Vyberte vše, co sedí — nebo nic.",
  "rel_ali": "partner Goli",
  "rel_alireza": "Mahzadin partner",
  "rel_ashraf": "máma Behdada, Bahareh a Baharak",
  "rel_athena": "Hamidova partnerka",
  "rel_baharak": "Hannina máma",
  "rel_bahareh": "Irenina máma",
  "rel_baka": "babička Markéty a Madly · Danielova máma",
  "rel_behdad": "Markétin partner",
  "rel_chinnell": "Rafiho partnerka",
  "rel_danbern": "písničkář — v loftu hraje jeho vlastní živá nahrávka",
  "rel_daniel": "táta Markéty a Madly · syn Báky",
  "rel_elisabeth": "dcera Madly a Roberta",
  "rel_farhang": "Laurenin partner",
  "rel_felix": "syn Madly a Roberta",
  "rel_goli": "Aliho partnerka",
  "rel_hamid": "Athenin partner",
  "rel_hannah": "dcera Baharak a Paymana",
  "rel_irene": "dcera Bahareh",
  "rel_jay": "Spencerův partner",
  "rel_lauren": "Farhangova partnerka",
  "rel_madla": "máma Elisabeth a Felixe",
  "rel_mahzad": "Alirezova partnerka",
  "rel_marie": "máma Markéty a Madly",
  "rel_marketa": "Behdadova partnerka",
  "rel_mohsen": "táta Behdada, Bahareh a Baharak",
  "rel_oritshimoni": "písničkářka — v loftu hraje její vlastní živá nahrávka",
  "rel_patricia": "máma dvou dětí",
  "rel_patricia_daughter": "Patriciina dcera",
  "rel_patricia_son": "Patriciin syn",
  "rel_payman": "Hannin táta",
  "rel_rafi": "Chinnellin partner",
  "rel_robert": "táta Elisabeth a Felixe",
  "rel_spencer": "Jayův partner",
  "rel_whistler": "pes Farhanga a Lauren",
  "restart_confirm": "Začít v loftu znovu? Přijdeš o svůj postup.",
  "role_bartender": "barman",
  "role_bdad": "Behdadův táta",
  "role_bestman": "svědek",
  "role_bmom": "Behdadova máma",
  "role_bride": "nevěsta",
  "role_bril": "Behdadův švagr",
  "role_business": "ta podnikatelka",
  "role_danbern": "hudební spolupracovník Orit",
  "role_diva": "diva",
  "role_dj": "DJ",
  "role_fashion": "módní ikona",
  "role_godson": "Behdadův kmotřenec",
  "role_godson_a": "grilmistr",
  "role_groom": "ženich",
  "role_hosts": "hostitelé",
  "role_maid": "svědek",
  "role_mc": "moderátor",
  "role_mdad": "Markétin táta",
  "role_mgrandma": "Markétina babička",
  "role_mmom": "Markétina máma",
  "role_mnephew": "Markétin synovec",
  "role_mniece": "Markétina neteř",
  "role_msisspouse": "Markétin švagr",
  "role_msister": "Markétina sestra",
  "role_nephew": "Behdadův synovec",
  "role_niece": "Behdadova neteř",
  "role_officiant": "oddávající",
  "role_oritshimoni": "hudební spolupracovnice Dana",
  "role_photographer": "fotografka",
  "role_qa": "šéfka svatby",
  "role_sister": "Behdadova sestra",
  "role_sisterinlaw": "Behdadova švagrová",
  "role_travelbuddy_f": "parťačka na cesty",
  "role_travelbuddy_m": "parťák na cesty",
  "role_whistler": "WOOF",
  "room_balcony": "Balkon",
  "room_bar": "Bar",
  "room_bathroom": "Koupelna",
  "room_bedroom": "Ložnice",
  "room_cinema": "Kino",
  "room_cuddly": "Cuddly-puddly",
  "room_dungeon": "Kobka",
  "room_entrance": "Vstup",
  "room_garden": "Zahrada",
  "room_garden_party": "Zahrada / Párty",
  "room_kitchen": "Kuchyň",
  "room_kitchen_bar": "Kuchyň / Bar",
  "room_office": "Pracovna",
  "roster_empty": "Parket je prázdný — nejdřív rozjeď párty.",
  "roster_none": "V téhle místnosti teď nikdo není.",
  "roster_title": "kdo je tady?",
  "rsvp_email_body": "kdo jsme:\n\nna kterou oslavu (jednu, nebo obě — všichni vítáni): Edmonton · 1. května  /  Praha · 10. července\n\nkolik nás přijede:\n\ncokoliv byste měli vědět — jídlo, malé děti, píseň, kterou prostě musíme slyšet:\n\ntěšíme se,",
  "rsvp_email_subject": "přijedeme 💌",
  "rsvp_exit_link": "Viděli jste celý den — zbývá jediné: dejte nám vědět, že přijdete ↓",
  "rsvp_gmail": "Otevřít v Gmailu",
  "rsvp_mail": "E-mailová aplikace",
  "rsvp_sub": "Malé i vzdálené, přijďte na jednu akci nebo na obě — jen nám dejte vědět.",
  "rsvp_title": "RSVP",
  "rumi_lines": [
    [
      "Bez všech ostatních se obejdu; bez tebe ne.",
      "Mé srdce nese tvé znamení; jinam už nemůže."
    ],
    [
      "Mé víno a má touha; má zahrada a mé jaro.",
      "Můj spánek a můj klid; bez tebe nemohu být."
    ],
    [
      "Když nejsi mou láskou, celý můj svět se rozpadá.",
      "Má společnice a útěcha; bez tebe nemohu být."
    ],
    [
      "Jsi má duše a můj svět; k čemu mi je duše či svět?",
      "Jsi můj živoucí poklad; co je mi po zisku či ztrátě?"
    ],
    [
      "Jsi naše světlo, naše slavnost, naše vítězné štěstí.",
      "Rozbouři náš zápal, ať se naše hrozny promění ve víno."
    ],
    [
      "Přišla jsem sklonit hlavu a nést na ní tvou lásku.",
      "I kdybys řekla ne, zlomím to stéblo a odnesu si cukr."
    ],
    [
      "Krásně kráčíš mou duší, krásně mě uzdravuješ.",
      "Jsi má víra i mé vyznání, mé moře plné perel."
    ]
  ],
  "sat_call_sub": "Sobota, jako vždycky",
  "scene_ctx_escape": "Escape",
  "scene_ctx_solve": "Vyřešit",
  "season_auto": "⛅ zpátky k dnešku",
  "season_autumn": "🍂 podzim",
  "season_canada": "🍁 den Kanady",
  "season_carodejnice": "🔥 pálení čarodějnic",
  "season_chaharshanbe": "🔥 čaháršanbe surí",
  "season_holiday": "🎄 svátky",
  "season_martin": "🍷 svatý Martin · Den veteránů",
  "season_mehregan": "🌼 mehregán",
  "season_newyear": "🎆 nový rok",
  "season_nowruz": "🌱 nowruz",
  "season_pride": "🏳️‍🌈 pride",
  "season_sadeh": "🪵 sade",
  "season_sizdah": "🌳 sizdah bedar",
  "season_smoky": "🔥 kouřová sezóna",
  "season_solstice": "☀️ letní slunovrat",
  "season_spooky": "🎃 strašidelno",
  "season_spring": "🌸 jaro",
  "season_stedry": "🐟 štědrý večer",
  "season_summer": "☀ léto",
  "season_svatojanska": "🔥 svatojánská noc",
  "season_valentines": "💕 valentýn",
  "season_wedding": "💍 svatební týden",
  "season_winter": "❄ zima",
  "season_xmas": "🦃 boží hod vánoční",
  "season_yalda": "🍉 šab-e jalda",
  "share_bd_a": "Všechno nejlepší — ",
  "share_bd_b": "!",
  "share_copied": "✓ Zkopírováno do schránky — vložte kamkoli",
  "share_copyfail": "Stáhněte nebo pošlete e-mailem níže",
  "share_download": "⬇ Stáhnout",
  "share_greet_canada": "Šťastný den Kanady!",
  "share_greet_carodejnice": "Veselé pálení čarodějnic!",
  "share_greet_chaharshanbe": "Šťastné Čaháršanbe Súrí!",
  "share_greet_holiday": "Veselé svátky!",
  "share_greet_martin": "Svatý Martin — mladé víno je otevřené",
  "share_greet_mehregan": "Šťastný Mehregán!",
  "share_greet_newyear": "Šťastný nový rok!",
  "share_greet_nowruz": "Šťastný Nourúz!",
  "share_greet_pride": "Šťastný Pride!",
  "share_greet_sadeh": "Krásné Sadeh — oheň uprostřed zimy",
  "share_greet_solstice": "Pořád je světlo. Zůstaň vzhůru s námi.",
  "share_greet_spooky": "Veselý Halloween!",
  "share_greet_stedry": "Šťastný Štědrý den!",
  "share_greet_svatojanska": "Přijď s námi přeskočit oheň. Drž se pevně.",
  "share_greet_valentines": "Krásného Valentýna!",
  "share_greet_wedding": "Uložte si datum!",
  "share_greet_xmas": "Veselé Vánoce!",
  "share_greet_yalda": "Krásnou Jaldu — nejdelší noc v roce",
  "share_mail": "✉ E-mail",
  "share_mail_bd_body": "Ať má {name} krásný den — a k tomu malé pozvání z našeho loftu. Kartu otevřete zde:",
  "share_mail_bd_subj": "Všechno nejlepší — {name}! 🎉",
  "share_mail_body": "Pozdrav z našeho loftu — přijďte se podívat na dnešní kartu s datem:",
  "share_mail_clip": "(Obrázek karty máte ve schránce — vložte jej do e-mailu jako přílohu.)",
  "share_mail_subj": "Malý pozdrav od markéty & behdada",
  "share_mail_wed_body": "Budeme se brát! Přijďte se podívat na naši kartu s datem v loftu:",
  "share_mail_wed_subj": "Uložte si datum — markéta & behdad",
  "share_title": "Uložte si datum — sdílejte loft",
  "shoot_doom": "Doom",
  "shoot_duke": "Duke",
  "shoot_mouse_coach": "Esc uvolní myš",
  "shoot_q3": "Quake III",
  "sizdah_wish": "Zauzlovat <em>sabzeh</em> znamená přát si svatbu. Zabralo to.",
  "snake_setup_cancel": "Zrušit",
  "snake_setup_fast": "rychle",
  "snake_setup_players": "Počet hráčů",
  "snake_setup_slow": "pomalu",
  "snake_setup_speed": "Rychlost hry",
  "snake_setup_start": "Spustit hru",
  "solitaire_help": "Nápověda",
  "solitaire_help_copy": "Skládejte sestupně a střídejte barvy. Esa až krále stejné barvy posílejte domů. Klepněte nebo táhněte; dvojím klepnutím pošlete kartu domů.",
  "solitaire_new": "Nová",
  "solitaire_play_again": "Rozdat znovu",
  "solitaire_ranks": [
    "eso",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "spodek",
    "dáma",
    "král"
  ],
  "solitaire_redeal": "Znovu rozdat",
  "solitaire_suits": [
    "srdce",
    "kára",
    "kříže",
    "piky"
  ],
  "solitaire_win": "Vyhráli jste. Trpělivost se vyplatila.",
  "tab_behdad": "behdad",
  "tab_ctx_close": "Zavřít",
  "tab_ctx_reload": "Načíst znovu",
  "tab_harfbuzz": "harfbuzz",
  "tab_loft": "m ∞ b",
  "tab_marketa": "markéta",
  "tab_new": "nová karta",
  "tagline": "Budeme se brát<br><strong>Budete tam?</strong>",
  "tehran_place": "Teherán",
  "tempnav_down": "Chladněji",
  "tempnav_reset": "Vrátit skutečnou teplotu v Edmontonu",
  "tempnav_up": "Tepleji",
  "tetris_again_key": "ENTER",
  "tetris_controls": "KLIK OTOČ · TÁHNI POSUŇ/SHOĎ",
  "tetris_lines": "ŘADY",
  "tetris_next": "DALŠÍ",
  "tetris_title": "BLOCK PARTY",
  "tetris_touch_again_key": "KLEPNI",
  "tetris_touch_controls": "KLEPNI OTOČ · TÁHNI POSUŇ/SHOĎ",
  "tip_abstract_butterfly": "Abstraktní 🌈🦋",
  "tip_behdad_pc": "behdadův počítač s otevřenou konstrukcí",
  "tip_carodejnice": "<em>Čarodějnice</em>, <em>filipojakubská noc</em>",
  "tip_chaharshanbe": "<em>Čaháršanbe surí</em> (<bdi>چهارشنبه‌سوری</bdi>), oheň, který se přeskakuje",
  "tip_cokecooler": "pojízdný chladicí box <em>Coca-Cola</em> ve vintage stylu — fakt jejich, fakt jezdí",
  "tip_fal": "<em>Díván</em> <em>Háfizův</em> (<bdi>دیوان حافظ</bdi>) — otevři jej pro <em>fál</em>",
  "tip_haftsin": "<em>haft-sín</em> (<bdi>هفت‌سین</bdi>), <em>nourúzský</em> (<bdi>نوروز</bdi>) stůl",
  "tip_immortality": "Nesmrtelnost",
  "tip_marketa_laptop": "Markétin notebook",
  "tip_marketa_phone": "Markétin telefon",
  "tip_meal_martin": "<em>svatý Martin</em> — husa, červené zelí, <em>karlovarský knedlík</em> a letošní <em>svatomartinské víno</em>",
  "tip_meal_nowruz": "<em>sabzi polo ba mahi</em> (<bdi>سبزی‌پلو با ماهی</bdi>), bylinková rýže s rybou na nový rok",
  "tip_meal_stedry": "<em>Štědrý večer</em> — smažený kapr a bramborový salát",
  "tip_meal_xmas": "Vánoční oběd — pečený krocan a brusinky, ani jedna ryba",
  "tip_meal_yalda": "<em>Šab-e jalda</em> (<bdi>شب یلدا</bdi>) — meloun, granátové jablko a <em>ajil</em> na nejdelší noc",
  "tip_mehregan": "<em>Mehregán</em> (<bdi>مهرگان</bdi>), podzimní <em>sofre</em> — měsíčky, <em>sendžed</em>, granátové jablko a růžová voda na fialovém ubruse",
  "tip_mehregan_esfand": "<em>esfand</em> (<bdi>اسفند</bdi>) na uhlících",
  "tip_mehregan_mirror": "zrcadlo a vedle něj <em>sormedán</em> (<bdi>سرمه‌دان</bdi>)",
  "tip_mehregan_noghl": "<em>noghl</em> (<bdi>نقل</bdi>) — cukrované mandle, hází se po hrstech",
  "tip_mondrian_butterfly": "Mondrian 🌈🦋",
  "tip_neon_butterfly": "Neon 🌈🦋",
  "tip_sadeh": "<em>Sade</em> (<bdi>سده</bdi>), zimní oheň padesát dní a nocí před <em>nourúzem</em> — postav, přilož, posaď se",
  "tip_sadeh_flint": "udeř kamenem o kámen",
  "tip_sadeh_wood": "chrastí, nasbírané na tuhle noc",
  "tip_sizdah": "<em>Sizdah Bedar</em> (<bdi>سیزده‌بدر</bdi>), třináctý den <em>nourúzu</em>, strávený v přírodě",
  "tip_smores": "opékání marshmallows u ohně",
  "tip_stainedglass_butterfly": "Vitráž 🌈🦋",
  "tip_sundogs": "<em>parhelium</em>, vedlejší slunce — jasné skvrny 22° od nízkého zimního slunce, vytvořené ledovými krystalky. V prériích pod −20 °C",
  "tip_svatojanska": "<em>Svatojánská noc</em> — oheň, který se přeskakuje za ruce",
  "trip_caption_acid": "Čas vyrazit na projížďku na kole.",
  "trip_caption_dmt": "Já osobně strojové elfy vítám.",
  "trip_caption_froggies": "Bod tání reality zaznamenán.",
  "trip_caption_iboga": "Někde za tebou se minulost pořád načítá.",
  "trip_caption_ketamine": "Je to jen hra ve hře, ve hře, ...",
  "trip_caption_molly": "Najednou je každý tvůj nejoblíbenější člověk.",
  "trip_caption_nitrous": "Počkej, ta myšlenka odplouvá.",
  "trip_caption_shrooms": "Houbová říše vítězí.",
  "trip_no_mix_text": "Prosím nemíchat. Užívejte s mírou. 🙃",
  "tt_by": "od",
  "tt_design_ayushi": "Paisley",
  "tt_design_bored": "Nuda",
  "tt_design_butterfly": "Motýl",
  "tt_design_dinosaur": "Dinosaurus",
  "tt_design_elephant": "Slon",
  "tt_design_giraffe": "Žirafa",
  "tt_design_princesses": "Princezny",
  "tt_design_pufferfish": "Čtverzubec",
  "tt_email_body": "Ahoj Markéto a Behdade!\n\nTady je návrh tetování z vašeho loftového studia — teď ho sem vlož, máš ho ve schránce (Ctrl/Cmd+V).\n\nUvidíme se na svatbě!",
  "tt_email_subject": "Návrh tetování 🖊️",
  "tt_new": "Nakresli si vlastní",
  "tt_share": "Pošli nám to",
  "typewriter_lines": [
    "Sliby: první verze. Smazáno.",
    "Poznámka: méně vtipů ve slibech.",
    "Pořád rychlejší než řešení merge konfliktů.",
    "Milý deníčku, v podkroví to zase voní kávou.",
    "Tenhle font pořád nemá ligatury."
  ],
  "typewriter_patience_line": "Pořád tu jsi? To je celý slib, popravdě.",
  "video_absent": "film ještě není nahraný — vraťte se brzy",
  "video_butterfly": "Rainbow Butterfly",
  "video_downtown": "Downtown dance",
  "video_rose": "Mon amie la rose",
  "watch_loft": "▷ Upoutávka",
  "watch_skip": "□ Převzít",
  "wd_anniversary": "výročí",
  "wd_ribbon": "novomanželé",
  "wd_wedding_day": "Svatební den"
};
