window.__loftMessages["en"] = {
  "age_forms": [
    "{n} years old now!",
    "{n} years old already!",
    "{n} now!",
    "already {n}! 🎂"
  ],
  "album_btn_copy": "📋 Copy",
  "album_cap_and": "&",
  "album_cap_dressup": "our dressed-up couple",
  "album_cap_group": "the group photo · everyone 🎉",
  "album_cap_selfie": "photobooth selfie",
  "album_cap_with": "with",
  "album_empty_sub": "Aspen hasn't captured one yet — wander around and she'll fill your roll.",
  "album_empty_title": "no photos yet",
  "album_recap_back": "Back to the full album",
  "album_recap_group": "everyone together",
  "album_recap_open": "View party recap",
  "album_recap_portraits": "portraits",
  "album_recap_rooms": "around the loft",
  "album_recap_selfies": "our selfies",
  "album_recap_sub": "A contact sheet from this party.",
  "album_recap_title": "tonight at the loft",
  "album_room_balcony": "the balcony",
  "album_room_cuddly": "the cuddly-puddly",
  "album_room_garden": "the garden/party",
  "album_room_kitchen": "the bar",
  "album_room_office": "the office",
  "album_search_none": "no photos with anyone by that name.",
  "album_search_ph": "search photos…",
  "app_album": "album",
  "app_browser": "browser",
  "app_calculator": "calculator",
  "app_calendar": "calendar",
  "app_call": "call",
  "app_cards": "phrasebook",
  "app_chat": "chat",
  "app_chrome": "chrome",
  "app_classics": "classics",
  "app_clock": "clock",
  "app_cocktails": "cocktails",
  "app_code": "code",
  "app_console": "console",
  "app_currency": "currency",
  "app_dressup": "dress-up",
  "app_firefox": "firefox",
  "app_flashlight": "flashlight",
  "app_hn": "news",
  "app_life": "life",
  "app_linux": "linux",
  "app_mail": "mail",
  "app_messages": "messages",
  "app_mines": "mines",
  "app_music": "music",
  "app_notes": "notes",
  "app_pacman": "hackman",
  "app_photobooth": "photobooth",
  "app_prince": "prince",
  "app_python": "python",
  "app_quiz": "quiz",
  "app_shoot": "shoot",
  "app_snake": "snake",
  "app_tattoo": "tattoo",
  "app_video": "video",
  "app_weather": "weather",
  "arcade_offer_flair": "New best! Flair Catch is serving the next round. 🍸",
  "arcade_offer_invaders": "New best! Alien Resources has an opening. 👾",
  "arcade_offer_pacman": "New best! Hack-Man has entered the chat. ᗧ",
  "arcade_offer_tetris": "New best! Block Party is lighting up. 🧱",
  "balcony_audience_callout": "Smile — we have an audience! 👀",
  "balcony_marketa_groceries": "Groceries are always on her.",
  "bd_msg_a": "Happy birthday, {name}! 🎂",
  "bd_msg_b": "it's {name}'s birthday!! 🥳",
  "bd_msg_c": "big day for {name} today 🎂🎈",
  "bd_msg_d": "Happy birthday {name}! 🎉🎈",
  "bd_toast_a": "🎂 ",
  "bd_toast_b": "’s birthday",
  "bedroom_glass_draw": "Draw — click any pane to clear the board",
  "bedroom_glass_loss": "The window won — click any pane to clear the board",
  "bedroom_glass_win": "You won — click any pane to clear the board",
  "bedroom_ttt_start_caption": "Click any pane to play tic-tac-toe",
  "box_trip_pick_title": "vitamins",
  "boxlock_ctx_unlock": "Unlock",
  "boxlock_fail_click": "Click on the date above.",
  "boxlock_fail_date": "It’s one of our wedding dates, try again.",
  "boxlock_fail_jul": "July 10, 2027 — Prague.",
  "boxlock_fail_may": "May 1, 2027 — Edmonton.",
  "boxlock_submit": "UNLOCK",
  "browser_deeper": "we need to go deeper…",
  "browser_loading": "loading…",
  "browser_noframe": "if it stays blank, that site refuses to live in a picture frame — most big ones do",
  "browser_omni_ph": "Search or enter address",
  "butterfly_broken_caption": "This is why we can’t have nice wings.",
  "butterfly_chase_progress": "Butterfly chase: {score}/10 · {seconds}s",
  "butterfly_chase_timeout": "The butterflies got away. 🦋",
  "butterfly_chase_tip": "Click any butterfly to start a chase. 🦋",
  "butterfly_chase_win": "Butterflies caught. Nobody was harmed. 🦋",
  "cal_bbq": "🍖 bbq day",
  "cal_bicycle_day": "Bicycle Day (LSD)",
  "cal_bipolar_day": "🧲 World Bipolar Day",
  "cal_brunch": "🍳 garden brunch",
  "cal_dl_e": "Download the Edmonton dates (.ics)",
  "cal_dl_p": "Download the Prague dates (.ics)",
  "cal_download": "Download .ics",
  "cal_e_d1": "May 1 · 16:00–04:00",
  "cal_e_d1_what": "wedding & party",
  "cal_e_d2": "May 2 · 16:00–22:00",
  "cal_e_d2_what": "bbq at the loft",
  "cal_edmonton": "Edmonton",
  "cal_gcal": "GCal",
  "cal_ics_e1": "markéta ∞ behdad — Edmonton wedding",
  "cal_ics_e2": "markéta ∞ behdad — Edmonton loft BBQ",
  "cal_ics_p1": "markéta ∞ behdad — Prague garden party",
  "cal_ics_p2": "markéta ∞ behdad — Prague garden brunch",
  "cal_lubeck": "Lübeck",
  "cal_marijuana_day": "420 (Marijuana)",
  "cal_mushroom_day": "International Mushroom Day",
  "cal_p_d1": "July 10 · 15:00–03:00",
  "cal_p_d1_what": "garden party",
  "cal_p_d2": "July 11 · 11:00–15:00",
  "cal_p_d2_what": "garden brunch",
  "cal_polyamory_day": "World Polyamory Day",
  "cal_prague": "Prague",
  "cal_search_meteor": "meteor shower",
  "cal_search_none": "no events match that search.",
  "cal_search_placeholder": "search events…",
  "cal_tehran": "Tehran",
  "calc_backspace": "Backspace",
  "calc_error": "Error",
  "california_place": "California",
  "call_incoming": "Incoming video call…",
  "can_streak_text": "Nice toss streak! 🥫",
  "cards_hint": "tap the card to flip",
  "cdb_conn": "to",
  "cdb_edmonton": "Edmonton",
  "cdb_edmonton_to": "Edmonton",
  "cdb_prague": "Prague",
  "cdb_prague_to": "Prague",
  "cdb_today": "{city} today!",
  "cdb_tomorrow": "{city} tomorrow!",
  "cdb_week_1": "week",
  "cdb_week_m": "weeks",
  "cdb_week_n": "weeks",
  "chat_action_failed": "I couldn’t do that right now. Try again.",
  "chat_error": "Something went wrong. Try again.",
  "chat_placeholder": "Ask about the loft…",
  "chat_retry": "Retry",
  "chat_thinking": "Thinking…",
  "chat_unavailable": "Chat isn’t connected yet.",
  "chat_welcome": "Hi! I’m Charlie, your wedding assistant. I know this loft and how it works. Ask me anything.",
  "cheers_text": "Cheers! 🥂",
  "cinema_short_gag": "The projector survived. The warranty did not.",
  "cinema_title": "What are we watching?",
  "ck_featured": "featured",
  "ck_gallery": "the bar",
  "ck_ingredients": "ingredients",
  "ck_order": "🍸 Order",
  "ck_signature": "our own signature",
  "ck_steps": "steps",
  "classics_back": "‹ games",
  "classics_choose": "Choose a classic",
  "classics_mines": "Mines",
  "classics_mines_sub": "don’t set off the ring",
  "classics_solitaire": "Solitaire",
  "classics_solitaire_sub": "a little patience",
  "clk_jump_label": "Jump to time",
  "clk_playtime": "You’ve been in the loft for",
  "code_email_intro": "Hi Markéta & Behdad!\n\nLook what I built in the loft — run it in the office computer's Code app:",
  "code_email_subject": "Look what I built!",
  "code_reset_file": "Reset “{filename}”…",
  "code_reset_file_confirm": "Reset “{filename}”? Only your local edit to this file will be lost.",
  "code_reset_files": "Reset files…",
  "code_reset_files_confirm": "Reset all Code files and edits? This cannot be undone.",
  "contact": "Questions? Write to us:",
  "credits_codesigner": "co-designer",
  "credits_codesigner_translator": "co-designer | Czech translator",
  "credits_killed": "CREDITS KILLED",
  "credits_licenses": "Licence notices are included with the software.",
  "credits_made": "made with love by behdad, Claude & Codex",
  "credits_open_source": "Open-source software",
  "credits_qa": "QA lead",
  "credits_survives": "the gratitude survives.",
  "credits_tester": "tester",
  "credits_testers": "Testers",
  "credits_thanks": "with thanks",
  "credits_title": "Credits",
  "cue_calendar_body": "put us in your calendar 📅 may 1 · july 10",
  "cue_cocktails_body": "the full menu's on your phone if you're deciding 🍸",
  "cue_mail_body": "did you check the mail? 💌 there's a letter for you",
  "cur_offline": "· offline rate",
  "datenav_reset": "Reset date to today",
  "datenav_reset_time": "Reset the clock to now",
  "desk_date": "May 1",
  "desk_search_apps": "search apps…",
  "desk_to": "to",
  "df_bsod_main": "Your PC ran into a problem and needs to restart.",
  "dial_call": "Call",
  "dial_fam_california": "patty & the kids",
  "dial_fam_lueb": "madla &amp; family",
  "dial_fam_prague": "markéta’s parents",
  "dial_fam_tehran": "behdad’s family",
  "dial_pick_title": "who are we calling?",
  "dj_pick_title": "request a song",
  "dollhouse_locked": "?",
  "dollhouse_progress": "{count} of 10 rooms visited",
  "dollhouse_roadtrip_unlocked": "Road Trip unlocked",
  "dollhouse_title": "The Loft 🗺️",
  "du_bouquet": "bouquet",
  "du_copy": "Copy",
  "du_download": "Download",
  "du_earrings": "earrings",
  "du_flowercrown": "flower crown",
  "du_monocle": "monocle",
  "du_mustache": "moustache",
  "du_necktie": "necktie",
  "du_partyhats": "party hats",
  "du_save": "Save",
  "du_shades": "shades",
  "du_tophats": "top hats",
  "du_veil": "veil",
  "ed_city": "Edmonton",
  "ed_date1": "Sat, May 1 · 4pm–4am",
  "ed_date2": "Sun, May 2 · 4pm–10pm",
  "ed_desc1": "Ceremony & dinner at <a href=\"https://www.atriumatsabor.ca/\" target=\"_blank\" rel=\"noopener\">Atrium by Sabor ↗</a>, followed by concert, dancing & afterparty at <a href=\"https://www.99ten.ca/\" target=\"_blank\" rel=\"noopener\">9910 ↗</a>.",
  "ed_desc2": "BBQ at the loft.",
  "entrance_intercom_reply": "“Alo?”",
  "entrance_windows_all_off": "The whole building has gone to bed.",
  "entrance_windows_all_on": "Every window is awake. Nobody told the power bill.",
  "entrance_windows_uv": "The building is trying to sleep. You're the reason it can't.",
  "eq_off_note": "This browser plays the songs directly — there's no audio pipeline for the equalizer to pull on. Try it on another device 🎚",
  "extinguisher_reset": "You would. You did. Game reset.",
  "extinguisher_warning": "I wouldn't.",
  "fal_intro": "You open the Divan at random. Hafez answers:",
  "fal_lines": [
    "Lost Joseph will come back to Canaan — do not grieve.<br>This house of sorrows will be a rose garden — do not grieve.",
    "Come, cupbearer, pass the cup and offer it round —<br>for love looked easy at first, and then the hard part came.",
    "Plant the tree of friendship — it bears the heart’s desire.<br>Tear out the sapling of enmity — it bears grief past counting."
  ],
  "fern_found": "The fern flower. You were standing here at midnight on the one night it opens. That's the whole trick, and it's supposed to be luck.",
  "fern_legend": "Fern. They say it flowers one midnight a year — tonight, if you believe the story — and whoever finds the flower comes into luck.",
  "flight_note": "Edmonton → Prague — about 10 weeks (and one ocean) apart.",
  "fun_ali": "competitive cyclist",
  "fun_alireza": "long-distance runner",
  "fun_ashraf": "also loves backgammon",
  "fun_aspen": "best wedding photographer",
  "fun_athena": "<em>Zebel-khan</em>",
  "fun_ayushi": "Stand-up comedian in practice.",
  "fun_baharak": "the younger sister, 'nough said",
  "fun_bahareh": "insane attention to detail",
  "fun_baka": "likes watching sports",
  "fun_behdad": "Claude & Codex's best friend.",
  "fun_chinnell": "no plans to grow up",
  "fun_danbern": "Irene grew up on his children’s albums",
  "fun_danesh": "best hair",
  "fun_daniel": "repairs churches",
  "fun_elisabeth": "climbs and paints",
  "fun_farhang": "triathlete",
  "fun_felix": "likes sports",
  "fun_goli": "Lady Gaga double",
  "fun_hamid": "Behdad's <em>adopted son</em>",
  "fun_hannah": "gymnast. learning piano.",
  "fun_irene": "learning Python already",
  "fun_jay": "the philosopher / jesus",
  "fun_lauren": "Farhang's boss",
  "fun_madla": "plays the guitar",
  "fun_mahzad": "architect & painter",
  "fun_marie": "engineer & psychologist",
  "fun_marketa": "sports, reading, writing, languages, music — you name it",
  "fun_mohsen": "loves backgammon!",
  "fun_navid": "Greek mythology expert",
  "fun_oritshimoni": "travelling musician",
  "fun_patricia": "fluffy hair",
  "fun_patricia_daughter": "mesmerizing eyes",
  "fun_patricia_son": "loves the <em>Lada</em>",
  "fun_payman": "avid reader",
  "fun_pouria": "collects hobbies",
  "fun_rafi": "great storyteller",
  "fun_robert": "plays the piano",
  "fun_robin": "Dinosaur expert",
  "fun_sina": "best techno",
  "fun_spencer": "speaks Korean",
  "fun_whistler": "She swims 1km nonstop",
  "game_alien_title": "ALIEN RESOURCES",
  "game_best": "BEST",
  "game_cleared": "CLEARED!",
  "game_flair_title": "FLAIR CATCH",
  "game_new": "NEW GAME",
  "game_over": "GAME OVER",
  "game_paused": "PAUSED",
  "game_play_again": "PLAY AGAIN",
  "game_ready": "READY!",
  "game_score": "SCORE",
  "genie_wish_love": "Love",
  "genie_wish_love_reply": "Already granted.",
  "genie_wish_money": "Money",
  "genie_wish_money_reply": "Approved for one brief shower.",
  "genie_wish_more": "More wishes",
  "genie_wish_more_reply": "Nice try.",
  "genie_wish_title": "Make a wish.",
  "gm_toast_ali_1": "To the two of you —",
  "gm_toast_ali_2": "may it always be a party. 🥂",
  "gm_toast_farhang_1": "One wedding wasn't enough,",
  "gm_toast_farhang_2": "so — twice to love! 💞",
  "hn_by": "by",
  "hn_comments": "comments",
  "hn_comments_error": "comments couldn’t be loaded.",
  "hn_comments_heading": "Comments",
  "hn_comments_loading": "loading comments…",
  "hn_comments_partial": "Some comments couldn’t be loaded.",
  "hn_error": "couldn’t reach Hacker News — check your connection.",
  "hn_external_intro": "This story lives on {source}. Open the original in a browser tab; the Hacker News discussion is below.",
  "hn_loading": "loading top stories…",
  "hn_no_comments": "no comments yet.",
  "hn_open_hn": "Open on Hacker News",
  "hn_open_original": "Open original",
  "hn_points": "points",
  "hn_source": "source",
  "hn_story": "Story",
  "hn_top_stories": "Top stories",
  "hp_nudge": "🎧 pop these on — the party's best on cans",
  "hunt": {
    "act_b0": "The day's done — but the sky isn't. Tap the sun, watch it go. 🌇",
    "act_b2": "Bed time. Lights out, switch by the door.",
    "act_b2_redirect": "Not the lamp — the little switch by the door. 👉",
    "act_b3": "…that was never the light switch. 🎉 Surprise — the loft doesn't do quiet nights.",
    "act_p1": "<em>Pouria</em>'s back behind the bar — go get the drink you skipped this morning. 🍸",
    "act_p2": "<em>DJ Sina</em> and <em>DJ Danesh</em> are trading the decks. The garden's dancing — stay for the next one. 💃",
    "act_p3": "Take an album strip — use the booth on your phone<span class=\"kbd-hint\">, just press <kbd>c</kbd></span>, or the one on the PC. 📷",
    "arcade_hint": "Move the chair or use ← → to aim; Space fires. 👾",
    "balcony": "There will be BBQ 🔥🍖🌽🍷",
    "bathroom_bubbles_done": "Bubble-gun · time!",
    "bathroom_bubbles_start": "Bubble-gun · 20 seconds. Click or drag the stool to fire.",
    "bathroom_mirror_doodle": "Bathroom · your turn in the remaining steam.",
    "bathroom_mirror_reveal": "Bathroom · m∞b, drawn through the steam.",
    "bedroom_ttt_turn_caption": "Your turn · the window is calling",
    "bedroom_ttt_wait_caption": "The window’s turn · it has a plan",
    "cine_anywhere": "Play wherever you wander.",
    "cine_arcade": "Play something that shoots back.",
    "cine_below": "Open a door. Wander downstairs.",
    "cine_camp": "Stay until the stars come out.",
    "cine_chapter_camp": "Stay for the night",
    "cine_chapter_jump": "Try something unexpected",
    "cine_chapter_open": "Open another door",
    "cine_chapter_party": "Let the room fill up",
    "cine_chapter_road": "Take the road west",
    "cine_chapter_round": "Try another round",
    "cine_chapter_soft": "Discover the soft side",
    "cine_chapter_unlock": "Follow the clues",
    "cine_chapter_wander": "Wander anywhere",
    "cine_clues": "Follow the clues. Open another room.",
    "cine_final_detail": "Games, detours, and one road west",
    "cine_final_kicker": "Follow the clues · Explore every room",
    "cine_final_note": "The rest is yours.",
    "cine_final_title": "See where the loft takes you",
    "cine_more": "There is always one more thing to try.",
    "cine_open": "Try the loft out of order.",
    "cine_party": "Sometimes the room fills itself.",
    "cine_phone": "Open a pocket-sized distraction.",
    "cine_road": "Take the long way west.",
    "cine_round": "Try one more round.",
    "cine_signoff": "Take over. Discover the rest.",
    "cine_soft": "Discover the soft side.",
    "cine_title": "Explore the Loft",
    "cine_title_kicker": "Come play for a little while",
    "cine_title_sub": "Try · open · wander · discover",
    "clickme": "CLICK ME!",
    "complete": "You’ve seen the whole loft ♥",
    "cuddly": "Play with Octi, open the balcony door, pull back a blanket.",
    "cuddly_door": "Now open the balcony door.",
    "cuddly_hint": "Play with Octi first.",
    "cuddly_outlet_visit": "Someone dropped by the cuddly-puddly. 👋",
    "cuddly_pull": "Now pull back any blanket.",
    "df_about_quip": "Have you tried turning reality off and on again?",
    "df_browser_quip": "Aw, Snap! The tab gave up.",
    "df_calendar_quip": "Your days are numbered.",
    "df_call_lost": "CONNECTION LOST",
    "df_call_quip": "It’s not you. It’s the connection.",
    "df_chat_quip": "Charlie has left the chat.",
    "df_classics_quip": "Pick a card. Any card.",
    "df_clock_quip": "Time’s up.",
    "df_code_quip": "Back to BASICs.",
    "df_console_quip": "undefined is not a function.",
    "df_doom_quip": "kill -9 — flawless victory.",
    "df_help_quip1": "You’ve been freed. You’re on your own.",
    "df_help_quip2": "Do you have a clue what happens now?",
    "df_life_quip": "The point of life is the playing.",
    "df_linux_q1": "First they ignore you…",
    "df_linux_q2": "…then you win.",
    "df_mail_quip": "You’ve got no mail.",
    "df_mines_quip": "You found them.",
    "df_music_quip": "The rest is silence.",
    "df_pacman_quip": "Game over. Insert another ghost.",
    "df_photobooth_quip": "Nobody blinked.",
    "df_python_quip1": "'Tis but a scratch!",
    "df_python_quip2": "It's just a flesh wound!",
    "df_snake_quip": "GAME OVER · It ate the process.",
    "df_solitaire_quip": "Patience ran out.",
    "df_system_quip": "System killed. The bugs survived.",
    "df_tattoo_quip": "No regrets.",
    "df_video_butterfly_quip": "The colour ran. The butterfly stayed.",
    "df_video_chooser_quip": "He shot every film. The camera shot back.",
    "df_video_quip": "Dance like the whole world is watching.",
    "df_video_rose_quip": "The rose falls. The song stays.",
    "df_weather_quip": "Under the weather.",
    "dj_danesh": [
      "<em>DJ Danesh</em> takes over the decks. 🎧",
      "<em>DJ Danesh</em> steps up to spin. 🎧"
    ],
    "dj_sina": [
      "<em>DJ Sina</em> takes over the decks. 🎧",
      "<em>DJ Sina</em> grabs the ones and twos. 🎧"
    ],
    "entrance_drive_auto": "Automatic · steer, accelerate and brake.",
    "entrance_drive_auto_desktop": "Automatic · ↑ accelerates · ↓ brakes · Space holds speed.",
    "entrance_drive_auto_drive_interlock": "Slow below 10 km/h before selecting Drive.",
    "entrance_drive_auto_neutral_hint": "Automatic is in N · select D to drive.",
    "entrance_drive_auto_park_hint": "Automatic is in P · select D to drive.",
    "entrance_drive_auto_park_interlock": "Stop before selecting Park.",
    "entrance_drive_auto_reverse_interlock": "Slow below 10 km/h before selecting reverse.",
    "entrance_drive_close": "Close dashboard",
    "entrance_drive_coach_auto_gear_desktop": "Shift + ↑ / ↓, or drag or click the shifter into D",
    "entrance_drive_coach_auto_gear_title": "Select Drive",
    "entrance_drive_coach_auto_gear_touch": "Drag the shifter down from P to D",
    "entrance_drive_coach_auto_pedals_desktop": "↑ accelerates · ↓ brakes",
    "entrance_drive_coach_auto_pedals_touch": "Blue steers · pink accelerates/brakes · centre holds speed",
    "entrance_drive_coach_cruise_text": "Press Space to hold speed.",
    "entrance_drive_coach_cruise_title": "Auto-cruise",
    "entrance_drive_coach_gear_desktop": "Shift + ↑ / ↓ changes gear",
    "entrance_drive_coach_gear_title": "Change gear",
    "entrance_drive_coach_gear_touch": "Long-press the shifter, then drag to choose",
    "entrance_drive_coach_ignition_text": "Press Enter or click the ignition key to start.",
    "entrance_drive_coach_ignition_title": "Start the car",
    "entrance_drive_coach_pedals_desktop": "↑ accelerates · ↓ brakes",
    "entrance_drive_coach_pedals_title": "Now drive",
    "entrance_drive_coach_pedals_touch": "Blue steers · pink accelerates/brakes · centre holds speed",
    "entrance_drive_coach_steer_desktop": "Use ← → to steer",
    "entrance_drive_coach_steer_title": "Steer",
    "entrance_drive_coach_steer_touch": "Slide the blue control or drag the wheel",
    "entrance_drive_cruise_active": "Cruising at {speed} km/h · Space resets held speed · brake cancels.",
    "entrance_drive_ignition_hint": "Start the ignition. The key is on the left.",
    "entrance_drive_manual": "Let’s drive manual.",
    "entrance_drive_manual_desktop": "Manual · ↑ accelerates · ↓ brakes · Space holds speed.",
    "entrance_drive_mode_auto": "Automatic transmission.",
    "entrance_drive_mode_manual": "Manual transmission.",
    "entrance_drive_neutral_hint": "Let’s drive manual · put it in gear.",
    "entrance_drive_rev_shift_auto": "Shift into D to drive.",
    "entrance_drive_rev_shift_manual": "Shift into 1st to drive.",
    "entrance_drive_roadtrip_button_hint": "Click Road Trip above to hit the road.",
    "entrance_drive_shift_down": "Shift ↓ · give the engine some leverage.",
    "entrance_drive_shift_up": "Shift ↑ · it wants another gear.",
    "entrance_drive_stalled": "You killed it. Restart the engine.",
    "entrance_drive_status_auto": "Automatic, {gear}",
    "entrance_drive_status_manual": "Manual, {gear}",
    "entrance_drive_touch_accel": "GAS",
    "entrance_drive_touch_brake": "BRAKE",
    "entrance_roadtrip_abraham_arrival": "Let’s camp for the night.",
    "entrance_roadtrip_abraham_exit": "Abraham Lake turnoff ahead · turn right.",
    "entrance_roadtrip_arrest_centerline_line": "double solid · fine {fine} · {points} pts · {total}/15",
    "entrance_roadtrip_arrest_centerline_title": "SOLID-LINE TICKET",
    "entrance_roadtrip_arrest_impaired_line": "{fine} · {points} pts · {total}/15",
    "entrance_roadtrip_arrest_impaired_title": "IMPAIRED DRIVING",
    "entrance_roadtrip_arrest_kicker": "TRAFFIC STOP",
    "entrance_roadtrip_arrest_line": "{over} over · {fine} · {points} pts · {total}/15",
    "entrance_roadtrip_arrest_shout_engine": "ENGINE OFF!",
    "entrance_roadtrip_arrest_shout_hands": "HANDS THROUGH THE WHEEL!",
    "entrance_roadtrip_arrest_shout_keys": "DROP THE KEYS!",
    "entrance_roadtrip_arrest_ticket_line": "{over} over · fine {fine} · {points} pts · {total}/15",
    "entrance_roadtrip_arrest_ticket_title": "SPEEDING TICKET",
    "entrance_roadtrip_arrest_title": "COURT SUMMONS",
    "entrance_roadtrip_banff_arrival": "Banff road · mountains, curves, limit 90.",
    "entrance_roadtrip_banff_exit": "Banff exit ahead · the road turns right.",
    "entrance_roadtrip_camp_arrival": "Congrats! You reached the end of the game. <span class=\"camp-rsvp-cta\">Now go do your RSVP!</span>",
    "entrance_roadtrip_camp_attended_time": "Wow, what a lofly day! {time} in loft. <span class=\"camp-rsvp-cta\">Tell us your time in your RSVP.</span>",
    "entrance_roadtrip_camp_behdad_aria": "Make Behdad laugh",
    "entrance_roadtrip_camp_finale": "Wow, what a lofly day! <span class=\"camp-rsvp-cta\">Now go do your RSVP!</span>",
    "entrance_roadtrip_camp_fire_close": "Close fire building",
    "entrance_roadtrip_camp_fire_igniting": "The fire is catching…",
    "entrance_roadtrip_camp_fire_invite": "What a beautiful campsite! Let’s build a fire.",
    "entrance_roadtrip_camp_fire_light": "Light",
    "entrance_roadtrip_camp_fire_no_logs": "The tinder and kindling burn away. Add logs before lighting.",
    "entrance_roadtrip_camp_fire_no_tinder": "The match dies. Add tinder first.",
    "entrance_roadtrip_camp_fire_no_twigs": "The tinder burns out. It needed kindling.",
    "entrance_roadtrip_camp_fire_stack": "Stacked",
    "entrance_roadtrip_camp_fire_teepee": "Teepee",
    "entrance_roadtrip_camp_fire_tinder": "Tinder",
    "entrance_roadtrip_camp_fire_title": "Build the fire",
    "entrance_roadtrip_camp_fire_twigs": "Twigs",
    "entrance_roadtrip_camp_food_warning": "Never leave food outside at night.",
    "entrance_roadtrip_camp_lake_aria": "Skip a stone across Abraham Lake",
    "entrance_roadtrip_camp_marketa_aria": "Make Markéta laugh",
    "entrance_roadtrip_camp_pine_aria": "Drop a pinecone",
    "entrance_roadtrip_camp_poplar_aria": "Wiggle the poplar eyes",
    "entrance_roadtrip_camp_sign": "CAMPING",
    "entrance_roadtrip_camp_sleep_prompt": "It’s getting late. Let’s put out the fire and get some sleep.",
    "entrance_roadtrip_camp_tent_aria": "Open or close the tent",
    "entrance_roadtrip_camping": "Camping",
    "entrance_roadtrip_centerline": "Crossed the centre line · −2 points.",
    "entrance_roadtrip_collision": "Rear-end impact · 10–40 point penalty, combo reset.",
    "entrance_roadtrip_continue": "Continue",
    "entrance_roadtrip_court_fine": "court-set fine",
    "entrance_roadtrip_crash": "Head-on crash · −100 points, windshield shattered, engine stalled.",
    "entrance_roadtrip_demerit_label": "DEMERITS",
    "entrance_roadtrip_demerit_suspended": " · licence suspended for {time}",
    "entrance_roadtrip_demerit_warning": " · demerit warning",
    "entrance_roadtrip_drive": "Highway · Space sets cruise · Enter pauses · dodge traffic and collect ♥️, 🍄, 💋, 🐸 & ∞.",
    "entrance_roadtrip_escape": "Wildlife clear · +{points} pts · {combo}× combo.",
    "entrance_roadtrip_exit": "Leave highway",
    "entrance_roadtrip_frog": "🐸 collected · +{points} pts · {combo}× combo.",
    "entrance_roadtrip_grade_legend": "Highway legend",
    "entrance_roadtrip_grade_regular": "Roadtrip regular",
    "entrance_roadtrip_grade_scenic": "Scenic run",
    "entrance_roadtrip_grade_sunday": "Scenic drive",
    "entrance_roadtrip_heart": "♥️ collected · +{points} pts · {combo}× combo.",
    "entrance_roadtrip_hedgehog_collision": "Hedgehog clipped · 2–8 point penalty, combo reset.",
    "entrance_roadtrip_inf": "Rare ∞ collected · +{points} pts · {combo}× combo.",
    "entrance_roadtrip_invite_accept": "Take the highway",
    "entrance_roadtrip_invite_title": "Let’s road trip!",
    "entrance_roadtrip_kiss": "💋 collected · +{points} pts · {combo}× combo.",
    "entrance_roadtrip_mushroom": "🍄 collected · +{points} pts · {combo}× combo.",
    "entrance_roadtrip_new": "New",
    "entrance_roadtrip_notebook_draft": "Without realizing, they formed a circle. How ridiculous, Parvaneh thought, glancing over her friends, who were exchanging uneasy looks. It was one of those first hot days of early summer that would burn her skin. In her youth, she’d chase the first scorching rays for a spring tan, but nowadays, she wanted to protect her skin at all costs. She shifted to the shade to avoid the sun climbing fast to its peak, which the others didn’t seem to mind. Of course, they were Iranians.",
    "entrance_roadtrip_notebook_title": "Chapter 1",
    "entrance_roadtrip_pass": "Clean close pass · +{points} pts · {combo}× combo.",
    "entrance_roadtrip_pause_line": "Play to resume · Esc to exit.",
    "entrance_roadtrip_pause_title": "PAUSED",
    "entrance_roadtrip_points_short": "pts",
    "entrance_roadtrip_police_arrest": "Stopped · officer approaching the driver’s window.",
    "entrance_roadtrip_police_capture": "Police closing in · braking override engaged.",
    "entrance_roadtrip_police_centerline_pursuit": "Stayed across the double solid line · pull onto the right shoulder and stop.",
    "entrance_roadtrip_police_centerline_ticket": "Crossed the double solid line · fine {fine} · {points} demerits · {total}/15{status}.",
    "entrance_roadtrip_police_clear": "Police passed · within tolerance.",
    "entrance_roadtrip_police_court_refused": "You didn’t pull over · {fine} · {points} demerits · {total}/15{status} · highway run over.",
    "entrance_roadtrip_police_court_stopped": "Stopped · police pulling in ahead.",
    "entrance_roadtrip_police_escape": "Police receding · hold above 215 to lose them.",
    "entrance_roadtrip_police_escaped": "Police lost · sirens fading away.",
    "entrance_roadtrip_police_impaired_pursuit": "Erratic impaired driving observed · pull onto the right shoulder and stop.",
    "entrance_roadtrip_police_impaired_summons": "Erratic impaired driving · {fine} · {points} demerits · {total}/15{status} · 250-point penalty.",
    "entrance_roadtrip_police_pull_over": "Police behind · pull onto the right shoulder and stop.",
    "entrance_roadtrip_police_pursuit": "Clocked at {speed} km/h · pull onto the right shoulder and stop.",
    "entrance_roadtrip_police_refused": "No pull-over · fine {fine} · {points} pts · {total}/15{status} · −1,000 score.",
    "entrance_roadtrip_police_stopped": "Stopped · police pulling in behind.",
    "entrance_roadtrip_police_summons": "{over} km/h over · {fine} · {points} demerits · {total}/15{status}.",
    "entrance_roadtrip_police_ticket": "{over} km/h over · fine {fine} · {points} demerits · {total}/15{status}.",
    "entrance_roadtrip_police_warning": "Headlights ×3 · police ahead. Watch your speed.",
    "entrance_roadtrip_rabbit_collision": "Rabbit clipped · 2–8 point penalty, combo reset.",
    "entrance_roadtrip_reenter": "Road Trip",
    "entrance_roadtrip_resume": "Roadtrip paused · steer or press a pedal to resume.",
    "entrance_roadtrip_route_abraham": "Abraham Lake",
    "entrance_roadtrip_route_banff": "Banff",
    "entrance_roadtrip_route_calgary": "Calgary",
    "entrance_roadtrip_route_stage_1": "SEGMENT 1",
    "entrance_roadtrip_route_stage_2": "SEGMENT 2",
    "entrance_roadtrip_route_stage_3": "SEGMENT 3",
    "entrance_roadtrip_route_title": "Choose a destination",
    "entrance_roadtrip_select_gear": "Select a driving gear.",
    "entrance_roadtrip_stargazing_ad_infinitum": "—ad infinitum.",
    "entrance_roadtrip_stargazing_behdad_1a": "They say all good things end—",
    "entrance_roadtrip_stargazing_behdad_1b": "but this is just the beginning…",
    "entrance_roadtrip_stargazing_behdad_2": "Until that ends as well.",
    "entrance_roadtrip_stargazing_cassiopeia": "Cassiopeia",
    "entrance_roadtrip_stargazing_continue": "Great wisdom dispensed.",
    "entrance_roadtrip_stargazing_hint": "Tap or drag the glowing star to trace each constellation.",
    "entrance_roadtrip_stargazing_invite": "The sky is clear. Click the sky to look up.",
    "entrance_roadtrip_stargazing_marketa_1a": "…and bad things end—",
    "entrance_roadtrip_stargazing_marketa_1b": "which is also good.",
    "entrance_roadtrip_stargazing_marketa_quote_1": "When something is over,",
    "entrance_roadtrip_stargazing_marketa_quote_2": "something else begins",
    "entrance_roadtrip_stargazing_title": "Stargazing",
    "entrance_roadtrip_stargazing_ursa_major": "Ursa Major",
    "entrance_roadtrip_stargazing_ursa_minor": "Ursa Minor",
    "entrance_roadtrip_start_engine": "Start the engine.",
    "entrance_roadtrip_stew_barley": "Barley",
    "entrance_roadtrip_stew_beans": "Beans",
    "entrance_roadtrip_stew_beef": "Beef",
    "entrance_roadtrip_stew_burnt_serve": "That bowl could be used to resurface the highway.",
    "entrance_roadtrip_stew_carrots": "Carrots",
    "entrance_roadtrip_stew_celery": "Celery",
    "entrance_roadtrip_stew_chicken": "Chicken",
    "entrance_roadtrip_stew_chilies_first": "Thai",
    "entrance_roadtrip_stew_chilies_second": "chilies",
    "entrance_roadtrip_stew_cook": "Cook",
    "entrance_roadtrip_stew_cooking_feedback": "The stew is cooking over the fire.",
    "entrance_roadtrip_stew_coriander": "Coriander",
    "entrance_roadtrip_stew_crate": "STEW",
    "entrance_roadtrip_stew_curry_first": "Curry",
    "entrance_roadtrip_stew_curry_second": "paste",
    "entrance_roadtrip_stew_garlic": "Garlic",
    "entrance_roadtrip_stew_ginger": "Ginger",
    "entrance_roadtrip_stew_invite": "Let’s make some stew.",
    "entrance_roadtrip_stew_lamb": "Lamb",
    "entrance_roadtrip_stew_mushrooms": "Mushrooms",
    "entrance_roadtrip_stew_onion": "Onion",
    "entrance_roadtrip_stew_overcooked_feedback": "The stew overcooked. Click the pot to start over.",
    "entrance_roadtrip_stew_pasta": "Pasta",
    "entrance_roadtrip_stew_pepper_first": "Black",
    "entrance_roadtrip_stew_pepper_second": "pepper",
    "entrance_roadtrip_stew_pork": "Pork",
    "entrance_roadtrip_stew_potatoes": "Potatoes",
    "entrance_roadtrip_stew_protein": "PROTEIN",
    "entrance_roadtrip_stew_raw_serve": "Still raw. Lid down, patience up.",
    "entrance_roadtrip_stew_ready_feedback": "The stew’s ready. Serve it while it’s lovely.",
    "entrance_roadtrip_stew_reset": "Start over",
    "entrance_roadtrip_stew_rice": "Rice",
    "entrance_roadtrip_stew_salt": "Salt",
    "entrance_roadtrip_stew_serve": "Serve",
    "entrance_roadtrip_stew_served_feedback": "Two warm bowls and two very happy campers.",
    "entrance_roadtrip_stew_starch": "BASE",
    "entrance_roadtrip_stew_tofu": "Tofu",
    "entrance_roadtrip_stew_tomato_first": "Tomato",
    "entrance_roadtrip_stew_tomato_second": "paste",
    "entrance_roadtrip_suspended": "Licence suspended · Road Trip temporarily unavailable.",
    "entrance_roadtrip_suspended_short": "Suspended · {time}",
    "entrance_roadtrip_transport_paused": "Play to resume · Esc to exit.",
    "entrance_roadtrip_unlocked": "All 10 rooms explored · fancy a road trip?",
    "entrance_roadtrip_wildlife_collision": "Wildlife strike · 20–60 point penalty, combo reset.",
    "explore_balcony": "Enjoy wandering — the balcony's the good part. 🌅",
    "explore_cuddly": "Enjoy wandering — curl up and poke around. 🐙",
    "explore_garden": "Enjoy wandering — the garden's full of small things. 🌿",
    "explore_kitchen": "Enjoy wandering — the kitchen keeps more than coffee. ☕",
    "explore_office": "Enjoy wandering — the office is more toy than work. 🖥️",
    "flair_hint": "Move Pouria to catch garnishes 🍋; dodge the wasp 🐝.",
    "garden": "Water a plant, play music, light candles.",
    "garden_need_candles": "Now light the candles.",
    "garden_need_music": "Now play music.",
    "garden_need_music_candles": "Play music, light candles.",
    "garden_need_water": "Now water a plant.",
    "garden_need_water_candles": "Water a plant, light candles.",
    "garden_need_water_music": "Water a plant, play music.",
    "garden_party": "Party's on — dance like nobody's watering. 💃🌱",
    "intro": "Practice the art of aimless wandering.",
    "intro_guide": "Instructions at the bottom.",
    "intro_guide_dismiss": "Click to dismiss.",
    "intro_guide_nav": "Navigation at the top.",
    "intro_promise": "Explore → Party → Road Trip",
    "kitchen": "Turn on La Maz → run El Maz → brew.",
    "kitchen_again": "Go ahead—make another espresso. ☕",
    "kitchen_bar": "Bar's open — watch <em>Pouria</em> mix a drink. Or order one. 🍸",
    "kitchen_bar_night": "Bar is open. Ask <em>Pouria</em> for a drink… 🍸",
    "kitchen_brew": "Now brew a shot.",
    "kitchen_grind": "Now grind coffee.",
    "kitchen_grinder_empty": "The grinder's out of beans.",
    "kitchen_grinder_refill": "Topped up the hopper — fresh beans. ☕",
    "kitchen_need_grind": "Grind the coffee first.",
    "kitchen_need_knockout": "Empty the old grounds first.",
    "kitchen_need_power": "Turn the machine on first.",
    "kitchen_need_tamp": "Next, tamp the coffee.",
    "kitchen_sip": "Go on, sip it. ☕",
    "kitchen_warming_up": "Let it warm up first.",
    "lower_bathroom": "Bathroom · play with the fixtures.",
    "lower_bedroom": "Bedroom · the window is calling.",
    "lower_cinema": "Cinema · choose a film to watch.",
    "lower_dungeon": "Dungeon · the old game is awake.",
    "lower_entrance": "Fancy-Stupid! · click the road to take the wheel.",
    "lower_entrance_before_party": "The car is yours to drive · finish the upstairs clue trail to unlock the party first.",
    "lower_entrance_locked": "The car is yours to drive · explore all 10 rooms to unlock Road Trip.",
    "lower_entrance_ready": "All 10 rooms seen · click the road to start your Road Trip.",
    "octi_escape_hint": "Watch where Octi hides, then tap that cushion.",
    "octi_escape_invite": "Octi eyes the cushions. Squeeze him once more. 🐙",
    "octi_escape_one": "Found him. Two hiding places left.",
    "octi_escape_two": "Again. One last hiding place.",
    "octi_escape_win": "Caught! Octi scuttles back to his trunk perch. 🐙",
    "octi_escape_wrong": "Just cushion. Octi peeks again…",
    "office": "Call Prague first — it's on the laptop.",
    "office_block_party": "Try the lit windows on the balcony.",
    "office_call": "Call Prague first — it's on the laptop.",
    "office_computer": "Play with the PC (not the laptop).",
    "office_find": "Find the stained-glass butterfly.",
    "office_hangup": "Hang up now.",
    "office_hint": "When you're done, turn off the lights.",
    "party_ended": "Party's over for now, not the game. The loft and apps are still yours.",
    "party_exit_hint": "The Garden disco ball toggles Party, not the game. Ending it is optional; the loft and apps stay open.",
    "party_rooms_complete": "You’ve seen all 10 rooms. Perfect day for a Road Trip!",
    "party_rooms_incomplete": "All rooms are open. You’ve seen {n} of 10 — explore the loft.",
    "prince_dark": "Too dark to read the wall.",
    "prince_gate_secret": "Dungeon · something crowned blinked behind the gate.",
    "recovery_continue": "▶ Continue",
    "recovery_days": "{n} d ago",
    "recovery_hours": "{n} hr ago",
    "recovery_just_now": "just now",
    "recovery_meta": "Saved {room} · {age}",
    "recovery_minutes": "{n} min ago",
    "recovery_restart": "↻ Start over",
    "recovery_title": "Welcome back",
    "roadtrip_completion_action": "Go to the car →",
    "roadtrip_completion_coach": "You’ve seen the whole Loft. Let’s go on a Road Trip.",
    "roadtrip_departure_caption": "Who wants to go on a Road Trip? Head out to the car.",
    "room_progress": "Rooms seen: {n}/10 · keep exploring.",
    "room_visit_bathroom_few": "Here’s the bathroom. {n} more rooms to go.",
    "room_visit_bathroom_many": "Here’s the bathroom. {n} more rooms to go.",
    "room_visit_bathroom_one": "Here’s the bathroom. 1 more room to go.",
    "room_visit_bedroom_few": "This is the bedroom, if you need to rest. {n} more rooms to go.",
    "room_visit_bedroom_many": "This is the bedroom, if you need to rest. {n} more rooms to go.",
    "room_visit_bedroom_one": "This is the bedroom, if you need to rest. 1 more room to go.",
    "room_visit_cinema_few": "This is the cinema. {n} more rooms to go.",
    "room_visit_cinema_many": "This is the cinema. {n} more rooms to go.",
    "room_visit_cinema_one": "This is the cinema. 1 more room to go.",
    "room_visit_complete": "That’s the whole loft. Head out front.",
    "room_visit_complete_party": "That’s the whole loft. Head out front to the street.",
    "room_visit_dungeon_few": "This is the dungeon. You go alone. {n} more rooms to go.",
    "room_visit_dungeon_many": "This is the dungeon. You go alone. {n} more rooms to go.",
    "room_visit_dungeon_one": "This is the dungeon. You go alone. 1 more room to go.",
    "room_visit_entrance_complete": "You’ve seen the whole loft. The road is right outside.",
    "room_visit_entrance_complete_party": "You’ve seen the whole loft. The road is right outside.",
    "room_visit_entrance_few": "Here’s the front entrance. Explore {n} more rooms before the Road Trip.",
    "room_visit_entrance_many": "Here’s the front entrance. Explore {n} more rooms before the Road Trip.",
    "room_visit_entrance_one": "Here’s the front entrance. Explore 1 more room before the Road Trip.",
    "tetris_game_over": "Game over · Enter: play again · Esc: exit.",
    "tetris_hint": "Keys: ← → move · ↑ rotate · Space drops.",
    "tetris_touch_game_over": "Game over · Tap: play again · ×: exit.",
    "tetris_touch_hint": "Tap to rotate; swipe to move or drop. × exits."
  },
  "hunt_title": "Loft Day",
  "install_dismiss": "Dismiss",
  "install_ios_hint": "Tap Share, then “Add to Home Screen”",
  "install_label": "Install app",
  "kbd_arrows": "previous / next room",
  "kbd_console": "open / close the console",
  "kbd_d": "day ↔ night",
  "kbd_devices": "monitor / laptop / cellphone",
  "kbd_digits": "upstairs room",
  "kbd_enter": "advance the room puzzle · Road Trip pause",
  "kbd_esc": "dismiss / go back · Road Trip pause, then exit",
  "kbd_f": "fullscreen",
  "kbd_g": "next phone message",
  "kbd_kitten": "toggle the kitten",
  "kbd_lower_digits": "downstairs room",
  "kbd_manual": "Game manual",
  "kbd_n": "next track (dance / piano piece / song)",
  "kbd_party": "start the Party",
  "kbd_qm": "this list",
  "kbd_roadtrip": "unlock every room for Road Trip",
  "kbd_s": "season change",
  "kbd_shift_arrows": "previous / next key day",
  "kbd_shift_updown": "clock +30 / −30 min",
  "kbd_slash": "open / close messages",
  "kbd_space": "game / media action · set driving cruise",
  "kbd_t": "next trip",
  "kbd_tab": "open / close the whole-loft view",
  "kbd_title": "Keyboard shortcuts",
  "kbd_trips": "laughing gas · shrooms · acid · froggies · dmt · molly · k. · iboga",
  "kbd_u": "toggle the UV / blacklight",
  "kbd_vertical": "descend / return",
  "kbd_watch": "who’s here? (roster for this room)",
  "laptop_amour": "Love",
  "laptop_calling": "Calling…",
  "laptop_connecting": "Connecting…",
  "laptop_ctx_end": "End call",
  "laptop_ctx_translate": "Translate",
  "laptop_date": "July 10",
  "laptop_lplace": "Lübeck",
  "laptop_place": "Prague",
  "laptop_sweet1": "What’s new:",
  "laptop_sweet2": "the rest of",
  "laptop_sweet3": "our lives ♥",
  "life_blinker": "blinker",
  "life_gen": "GEN",
  "life_glider": "glider",
  "life_help_copy": "A zero-player game: once you draw a starting pattern, the rules run it for you. A cell is born with 3 neighbours and survives with 2 or 3. Draw cells, then play, step, change speed, or try a pattern. Space pauses. <a href=\"https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life\" target=\"_blank\" rel=\"noopener\">Wikipedia</a>.",
  "life_help_title": "Conway’s Game of Life",
  "life_pulsar": "pulsar",
  "lower_portal_insist": "I insist.",
  "lower_portal_unlock": "Unlock",
  "lower_rooms_clue": "The loft may have kept a few rooms out of sight.",
  "madla_fam": "Madla",
  "madla_place": "night shift, Germany",
  "mail_back": "‹ Inbox",
  "mail_body_lore": "hi you.\nwe're getting married — twice: Edmonton on May 1, 2027, and Prague on July 10, 2027.\ncome to one or both — all our loved ones welcome, small or big.\nbetween the parties, the loft misses visitors. — m ∞ b",
  "mail_body_rsvp": "the couch is saving you a seat.\nhit reply and put us out of our suspense.",
  "mail_body_spam": "it's us. we're the hot singles.\nwe're getting married.\nunsubscribe at the wedding.",
  "mail_cancel": "Cancel",
  "mail_cc": "Cc",
  "mail_compose": "Compose",
  "mail_compose_subject": "hello from the loft",
  "mail_from_lore": "markéta ∞ behdad",
  "mail_from_rsvp": "the loft",
  "mail_from_spam": "totally-real-deals",
  "mail_inbox_title": "inbox",
  "mail_message": "Message",
  "mail_reply_body": "Hi Markéta & Behdad!\n\nYes! Count me in for Edmonton / Prague / both.\n\n",
  "mail_reply_btn": "Reply",
  "mail_reply_subject": "Re: will you be there?",
  "mail_send": "Send",
  "mail_subj_lore": "so, we're doing this twice",
  "mail_subj_rsvp": "will you be there?",
  "mail_subj_spam": "HOT SINGLES IN YOUR LOFT AREA 🔥",
  "mail_subject": "Subject",
  "mail_to": "To",
  "marketa_url": "https://marketajakesova.ca",
  "meteor_deltaaquariids": "🌠 delta aquariids",
  "meteor_draconids": "🌠 draconids",
  "meteor_geminids": "🌠 geminids",
  "meteor_leonids": "🌠 leonids",
  "meteor_lyrids": "🌠 lyrids",
  "meteor_orionids": "🌠 orionids",
  "meteor_perseids": "🌠 perseids",
  "meteor_quadrantids": "🌠 quadrantids",
  "meteor_taurids": "🌠 taurids",
  "meteor_ursids": "🌠 ursids",
  "mines_lose": "You set off the ring!<br>(It was always going to happen.)",
  "mines_win": "The ring stays a surprise.",
  "mix_campari": "Campari",
  "mix_curacao": "Blue curaçao",
  "mix_gin": "Gin",
  "mix_house": "House Pour",
  "mix_vermouth": "Sweet vermouth",
  "mol_caption": "we’ve got chemistry",
  "mol_caption_ethanol": "Reality is an illusion caused by alcohol deficiency.",
  "mol_caption_thc": "this is sooo sick, bro",
  "mol_name_acid": "LSD",
  "mol_name_dmt": "N,N-DMT",
  "mol_name_ethanol": "Ethanol",
  "mol_name_froggies": "5-MeO-DMT",
  "mol_name_iboga": "Ibogaine",
  "mol_name_ketamine": "Ketamine",
  "mol_name_molly": "MDMA",
  "mol_name_nitrous": "Nitrous oxide",
  "mol_name_shrooms": "Psilocybin",
  "mol_name_thc": "THC",
  "mol_street_acid": "acid",
  "mol_street_dmt": "DMT",
  "mol_street_ethanol": "booze",
  "mol_street_froggies": "froggies",
  "mol_street_iboga": "iboga",
  "mol_street_ketamine": "k",
  "mol_street_molly": "molly",
  "mol_street_nitrous": "laughing gas",
  "mol_street_shrooms": "shrooms",
  "mol_street_thc": "weed",
  "mom_bouquet": "Bouquet Toss",
  "mom_cake": "Cake Cutting",
  "mom_firstdance": "First Dance",
  "mom_groupphoto": "Group Photo",
  "mom_slowdance": "Slow Dance",
  "mom_sparklers": "Sparkler Send-off",
  "mom_toasts": "Toasts",
  "mon_about_home": "the place we (Markéta & behdad) call home.",
  "mon_about_party": "and find the party.",
  "mon_about_title": "Welcome to The Loft",
  "mon_about_wander": "Wander around, make coffee, meet our people,",
  "mon_ctx_copy": "Copy",
  "mon_ctx_cut": "Cut",
  "mon_ctx_kill": "Kill app",
  "mon_ctx_open": "Open",
  "mon_ctx_paste": "Paste",
  "mon_ctx_reset_eq": "Reset EQ",
  "mon_ctx_select_all": "Select all",
  "mon_ctx_stop": "Stop",
  "mon_ctx_uninstall": "Uninstall",
  "mon_help_click": "Click everything! Right-click for more options.",
  "mon_help_clue": "Follow the clue below the scene.",
  "mon_help_keyboard": "Press ? for the full control list.",
  "mon_help_manual": "Game manual ↗",
  "mon_help_title": "Help",
  "mon_kill_hint_desktop": "Right-click a running app to Kill it.",
  "mon_kill_hint_touch": "Press and hold a running app to Kill it.",
  "mon_lock_behdad": "Behdad",
  "mon_lock_blue": "Markéta’s blue baker cap",
  "mon_lock_marketa": "Markéta",
  "mon_lock_pink": "Behdad’s pink flat cap",
  "mon_lock_prompt": "Match the caps, or press Caps Lock twice.",
  "mon_lock_title": "CAPS LOCK",
  "mon_lock_unlocked": "unlocked",
  "mon_reboot_gag": "Have you tried closing all windows?",
  "mon_shutdown_gag": "Have a lofty evening!",
  "mon_sleep_gag": "Time for me to take a nap.. Zzz...",
  "mon_sys_credits": "Credits",
  "mon_sys_help": "Help",
  "mon_sys_lock": "Lock",
  "mon_sys_reboot": "Reboot",
  "mon_sys_shutdown": "Shut down",
  "mon_sys_sleep": "Sleep",
  "mon_sys_system": "System",
  "mon_sys_tagline_1": "The Loft: where artificial meets higher intelligence.",
  "mon_sys_title": "Loft OS",
  "mon_sys_website": "About",
  "mon_system_info_browser": "Browser",
  "mon_system_info_full": "Full detail",
  "mon_system_info_graphics": "Graphics",
  "mon_system_info_hardware": "Hardware",
  "mon_system_info_input": "Input",
  "mon_system_info_limitations": "Known limitations",
  "mon_system_info_measuring": "Measuring…",
  "mon_system_info_motion_reduced": "Reduced motion",
  "mon_system_info_motion_standard": "Standard motion",
  "mon_system_info_performance": "Performance",
  "mon_system_info_pointer": "Pointer",
  "mon_system_info_ready": "No known issues",
  "mon_system_info_recommendation": "Best in the latest desktop Chrome.",
  "mon_system_info_reduced": "Reduced detail",
  "mon_system_info_status": "Status",
  "mon_system_info_title": "System Information",
  "mon_system_info_touch": "Touch + pointer",
  "mon_system_info_unreported": "Not reported",
  "mon_system_info_upgrade": "Update recommended",
  "msg_action_coach": "Try the arrows",
  "msg_album_body": "new photo added — let's take another selfie!",
  "msg_albumfull_body": "been snapping all night 📸 your album's filling up — take a look",
  "msg_ali_from": "Ali",
  "msg_ali_love_body": "<em>Habibi</em>s, I love you all!",
  "msg_alireza_from": "Alireza",
  "msg_aspen_banter_body": "if you see me hiding behind a plant, keep doing whatever made you laugh 📸",
  "msg_aspen_from": "Aspen",
  "msg_athena_banter_body": "schedule update: we’re exactly on time if nobody checks the schedule. ✨",
  "msg_athena_from": "Athena",
  "msg_ayushi_from": "Ayushi",
  "msg_badge_coach": "New message. Tap to read.",
  "msg_baharak_from": "Baharak",
  "msg_bahareh_from": "Bahareh",
  "msg_bbq_body": "let's start the BBQ 🔥🍔",
  "msg_bbq_cheer_madla_body": "running — save me the crispy tofu 🔥",
  "msg_bbq_cheer_pouria_body": "too late, I'm already holding a plate 🍽️",
  "msg_behdad_aspen_reply_body": "Aspen is branching out. 🌿",
  "msg_behdad_from": "behdad",
  "msg_behdad_to_marketa_from": "behdad → markéta",
  "msg_bouquet_body": "bouquet toss time!! who's catching it?? 💐",
  "msg_cake_body": "the cake is out!! come cut it you two 🍰🔪",
  "msg_charlie_body_a": "Hi, Charlie here. I know this loft pretty well—ask me anything, or just come chat. 💬",
  "msg_charlie_body_b": "Need a clue, directions, or a little company? Message me. —Charlie 💬",
  "msg_charlie_body_c": "Hello from inside the computer. I’m Charlie; I know the loft, the people, and most of the secrets. 💬",
  "msg_charlie_body_d": "Looking for a way around, an answer, or an excuse to leave the dance floor? I’m around. —Charlie 💬",
  "msg_charlie_body_e": "I’m Charlie. Ask me about the wedding, the loft, or whatever just happened. 💬",
  "msg_charlie_body_f": "Psst. If this place gets confusing, I probably know what’s going on. Probably. —Charlie 💬",
  "msg_charlie_from": "Charlie",
  "msg_chinnell_from": "Chinnell",
  "msg_copy": "Copy",
  "msg_danesh_body": "dude your crowd is SOOOOOOO HOT! 🔥",
  "msg_danesh_from": "DJ Danesh",
  "msg_downstairs_bathroom_body": "Where’s the toilet?",
  "msg_downstairs_bedroom_body": "I need to lie down for a minute.",
  "msg_downstairs_cinema_ask_body": "I heard you have an awesome home theatre.",
  "msg_downstairs_cinema_reply_body": "Come see it!",
  "msg_downstairs_dungeon_body": "Daaeee, there’s a dungeon door in the garden.",
  "msg_downstairs_entrance_body": "Fancy a road trip?",
  "msg_downstairs_roadtrip_go_body": "Let’s go!",
  "msg_downstairs_roadtrip_journey_body": "The journey is the destination.",
  "msg_downstairs_roadtrip_where_body": "Where to?",
  "msg_dusk_body": "eclipse on the balcony 🌑 come out?",
  "msg_empty": "No messages yet — the wedding crew will write here as the day unfolds.",
  "msg_farhang_banter_body": "I have the microphone and apparently no adult supervision. 🎤",
  "msg_farhang_from": "Farhang",
  "msg_fireworks_body": "FINALE TIME 🎆 get out on the balcony!",
  "msg_firstdance_body": "Ready for the first dance? 💃",
  "msg_flair_body": "I need a break 🍸",
  "msg_fresh_air_body": "Fancy some fresh air?",
  "msg_group_body": "you dancing or what?? 💃",
  "msg_group_from": "Wedding crew",
  "msg_groupphoto_body": "📸 everyone in for the group photo! gather round 🤗",
  "msg_hamid_bbq_done_body": "grill defeated. nobody leaves hungry on my watch 🔥✅",
  "msg_hamid_food_body": "grill's open — first batch is ready, come get it while it's hot 🔥🍔🌽",
  "msg_hamid_from": "Hamid",
  "msg_hamid_verse2_body": "<em>رفتم تو آب، آب اومده تا سرِ زانوم.</em>",
  "msg_hamid_verse_body": "<em>من پسرِ باادبِ میرزامشیرم</em>",
  "msg_hannah_banter_body": "official gymnastics score for this dance floor: 10/10 🤸",
  "msg_hannah_from": "Hannah",
  "msg_hannah_piano_body_a": "<em>daee joon</em>, can I play the piano?",
  "msg_hannah_piano_body_b": "Mom, can I play the piano?",
  "msg_hannah_piano_body_c": "Dad, can I play the piano?",
  "msg_hannah_tetris_body": "can I play Tetris?",
  "msg_heat_body": "Could somebody bring something cold? 🧊",
  "msg_input_placeholder": "Message the wedding crew…",
  "msg_invaders_body": "Irene, did you see the aliens in the office? 👾",
  "msg_irene_banter_body": "I checked: the party is not valid Python, but it still runs 🐍",
  "msg_irene_from": "Irene",
  "msg_irene_games_body": "<em>daeeee</em> I'm bored. can I play games on the computer?",
  "msg_irene_tictactoe_body": "can I play tic-tac-toe?",
  "msg_jay_bbq_satisfied_body": "By the power vested in me, I hereby declare my hunger officially satisfied. 🌿⚖️",
  "msg_jay_from": "Jay",
  "msg_jukebox_body": "requests are open 🎧 tap to pick the next song",
  "msg_kidsasleep_body_a": "kids are finally asleep 😴",
  "msg_kidsasleep_body_b": "kids are FINALLY down 😴 don't you dare wake them",
  "msg_kidsloose_body_a": "kids are on the loose again! 🙃",
  "msg_kidsloose_body_b": "and they're awake again 🙃 send help",
  "msg_lanterns_body": "let's send up wish-lanterns 🏮 make a wish ✨",
  "msg_lastdance_body": "last dance, everyone — grab your person 💞",
  "msg_lastsong_body": "last song! make it count 🎧",
  "msg_madla_from": "Madla",
  "msg_mahzad_from": "Mahzad",
  "msg_mark_all_read_short": "✓ all",
  "msg_mark_read": "Mark as read.",
  "msg_mark_unread": "Mark as unread.",
  "msg_marketa_from": "markéta",
  "msg_marketa_to_behdad_from": "markéta → behdad",
  "msg_mb_body": "did you RSVP yet? 😉 no pressure. (some pressure.)",
  "msg_mb_from": "markéta & behdad",
  "msg_new_divider": "New",
  "msg_patricia_from": "Patricia",
  "msg_pouria_banter_body": "tonight’s new hobby: reminding everyone to drink water 💧",
  "msg_pouria_body": "bar's open again 🍸 get down here",
  "msg_pouria_farhang_body": "Farhang, <em>chetori chaghal?</em>",
  "msg_pouria_from": "Pouria",
  "msg_reply": "Reply…",
  "msg_replying_to": "Replying to {name}",
  "msg_search_none": "no messages match that search.",
  "msg_search_placeholder": "search messages…",
  "msg_sina_from": "Sina",
  "msg_slowdance_body": "ok DJ, slow one now — grab your person 🥰🕯️",
  "msg_smores_body": "who wants s'mores? 🔥🍫",
  "msg_sparklers_body": "✨ sparklers out front for the send-off — form the tunnel!",
  "msg_spencer_from": "Spencer",
  "msg_sunrise_body": "wait it's sunrise already?! 😳☀️ we pulled an all-nighter",
  "msg_sunset_baharak_awake_body": "Hannah! you too — why are you still awake?! 😳",
  "msg_sunset_bahareh_awake_body": "Irene! why are you still awake?! 😳",
  "msg_sunset_bed_body": "I'm going to sleep. Last person up can dim the disco ball — if you feel like it. 😴",
  "msg_sunset_body": "this sunset is UNREAL 🌅 get on the balcony",
  "msg_sunset_hannah_tattoo_body": "can I draw your next tattoo? ✍️🖋️",
  "msg_sunset_irene_code_body": "can I draw some turtle art in Python on the computer? 🐢🐍🎨",
  "msg_sunset_magicbox_body": "ooooooooooooooooor… magic box and keep going? 👀✨",
  "msg_toasts_body": "🥂 speech time! grab a glass — Ali & Farhang want to say a few words",
  "msg_trip_body_a": "Vitamin time? 💊",
  "msg_trip_body_b": "who's got some party helpers? 😜",
  "msg_trip_body_c": "the magic box is calling… 🍄✨",
  "msg_trip_body_d": "anyone checking the magic box? 👀",
  "msg_trip_body_e": "party supplies are in the magic box 🎁",
  "msg_trip_body_f": "take a little trip? 🌈",
  "msg_unread_only_short": "unread",
  "msg_visit_ali_a": "yo are you two home? we're right around the corner 🍷",
  "msg_visit_alireza_a": "home? we brought souvenirs from the trip ✈️",
  "msg_visit_ayushi_a": "home? I'm nearby and ready for a dramatic entrance ✨",
  "msg_visit_baharak_a": "<em>salam aziz</em>, are you home? Payman & Hannah are with me 🌸",
  "msg_visit_bahareh_a": "are you home, <em>aziz</em>? Irene's dying to see you 👧",
  "msg_visit_body_a": "are you home? 🏠",
  "msg_visit_body_b": "you lovebirds home? 💕",
  "msg_visit_body_c": "want visitors? 👀",
  "msg_visit_body_d": "knock knock — you around? ✊",
  "msg_visit_body_e": "we're in the neighbourhood, home? 🚶",
  "msg_visit_body_f": "coffee's on you if you're home ☕",
  "msg_visit_body_g": "miss your faces — home right now? 🥺",
  "msg_visit_body_h": "quick pop-in? are you two in? 🔔",
  "msg_visit_body_i": "is the door open for us? 🚪",
  "msg_visit_farhang_a": "home? Lauren & I are just around the corner 🎩",
  "msg_visit_hamid_a": "yo are you home? Athena & I would love to pop by 💛",
  "msg_visit_madla_a": "ahoj! are you home? we're all here with the mouses 🐭",
  "msg_visit_patricia_a": "home? the kids can't wait to see you two! 🧒👶",
  "msg_visit_spencer_a": "hey!! are you home? we'd love to swing by 🤗",
  "msg_you_from": "You",
  "name_patricia_daughter": "Patricia’s daughter",
  "name_patricia_son": "Patricia’s son",
  "notes_email_intro": "Hi Markéta & Behdad!\n\nHere's a note from your loft:",
  "notes_email_subject": "A little note from your loft 💌",
  "notes_placeholder": "leave us a few words…",
  "notes_send": "Gmail",
  "notes_send_lead": "Send to us",
  "notes_send_mail": "Email",
  "notes_write_lead": "write us a little note",
  "np": {
    "aqua": "Aquarium ambient",
    "bandari": "Bandari",
    "bhangra": "Bhangra",
    "bulgar": "Klezmer bulgar",
    "coffee": "Slow coffee",
    "cumbia": "Cumbia",
    "disco": "Disco",
    "dupak": "Dupák",
    "furiant": "Bohemian furiant",
    "polka": "Polka",
    "salsa": "Salsa",
    "swing": "Swing",
    "tango": "Tango",
    "techno": "Techno",
    "totoro": "Woodland rain",
    "waltz": "Waltz",
    "workout": "Workout beat"
  },
  "occ_banner_bbq": "🍖 BBQ Day",
  "occ_banner_brunch": "🍳 Garden Brunch",
  "occ_banner_wed_edm": "💍 Edmonton Wedding",
  "occ_banner_wed_prg": "💍 Prague Wedding",
  "occ_invite_bbq": "cookout on the balcony today 🍖 come by for the BBQ!",
  "occ_invite_brunch": "garden brunch in Prague today 🍳 come join the family!",
  "occ_invite_wed_edm": "it's our Edmonton wedding day! 💍 come celebrate with us",
  "occ_invite_wed_prg": "it's our Prague wedding day! 💍 come celebrate with us",
  "occasion_activate": "activate this day",
  "office_pouf_sock_found": "Two medals—and the missing sock. Of course.",
  "pacman_kill": "GHOSTS WIN",
  "pacman_win": "MAZE CLEARED",
  "pb_btn_cancel": "Cancel",
  "pb_btn_download": "⬇ Download",
  "pb_btn_email": "Email",
  "pb_btn_gmail": "Gmail",
  "pb_btn_retake": "↺ Retake",
  "pb_confirm_no": "Cancel",
  "pb_confirm_q": "Open the photobooth?",
  "pb_confirm_yes": "📷 Open camera",
  "pb_email_body": "Hi Markéta & Behdad!\n\nPaste the picture now — it's on your clipboard (Ctrl/Cmd+V).\n\nSee you at the wedding!",
  "pb_email_subject": "A photo from your loft photobooth 📸",
  "pb_err_1": "no camera here",
  "pb_err_2": "no worries 🙂",
  "pb_err_ok": "OK",
  "pb_frame_heading": "Wedding frame",
  "pb_frame_hearts": "∞ hearts",
  "pb_frame_married": "Count me in",
  "pb_frame_married_text": "count me in",
  "pb_frame_none": "Plain",
  "pb_frame_stamp": "See you in 2027",
  "pb_frame_stamp_text": "see you in 2027",
  "pb_fx_acid": "Acid",
  "pb_fx_bw": "Black & white",
  "pb_fx_dream": "Dreamy",
  "pb_fx_infra": "Infra",
  "pb_fx_kaleido": "Kaleidoscope",
  "pb_fx_neon": "Neon",
  "pb_fx_night": "Night vision",
  "pb_fx_normal": "Normal",
  "pb_fx_poster": "Poster",
  "pb_fx_psy": "Psychedelic",
  "pb_fx_sepia": "Sepia",
  "pb_fx_vapor": "Vaporwave",
  "pb_hint_copied": "Photo copied to clipboard — paste it into your email 📋",
  "pb_hint_nocopy": "tap Download, then attach it to your email ⬇",
  "pb_panel_lead": "Love it? Send it to us 💌",
  "pb_pick_hint": "pick one ✨",
  "pb_strip_caption": "loft photobooth",
  "phone_dialer_title": "contacts",
  "phone_lock_title": "Unlock",
  "phone_notification_many": "{count} notifications",
  "phone_notification_one": "1 notification",
  "phone_recents_empty": "No recently opened apps.",
  "phone_recents_title": "Recent apps",
  "phone_signal_1": "You’re too far from Edmonton.",
  "phone_signal_2": "You’re far from Edmonton.",
  "phone_signal_3": "A little far from Edmonton.",
  "phone_signal_4": "Close enough to Edmonton.",
  "photo_pose_callout_1": "Say cheese! 🧀",
  "photo_pose_callout_2": "Smile! 📸",
  "photo_pose_callout_3": "Everyone look here! 👀",
  "piano_close": "Dismiss piano",
  "piano_coach_1": "Play along—or pause the channel",
  "piano_coach_2": "and take over.",
  "plant_overwatered": "Overwatered. The roots are plotting revenge. 🪰",
  "portrait_action": "Try landscape",
  "portrait_body": "Plays best in landscape, or on a bigger device.",
  "portrait_title": "Rotate your phone",
  "pr_city": "Prague",
  "pr_date1": "Sat, July 10 · 3pm–3am",
  "pr_date2": "Sun, July 11 · 11am–3pm",
  "pr_desc1": "Garden party: drinks, music, dinner, dancing, afterparty.",
  "pr_desc2": "Brunch.",
  "pr_desc_half": "+ sleepover option available.",
  "pr_venue": "Both days at the summer house.",
  "prince_kill_line": "the hourglass runs out.",
  "prince_kill_title": "JAFFAR WINS",
  "quiz_again": "Take quiz again",
  "quiz_continue": "Continue",
  "quiz_lead": "You’re most like",
  "quiz_none": "None of these",
  "quiz_q1": "It’s the wedding afterparty — where do you end up?",
  "quiz_q1a1": "On the dance floor till dawn",
  "quiz_q1a2": "Deep in conversation in a quiet corner",
  "quiz_q1a3": "Behind the camera, catching the moments",
  "quiz_q1a4": "At the bar, mixing everyone a drink",
  "quiz_q1a5": "Keeping an eye on the room and its people",
  "quiz_q2": "Pick the parts of a perfect weekend that fit you.",
  "quiz_q2a1": "A long bike ride or a run",
  "quiz_q2a2": "Curled up with a great book",
  "quiz_q2a3": "Painting or building something",
  "quiz_q2a4": "A board-game marathon",
  "quiz_q2a5": "A walk outside, with room for surprises",
  "quiz_q3": "Your hidden talent?",
  "quiz_q3a1": "I never lose at backgammon",
  "quiz_q3a2": "I can play you a tune",
  "quiz_q3a3": "Best hair in the room",
  "quiz_q3a4": "More languages than I can count",
  "quiz_q3a5": "I can fix, organise, or rescue the situation",
  "quiz_q4": "Choose any soundtracks you would happily hear.",
  "quiz_q4a1": "Techno till sunrise",
  "quiz_q4a2": "Live guitar and piano",
  "quiz_q4a3": "Pop-diva anthems",
  "quiz_q4a4": "A podcast about philosophy",
  "quiz_q4a5": "A warm acoustic song everyone can sing",
  "quiz_q5": "How would friends describe you?",
  "quiz_q5a1": "Obsessed with the tiny details",
  "quiz_q5a2": "Endlessly curious",
  "quiz_q5a3": "Competitive to the core",
  "quiz_q5a4": "The creative one",
  "quiz_q5a5": "The person people call when they need a hand",
  "quiz_q6": "Which family description fits you? Choose all that apply.",
  "quiz_q6a1": "I have no children here — I am here for the grown-up conversation",
  "quiz_q6a2": "I am a parent of one child here",
  "quiz_q6a3": "I am a parent of two children here",
  "quiz_q6a4": "I am one of the children here",
  "quiz_q6a5": "I am a parent or grandparent of this extended family",
  "quiz_q7": "Pick the things that sound like you.",
  "quiz_q7a1": "A curious kid with a camera or a notebook",
  "quiz_q7a2": "A small person who would rather run or build",
  "quiz_q7a3": "A family storyteller",
  "quiz_q7a4": "A person who makes the room warmer",
  "quiz_q7a5": "A musician, listener, or quiet observer",
  "quiz_q8": "What would you bring to the party?",
  "quiz_q8a1": "A ridiculous pun or dad joke",
  "quiz_q8a2": "A camera and an eye for a good moment",
  "quiz_q8a3": "A guitar, piano, or song request",
  "quiz_q8a4": "A plan for keeping the kids happy",
  "quiz_q8a5": "A drink, snack, or warm welcome",
  "quiz_qword": "Question",
  "quiz_select_hint": "Choose any that fit — or none.",
  "rel_ali": "Goli's partner",
  "rel_alireza": "Mahzad's partner",
  "rel_ashraf": "Behdad, Bahareh & Baharak's mom",
  "rel_athena": "Hamid's partner",
  "rel_baharak": "Hannah's mom",
  "rel_bahareh": "Irene's mom",
  "rel_baka": "Markéta & Madla's grandmother · Daniel's mom",
  "rel_behdad": "Markéta's partner",
  "rel_chinnell": "Rafi's partner",
  "rel_danbern": "songwriter — the loft plays his own live recording",
  "rel_daniel": "Markéta & Madla's dad · Báka's son",
  "rel_elisabeth": "Madla & Robert's daughter",
  "rel_farhang": "Lauren's partner",
  "rel_felix": "Madla & Robert's son",
  "rel_goli": "Ali's partner",
  "rel_hamid": "Athena's partner",
  "rel_hannah": "Baharak & Payman's daughter",
  "rel_irene": "Bahareh's daughter",
  "rel_jay": "Spencer's partner",
  "rel_lauren": "Farhang's partner",
  "rel_madla": "Elisabeth & Felix's mom",
  "rel_mahzad": "Alireza's partner",
  "rel_marie": "Markéta & Madla's mom",
  "rel_marketa": "Behdad's partner",
  "rel_mohsen": "Behdad, Bahareh & Baharak's dad",
  "rel_oritshimoni": "songwriter — the loft plays her own live recording",
  "rel_patricia": "mother of two",
  "rel_patricia_daughter": "Patricia’s daughter",
  "rel_patricia_son": "Patricia’s son",
  "rel_payman": "Hannah's dad",
  "rel_rafi": "Chinnell's partner",
  "rel_robert": "Elisabeth & Felix's dad",
  "rel_spencer": "Jay's partner",
  "rel_whistler": "Farhang & Lauren's dog",
  "restart_confirm": "Start the loft over? You'll lose your progress.",
  "role_bartender": "bartender",
  "role_bdad": "Behdad's dad",
  "role_bestman": "best man",
  "role_bmom": "Behdad's mom",
  "role_bride": "the bride",
  "role_bril": "Behdad's brother-in-law",
  "role_business": "the businesswoman",
  "role_danbern": "Orit’s musical collaborator",
  "role_diva": "diva",
  "role_dj": "DJ",
  "role_fashion": "fashionista",
  "role_godson": "Behdad's godson",
  "role_godson_a": "grillmaster",
  "role_groom": "the groom",
  "role_hosts": "the hosts",
  "role_maid": "man of honour",
  "role_mc": "MC",
  "role_mdad": "Markéta's dad",
  "role_mgrandma": "Markéta's grandmother",
  "role_mmom": "Markéta's mom",
  "role_mnephew": "Markéta's nephew",
  "role_mniece": "Markéta's niece",
  "role_msisspouse": "Markéta's brother-in-law",
  "role_msister": "Markéta's sister",
  "role_nephew": "Behdad's nephew",
  "role_niece": "Behdad's niece",
  "role_officiant": "officiant",
  "role_oritshimoni": "Dan’s musical collaborator",
  "role_photographer": "photographer",
  "role_qa": "wedding boss",
  "role_sister": "Behdad's sister",
  "role_sisterinlaw": "Behdad's sister-in-law",
  "role_travelbuddy_f": "travel buddy",
  "role_travelbuddy_m": "travel buddy",
  "role_whistler": "WOOF",
  "room_balcony": "Balcony",
  "room_bar": "Bar",
  "room_bathroom": "Bathroom",
  "room_bedroom": "Bedroom",
  "room_cinema": "Cinema",
  "room_cuddly": "Cuddly-puddly",
  "room_dungeon": "Dungeon",
  "room_entrance": "Entrance",
  "room_garden": "Garden",
  "room_garden_party": "Garden / Party",
  "room_kitchen": "Kitchen",
  "room_kitchen_bar": "Kitchen / Bar",
  "room_office": "Office",
  "roster_empty": "The floor's empty — throw the party first.",
  "roster_none": "Nobody's in this room right now.",
  "roster_title": "who's here?",
  "rsvp_email_body": "who we are:\n\nwhich celebration (one or both — all welcome): Edmonton · May 1  /  Prague · July 10\n\nhow many of us:\n\nanything you should know — food, little ones, a song we have to hear:\n\ncan't wait,",
  "rsvp_email_subject": "we're coming 💌",
  "rsvp_exit_link": "You’ve seen the whole day — one thing left: tell us you’ll come ↓",
  "rsvp_gmail": "Open in Gmail",
  "rsvp_mail": "Email app",
  "rsvp_sub": "Small or far away, come to one or both — just let us know.",
  "rsvp_title": "RSVP",
  "rumi_lines": [
    [
      "I can do without everyone; without you, I cannot.",
      "My heart bears your mark; it cannot go anywhere else."
    ],
    [
      "My wine and my longing; my garden and my spring.",
      "My sleep and my peace; without you, I cannot."
    ],
    [
      "If you are not my beloved, all my world falls apart.",
      "My companion and comfort; without you, I cannot."
    ],
    [
      "You are my soul and my world; what need have I of soul or world?",
      "You are my living treasure; what care have I for gain or loss?"
    ],
    [
      "You are our light, our feast, our triumph crowned.",
      "Set our passion boiling, until our grapes become wine."
    ],
    [
      "I have come to lay down my head, to bear your love upon it.",
      "Even if you tell me no, I’ll break the reed and carry away its sugar."
    ],
    [
      "You move sweetly through my soul; sweetly you make me whole.",
      "O my faith and my believing; my sea filled with pearls."
    ]
  ],
  "sat_call_sub": "Saturday, same as always",
  "scene_ctx_escape": "Escape",
  "scene_ctx_solve": "Solve",
  "season_auto": "⛅ back to today",
  "season_autumn": "🍂 autumn",
  "season_canada": "🍁 canada day",
  "season_carodejnice": "🔥 witches' night",
  "season_chaharshanbe": "🔥 chaharshanbe suri",
  "season_holiday": "🎄 holiday season",
  "season_martin": "🍷 st. martin’s · remembrance day",
  "season_mehregan": "🌼 mehregan",
  "season_newyear": "🎆 new year",
  "season_nowruz": "🌱 nowruz",
  "season_pride": "🏳️‍🌈 pride",
  "season_sadeh": "🪵 sadeh",
  "season_sizdah": "🌳 sizdah bedar",
  "season_smoky": "🔥 smoky season",
  "season_solstice": "☀️ summer solstice",
  "season_spooky": "🎃 spooky season",
  "season_spring": "🌸 spring",
  "season_stedry": "🐟 xmas eve",
  "season_summer": "☀ summer",
  "season_svatojanska": "🔥 St John's Eve",
  "season_valentines": "💕 valentine's",
  "season_wedding": "💍 wedding week",
  "season_winter": "❄ winter",
  "season_xmas": "🦃 xmas day",
  "season_yalda": "🍉 shab-e yalda",
  "share_bd_a": "Happy Birthday, ",
  "share_bd_b": "!",
  "share_copied": "✓ Copied to clipboard — paste it anywhere",
  "share_copyfail": "Download it below",
  "share_download": "⬇ Download",
  "share_greet_canada": "Happy Canada Day!",
  "share_greet_carodejnice": "Happy Witches’ Night!",
  "share_greet_chaharshanbe": "Happy Chaharshanbe Suri!",
  "share_greet_holiday": "Happy Holidays!",
  "share_greet_martin": "St. Martin’s Day — the new wine is open",
  "share_greet_mehregan": "Happy Mehregan!",
  "share_greet_newyear": "Happy New Year!",
  "share_greet_nowruz": "Happy Nowruz!",
  "share_greet_pride": "Happy Pride!",
  "share_greet_sadeh": "A warm Sadeh — the mid-winter fire",
  "share_greet_solstice": "Still light out. Stay up with us.",
  "share_greet_spooky": "Happy Halloween!",
  "share_greet_stedry": "Merry Christmas Eve!",
  "share_greet_svatojanska": "Come jump the fire with us. Hold on tight.",
  "share_greet_valentines": "Happy Valentine’s Day!",
  "share_greet_wedding": "Save the Date!",
  "share_greet_xmas": "Merry Christmas!",
  "share_greet_yalda": "A good Yalda — the longest night",
  "share_mail": "✉ Email",
  "share_mail_bd_body": "Happy Birthday, {name}! Here’s a birthday postcard from our loft. Open Loft Day here:",
  "share_mail_bd_subj": "Happy Birthday, {name}! 🎉",
  "share_mail_clip": "(The birthday postcard is on your clipboard — paste it into this email to attach it.)",
  "share_title": "Save the date — share the loft",
  "shoot_doom": "Doom",
  "shoot_duke": "Duke",
  "shoot_mouse_coach": "Esc releases mouse",
  "shoot_q3": "Quake III",
  "sizdah_wish": "Knotting the <em>sabzeh</em> is a wish for a wedding. It worked.",
  "snake_setup_cancel": "Cancel",
  "snake_setup_fast": "fast",
  "snake_setup_players": "Number of players",
  "snake_setup_slow": "slow",
  "snake_setup_speed": "Game speed",
  "snake_setup_start": "Start game",
  "solitaire_help": "Help",
  "solitaire_help_copy": "Build down in alternating colours. Send A→K by suit home. Tap or drag; double-tap a card to send it home.",
  "solitaire_new": "New",
  "solitaire_play_again": "Deal again",
  "solitaire_ranks": [
    "Ace",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "Jack",
    "Queen",
    "King"
  ],
  "solitaire_redeal": "Redeal",
  "solitaire_suits": [
    "hearts",
    "diamonds",
    "clubs",
    "spades"
  ],
  "solitaire_win": "You won. Patience rewarded.",
  "tab_behdad": "behdad",
  "tab_ctx_close": "Close",
  "tab_ctx_reload": "Reload",
  "tab_harfbuzz": "harfbuzz",
  "tab_loft": "m ∞ b",
  "tab_marketa": "markéta",
  "tab_new": "new tab",
  "tagline": "We’re getting married<br><strong>Will you be there?</strong>",
  "tehran_place": "Tehran",
  "tempnav_down": "Colder",
  "tempnav_reset": "Hand the temperature back to Edmonton’s real weather",
  "tempnav_up": "Warmer",
  "tetris_again_key": "ENTER",
  "tetris_controls": "← → MOVE · ↑ ROTATE · SPACE DROP",
  "tetris_lines": "LINES",
  "tetris_next": "NEXT",
  "tetris_title": "BLOCK PARTY",
  "tetris_touch_again_key": "TAP",
  "tetris_touch_controls": "TAP ROTATE · SWIPE MOVE/DROP",
  "tip_abstract_butterfly": "Abstract 🌈🦋",
  "tip_behdad_pc": "behdad’s open-frame PC",
  "tip_carodejnice": "<em>Čarodějnice</em>, burning of the witches",
  "tip_chaharshanbe": "<em>Chaharshanbe Suri</em> (<bdi>چهارشنبه‌سوری</bdi>), the fire you leap",
  "tip_cokecooler": "the vintage-looking <em>Coca-Cola</em> cooler — really theirs, really rolls",
  "tip_fal": "the <em>Divan</em> of <em>Hafez</em> (<bdi>دیوان حافظ</bdi>) — open it for a <em>fāl</em>",
  "tip_haftsin": "<em>haft-sin</em> (<bdi>هفت‌سین</bdi>), the <em>nowruz</em> (<bdi>نوروز</bdi>) table",
  "tip_immortality": "Immortality",
  "tip_marketa_laptop": "Markéta’s laptop",
  "tip_marketa_phone": "Markéta’s phone",
  "tip_meal_martin": "<em>svatý Martin</em> — goose, red cabbage, <em>karlovarský knedlík</em>, and that year's <em>svatomartinské víno</em>",
  "tip_meal_nowruz": "<em>zerešk polo ba mahi</em> (<bdi>زرشک‌پلو با ماهی</bdi>), white rice with barberries and fish for the new year",
  "tip_meal_stedry": "<em>Štědrý večer</em> — fried carp and potato salad",
  "tip_meal_xmas": "Christmas dinner — a roast bird and cranberry, and not a fish in sight",
  "tip_meal_yalda": "<em>Shab-e Yalda</em> (<bdi>شب یلدا</bdi>) — watermelon, pomegranate and <em>ajil</em> for the longest night",
  "tip_mehregan": "<em>Mehregan</em> (<bdi>مهرگان</bdi>), the autumn <em>sofreh</em> — marigolds, <em>senjed</em>, pomegranate and rosewater on a violet cloth",
  "tip_mehregan_esfand": "<em>esfand</em> (<bdi>اسفند</bdi>) on the coals",
  "tip_mehregan_mirror": "the mirror, and the <em>sormedan</em> (<bdi>سرمه‌دان</bdi>) beside it",
  "tip_mehregan_noghl": "<em>noghl</em> (<bdi>نقل</bdi>) — sugared almonds, thrown by the handful",
  "tip_mondrian_butterfly": "Mondrian 🌈🦋",
  "tip_neon_butterfly": "Neon 🌈🦋",
  "tip_sadeh": "<em>Sadeh</em> (<bdi>سده</bdi>), the midwinter fire, fifty days and nights before <em>nowruz</em> — build it, feed it, gather around",
  "tip_sadeh_flint": "strike stone on stone",
  "tip_sadeh_wood": "brushwood, gathered for the night",
  "tip_sizdah": "<em>Sizdah Bedar</em> (<bdi>سیزده‌بدر</bdi>), <em>nowruz</em>'s thirteenth day, spent outdoors",
  "tip_smores": "s’mores by the fire",
  "tip_stainedglass_butterfly": "Stained-glass 🌈🦋",
  "tip_sundogs": "<em>sun dogs</em> — bright patches 22° from a low winter sun, made by ice crystals. A Prairie sight below −20 °C",
  "tip_svatojanska": "<em>Svatojánská noc</em>, St John's Eve — the fire you jump hand in hand",
  "trip_caption_acid": "Time to go for a bicycle ride.",
  "trip_caption_dmt": "I for one welcome the machine elves.",
  "trip_caption_froggies": "Reality melting point observed.",
  "trip_caption_iboga": "Somewhere behind you, the past is still loading.",
  "trip_caption_ketamine": "It’s just a game, within a game, within a game, ...",
  "trip_caption_molly": "Everyone is suddenly your favourite person.",
  "trip_caption_nitrous": "Hold that thought. It’s floating away.",
  "trip_caption_shrooms": "Fungal kingdom for the win.",
  "trip_no_mix_text": "Please don't mix. Enjoy responsibly. 🙃",
  "tt_by": "by",
  "tt_email_body": "Hi Markéta & Behdad!\n\nHere's a tattoo design from your loft studio — paste it now, it's on your clipboard (Ctrl/Cmd+V).\n\nSee you at the wedding!",
  "tt_email_subject": "A tattoo design 🖊️",
  "tt_new": "Draw your own",
  "tt_share": "Send",
  "typewriter_lines": [
    "Vows: first draft. Deleted.",
    "Note to self: fewer puns in the vows.",
    "Still faster than resolving a merge conflict.",
    "Dear diary, the loft smells like coffee again.",
    "Still no ligatures in this font."
  ],
  "typewriter_patience_line": "Still here? That's the whole vow, honestly.",
  "video_absent": "the film isn’t loaded yet — come back soon",
  "video_butterfly": "Rainbow Butterfly",
  "video_choose": "Choose a film",
  "video_downtown": "Downtown dance",
  "video_rose": "Mon amie la rose",
  "watch_loft": "▷ Trailer",
  "watch_skip": "□ Take over",
  "wd_anniversary": "anniversary",
  "wd_ribbon": "just married",
  "wd_wedding_day": "Wedding day"
};
