#!/usr/bin/env node
"use strict";

var lib = require("./lib");

var HARNESS = [
  '<pre id="__report">pending</pre>',
  '<script>(function(){',
  'var report={errors:[],steps:{}};function S(k,v){report.steps[k]=v;}function D(id,args){var r=window.loft.api.describe(id,args||{});return r.ok?r.value.availability:null;}function A(id,args){var d=D(id,args);return !!(d&&d.available);}function room(){var r=window.loft.api.query("room.current");return r.ok?r.value:null;}',
  'window.addEventListener("load",function(){setTimeout(function(){run().catch(function(e){window.__errs.push(String(e&&e.stack||e));}).then(function(){report.errors=window.__errs;document.getElementById("__report").textContent=JSON.stringify(report);});},350);});',
  'async function run(){',
  ' var api=window.loft.api,oldMax=window.__maxUnlocked;window.__maxUnlocked=function(){return 0;};window.__secondRound=false;',
  ' var lower=["bathroom","dungeon","cinema","bedroom","entrance"],fresh={phase:api.query("game.status").value.phase,count:api.capabilities().length,roomGo:A("room.go",{room:"balcony"}),car:A("car.dashboard.set",{open:true}),roadtripStart:A("roadtrip.start"),roadtripChooser:A("roadtrip.chooser.open"),roadtripRoute:A("roadtrip.route.start",{route:"banff"}),lower:lower.map(function(name){return [name,A(name+".set",{open:true})];}),runtime:{roster:A("roster.set",{open:true}),fixture:A("bathroom.fixture.activate",{fixture:"sink"}),camp:A("camping.fire.open"),pause:A("roadtrip.pause.set",{on:true}),moment:A("garden.moment.start",{moment:"toasts"}),call:A("call.video.start",{contact:"prague"}),flair:A("minigame.start",{game:"flair-catch"}),invaders:A("minigame.start",{game:"invaders"})},metadata:{fixture:D("bathroom.fixture.activate",{fixture:"sink"}),pause:D("roadtrip.pause.set",{on:true}),partyMusic:D("garden.music.next"),invaders:D("minigame.start",{game:"invaders"})}};',
  ' var combined={preview:{bathroom:D("bathroom.bubbles.preview",{on:true}),bedroom:D("bedroom.tic-tac-toe.preview",{on:true}),office:D("office.invaders.preview",{on:true})},party:{slow:D("garden.dance.request",{style:"slow"}),dj:D("garden.dj.set",{dj:"sina"})},car:{gear:D("car.gear.set",{gear:1})},cinema:D("cinema.playback.set",{playing:true})};',
  ' var oldPreviewBegin=window.__loftPreviewBegin;window.__loftPreviewBegin=undefined;combined.preview.noController=D("bathroom.bubbles.preview",{on:false});window.__loftPreviewBegin=oldPreviewBegin;',
  ' var oldMoment=window.__toastsOn;window.__toastsOn=true;combined.party.moment=D("garden.moment.start",{moment:"cake"});window.__toastsOn=oldMoment;',
  ' var oldPhotog=window.__photogSnap;window.__photogSnap=undefined;combined.photo=D("photo.take");window.__photogSnap=oldPhotog;',
  ' var oldPartySet=window.__setPartyMode,oldParty=window.__loftControllers.party;window.__setPartyMode=undefined;window.__loftControllers.party=undefined;combined.party.noController=D("garden.music.next");window.__setPartyMode=oldPartySet;window.__loftControllers.party=oldParty;',
  ' combined.controllers={};var oldPartyOn=window.__gardenPartyOn,oldSlowdance=window.__loftControllers.slowdance,oldRequestDance=window.__requestDance;window.__gardenPartyOn=true;window.__loftControllers.slowdance=undefined;combined.controllers.slow=D("garden.dance.request",{style:"slow"});window.__loftControllers.slowdance=oldSlowdance;window.__requestDance=undefined;combined.controllers.fast=D("garden.dance.request",{style:"fast"});window.__requestDance=oldRequestDance;window.__gardenPartyOn=oldPartyOn;var oldCocktail=window.__makeCocktail,oldMixer=window.__loftControllers.mixer;window.__makeCocktail=undefined;combined.controllers.cocktail=D("kitchen.cocktail.make",{drink:"negroni"});window.__makeCocktail=oldCocktail;window.__loftControllers.mixer=undefined;combined.controllers.mixer=D("kitchen.mixer.start",{recipe:"yale"});window.__loftControllers.mixer=oldMixer;var oldHudOpen=window.__openEntrancePorscheDriveHud;window.__openEntrancePorscheDriveHud=undefined;combined.controllers.roadtrip=D("roadtrip.start");combined.controllers.engine=D("car.engine.set",{on:true});window.__openEntrancePorscheDriveHud=oldHudOpen;',
  ' var oldPhoneState=window.__chatPhoneState;window.__chatPhoneState=function(){return {open:true,call:"madla"};};combined.call=D("call.video.start",{contact:"prague"});var oldLaptopCall=window.__laptopCall,oldMonitorApp=window.__openMonitorApp;window.__laptopCall=undefined;window.__openMonitorApp=undefined;combined.callNoController=D("call.video.start",{contact:"prague"});window.__openMonitorApp=oldMonitorApp;window.__chatPhoneState=oldPhoneState;combined.callWrongController=D("call.video.start",{contact:"prague"});window.__laptopCall=oldLaptopCall;',
  ' var oldFlairState=window.__flairState,oldAmbient=window.__ambientMaking;window.__flairState=function(){return {active:true};};window.__ambientMaking=function(){return true;};combined.minigame=D("minigame.start",{game:"flair-catch"});combined.bartender=D("kitchen.cocktail.make",{drink:"negroni"});window.__flairState=oldFlairState;window.__ambientMaking=oldAmbient;',
  ' var oldBathroomOpen=window.__openBathroomRoom,failedVersion=api.stateVersion;window.__openBathroomRoom=undefined;combined.routeUnavailable=D("bathroom.fixture.activate",{fixture:"sink"});window.__openBathroomRoom=function(){return false;};var failedRoute=await api.perform("bathroom.fixture.activate",{fixture:"sink"},{source:"test"});window.__openBathroomRoom=oldBathroomOpen;failedRoute.versionStable=api.stateVersion===failedVersion;failedRoute.room=room();',
  ' var routedEvents=[],unsubscribe=api.subscribe(function(event){routedEvents.push(event);}),fixtureHits=(window.__bathroomInteractionState().hits.sink||0),fixtureVersion=api.stateVersion;var routedFixture=await api.perform("bathroom.fixture.activate",{fixture:"sink"},{source:"test"});var fixtureRoute={result:routedFixture,room:room(),open:!!window.__bathroomRoomOpen,hits:(window.__bathroomInteractionState().hits.sink||0)-fixtureHits,version:api.stateVersion-fixtureVersion,events:routedEvents.splice(0)};',
  ' var upper=await api.perform("interaction.activate",{interaction:"garden.tensegrity"},{source:"upper-test"}),upperRoute={result:upper,room:room(),events:routedEvents.splice(0)};var lowerProp=await api.perform("bedroom.prop.activate",{prop:"wardrobe"},{source:"lower-test"}),bedroomState=window.__bedroomRoomState(),lowerRoute={result:lowerProp,room:room(),wardrobe:(bedroomState.props.filter(function(prop){return prop.id==="bedroom-wardrobe";})[0]||{}).state||"",events:routedEvents.splice(0)};',
  ' var missingCloserVersion=api.stateVersion,oldBedroomClose=window.__closeBedroomRoom;window.__closeBedroomRoom=undefined;var missingCloserDetail=D("bathroom.fixture.activate",{fixture:"towel"}),missingCloserResult=await api.perform("bathroom.fixture.activate",{fixture:"towel"},{source:"missing-closer"});var missingCloser={detail:missingCloserDetail,result:missingCloserResult,versionStable:api.stateVersion===missingCloserVersion,room:room(),stage:window.__currentStageName,bedroom:!!window.__bedroomRoomOpen,bathroom:!!window.__bathroomRoomOpen};window.__closeBedroomRoom=oldBedroomClose;',
  ' await api.perform("room.go",{room:"kitchen"},{source:"test"});routedEvents.splice(0);var concurrentVersion=api.stateVersion,firstDispatch={},towelHits=window.__bathroomInteractionState().hits.towel||0,oldBedroomProp=window.__activateBedroomProp;window.__activateBedroomProp=function(){var activated=oldBedroomProp.apply(this,arguments),state=window.__bedroomRoomState(),table=(state.props.filter(function(prop){return prop.id==="bedroom-left-table";})[0]||{}).state||"";firstDispatch={room:room(),table:table,activated:activated};return activated;};var concurrent=await Promise.all([api.perform("bedroom.prop.activate",{prop:"left-table"},{source:"concurrent-bedroom"}),api.perform("bathroom.fixture.activate",{fixture:"towel"},{source:"concurrent-bathroom"})]);window.__activateBedroomProp=oldBedroomProp;var concurrentRoute={results:concurrent,first:firstDispatch,room:room(),towelHits:(window.__bathroomInteractionState().hits.towel||0)-towelHits,version:api.stateVersion-concurrentVersion,events:routedEvents.splice(0)};',
  ' var conflictVersion=api.stateVersion,conflict=await Promise.all([api.perform("bedroom.tic-tac-toe.start",{},{source:"conflict-one"}),api.perform("bedroom.tic-tac-toe.start",{},{source:"conflict-two"})]),conflictRoute={results:conflict,room:room(),state:window.__bedroomTicTacToeState(),version:api.stateVersion-conflictVersion,events:routedEvents.splice(0)};await api.perform("bedroom.tic-tac-toe.dismiss",{},{source:"test"});routedEvents.splice(0);',
  ' await api.perform("room.go",{room:"kitchen"},{source:"test"});routedEvents.splice(0);var oldToasts=window.__loftControllers.toasts,longStarted=false,longRelease=null;window.__loftControllers.toasts=function(){longStarted=true;return new Promise(function(resolve){longRelease=resolve;});};var longPending=api.perform("garden.moment.start",{moment:"toasts"},{source:"long-route"});for(var longWait=0;!longStarted&&longWait<120;longWait++)await new Promise(function(resolve){setTimeout(resolve,20);});var follower=await api.perform("bathroom.fixture.activate",{fixture:"soap"},{source:"long-follower"}),followerBeforeRelease=!!longRelease;longRelease({done:true});var longResult=await longPending;window.__loftControllers.toasts=oldToasts;var longQueue={started:longStarted,follower:follower,followerRoom:room(),followerBeforeRelease:followerBeforeRelease,longResult:longResult,events:routedEvents.splice(0)};',
  ' await api.perform("room.go",{room:"kitchen"},{source:"test"});var rosterPartyOn=window.__gardenPartyOn;window.__gardenPartyOn=true;if(window.__syncRosterAvail)window.__syncRosterAvail();await api.perform("roster.set",{open:true},{source:"test"});routedEvents.splice(0);var rosterUpper=await api.perform("room.go",{room:"office"},{source:"roster-upper"}),rosterUpperState={result:rosterUpper,room:room(),open:!!(window.__rosterOpen&&window.__rosterOpen())};var rosterLower=await api.perform("room.go",{room:"bathroom"},{source:"roster-lower"}),rosterLowerState={result:rosterLower,room:room(),open:!!(window.__rosterOpen&&window.__rosterOpen())};var rosterSet=await api.perform("bedroom.set",{open:true},{source:"roster-set"}),rosterSetState={result:rosterSet,room:room(),open:!!(window.__rosterOpen&&window.__rosterOpen())};routedEvents.splice(0);var rosterRouteResult=await api.perform("interaction.activate",{interaction:"garden.tensegrity"},{source:"roster-route"}),rosterRoute={upper:rosterUpperState,lower:rosterLowerState,setter:rosterSetState,result:rosterRouteResult,room:room(),open:!!(window.__rosterOpen&&window.__rosterOpen()),events:routedEvents.splice(0)};await api.perform("roster.set",{open:false},{source:"test"});window.__gardenPartyOn=rosterPartyOn;if(window.__syncRosterAvail)window.__syncRosterAvail();routedEvents.splice(0);unsubscribe();',
  ' var dashboard=await api.perform("car.dashboard.set",{open:true},{source:"test"}),afterDashboard={room:room(),phase:api.query("game.status").value.phase,secondRound:!!window.__secondRound};var visibleHudOpener=window.__openEntrancePorscheDriveHud;window.__openEntrancePorscheDriveHud=undefined;afterDashboard.engineWithoutOpener=A("car.engine.set",{on:false});afterDashboard.dashboardWithoutOpener=A("car.dashboard.set",{open:true});window.__openEntrancePorscheDriveHud=visibleHudOpener;',
  ' await api.perform("car.transmission.set",{mode:"manual"},{source:"test"});await api.perform("car.dashboard.set",{open:false},{source:"test"});combined.car.range=D("car.range.set",{range:"D"});await api.perform("car.dashboard.set",{open:true},{source:"test"});await api.perform("car.transmission.set",{mode:"auto"},{source:"test"});',
  ' var chooser=await api.perform("roadtrip.chooser.open",{},{source:"test"}),chooserOpen={opened:chooser.ok&&chooser.value.opened,state:api.query("roadtrip.status").value};document.getElementById("entrance-roadtrip-route-banff").dispatchEvent(new MouseEvent("click",{bubbles:true,cancelable:true}));var chooserStarted={active:api.query("roadtrip.status").value.active,route:api.query("roadtrip.status").value.route};var chooserExit=await api.perform("roadtrip.exit",{}, {source:"test"});',
  ' var start=await api.perform("roadtrip.route.start",{route:"abraham"},{source:"test"}),during={active:api.query("roadtrip.status").value.active,route:api.query("roadtrip.status").value.route,pause:A("roadtrip.pause.set",{on:true}),startAgain:A("roadtrip.start"),startAgainDetail:D("roadtrip.start"),phase:api.query("game.status").value.phase};',
  ' var oldRoadtripStart=window.__entranceRoadtripApiStart;window.__entranceRoadtripApiStart=undefined;during.startNoController=D("roadtrip.start");window.__entranceRoadtripApiStart=oldRoadtripStart;',
  ' var oldRoadtripExit=window.__exitEntranceRoadtrip;window.__exitEntranceRoadtrip=undefined;during.startNoExit=D("roadtrip.start");window.__exitEntranceRoadtrip=oldRoadtripExit;',
  ' var exit=await api.perform("roadtrip.exit",{}, {source:"test"}),afterRoadtrip={active:api.query("roadtrip.status").value.active,pause:A("roadtrip.pause.set",{on:true}),camp:A("camping.fire.open"),phase:api.query("game.status").value.phase,secondRound:!!window.__secondRound};',
  ' await api.perform("room.go",{room:"kitchen"},{source:"test"});var kitchen={room:room(),cocktail:A("kitchen.cocktail.make",{drink:"negroni"}),mixer:A("kitchen.mixer.start",{recipe:"yale"}),flair:A("minigame.start",{game:"flair-catch"}),invaders:A("minigame.start",{game:"invaders"})};',
  ' await api.perform("room.go",{room:"garden"},{source:"test"});await api.perform("garden.set",{on:true},{source:"test"});window.__secondRound=false;var garden={room:room(),phase:api.query("game.status").value.phase,roster:A("roster.set",{open:true}),moment:A("garden.moment.start",{moment:"toasts"}),kids:A("scene.activity.start",{activity:"kids-chase"}),rainbow:A("scene.activity.start",{activity:"rainbow"}),dj:A("garden.dj.set",{dj:"danesh"}),slow:A("garden.dance.request",{style:"slow"})};',
  ' await api.perform("room.go",{room:"office"},{source:"test"});window.__secondRound=false;var office={room:room(),phase:api.query("game.status").value.phase,call:A("call.video.start",{contact:"prague"}),invaders:A("minigame.start",{game:"invaders"}),flair:A("minigame.start",{game:"flair-catch"}),dj:A("garden.dj.set",{dj:"sina"}),slow:A("garden.dance.request",{style:"slow"})};',
  ' await api.perform("garden.set",{on:false},{source:"test"});window.__maxUnlocked=oldMax;S("audit",{fresh:fresh,combined:combined,failedRoute:failedRoute,fixtureRoute:fixtureRoute,upperRoute:upperRoute,lowerRoute:lowerRoute,missingCloser:missingCloser,concurrentRoute:concurrentRoute,conflictRoute:conflictRoute,longQueue:longQueue,rosterRoute:rosterRoute,dashboard:dashboard,afterDashboard:afterDashboard,chooser:chooser,chooserOpen:chooserOpen,chooserStarted:chooserStarted,chooserExit:chooserExit,start:start,during:during,exit:exit,afterRoadtrip:afterRoadtrip,kitchen:kitchen,garden:garden,office:office});',
  '}',
  '})();</script>'
].join("\n");

var failures = 0;
function check(ok, msg, detail) {
  if (ok) console.log("  ✓ " + msg);
  else { failures++; console.log("  ✗ " + msg + (detail ? "   [" + JSON.stringify(detail) + "]" : "")); }
}

console.log("loft-day.html typed API story-gate audit:");
var result = lib.runPageSync("loft-day.html", HARNESS, 23000, { patchRaf: true });
if (!result) { console.log("  ✗ harness produced no report"); process.exit(1); }
var a = result.steps.audit || {}, fresh = a.fresh || {};
var combined = a.combined || {};
function compound(detail, parts) {
  return detail && !detail.available && !detail.remedy && parts.every(function (part) { return detail.reason.indexOf(part) >= 0; });
}
check(result.errors.length === 0, "no uncaught page errors", result.errors);
check(fresh.count >= 195, "the catalogue contains the audited 195-capability baseline and any later extensions", fresh.count);
check(fresh.phase === 1 && fresh.roomGo && fresh.car && fresh.roadtripStart && fresh.roadtripChooser && fresh.roadtripRoute && (fresh.lower || []).every(function (entry) { return entry[1]; }), "navigation, every lower room, the car, and every Road Trip entry are available in a fresh Phase 1 game", fresh);
check(fresh.runtime && fresh.runtime.roster && fresh.runtime.fixture && !fresh.runtime.camp && !fresh.runtime.pause && fresh.runtime.moment && fresh.runtime.call && fresh.runtime.flair && fresh.runtime.invaders, "fresh Phase 1 exposes routable room actions while retaining real lifecycle gates", fresh.runtime);
check(fresh.metadata && fresh.metadata.fixture.available && !fresh.metadata.fixture.reason && !fresh.metadata.fixture.remedy && fresh.metadata.partyMusic.reason === "The Garden Party is not running." && fresh.metadata.partyMusic.remedy.id === "garden.set" && fresh.metadata.partyMusic.remedy.args.on === true && fresh.metadata.invaders.available && !fresh.metadata.invaders.reason && !fresh.metadata.invaders.remedy, "discovery stays side-effect-free and omits artificial room blockers", fresh.metadata);
check(fresh.metadata && fresh.metadata.pause.reason === "No Road Trip is active." && !Object.prototype.hasOwnProperty.call(fresh.metadata.pause, "remedy"), "gates with no honest single-step remedy publish a reason without inventing one", fresh.metadata && fresh.metadata.pause);
check(combined.preview && [combined.preview.bathroom,combined.preview.bedroom,combined.preview.office].every(function(detail){return detail && !detail.available && detail.reason === "No preview session is active." && detail.remedy && detail.remedy.id === "session.preview.begin";}), "preview discovery offers its session remedy without treating the current room as a blocker", combined.preview);
check(combined.preview && compound(combined.preview.noController, ["No preview session is active."]), "preview begin is not advertised when its controller cannot establish the required session", combined.preview && combined.preview.noController);
check(combined.party && combined.party.slow.reason === "The Garden Party is not running." && combined.party.slow.remedy.id === "garden.set" && combined.party.dj.reason === "The Garden Party is not running." && combined.party.dj.remedy.id === "garden.set" && combined.party.moment.reason === "Another Garden Party moment is still running." && !combined.party.moment.remedy, "Party discovery retains real Party and active-moment blockers without a room convention", combined.party);
check(combined.party && compound(combined.party.noController, ["The Garden Party is not running."]), "Party start is not advertised when its controller cannot clear the gate", combined.party && combined.party.noController);
check(combined.controllers && combined.controllers.slow.reason === "The requested dance controller is not ready." && combined.controllers.fast.reason === "The requested dance controller is not ready." && combined.controllers.cocktail.reason === "The cocktail controller is not ready." && combined.controllers.mixer.reason === "The mixer controller is not ready." && combined.controllers.roadtrip.reason === "The Road Trip dashboard surface cannot be opened." && combined.controllers.engine.reason === "The car dashboard surface cannot be opened." && Object.keys(combined.controllers).every(function(key){return !combined.controllers[key].remedy;}), "converted room actions keep their argument-specific controller and route availability exact", combined.controllers);
check(compound(combined.photo, ["The Garden Party is not running.", "The photographer is not ready."]) && combined.call.reason === "Another call is active or ringing." && combined.call.remedy.id === "call.hangup" && compound(combined.callNoController, ["Another call is active or ringing.", "The video-call controller is not ready."]) && combined.callWrongController.reason === "The video-call controller is not ready." && !combined.callWrongController.remedy, "missing or contact-mismatched controllers cannot leave Party or call remedies that clear only another blocker", { photo: combined.photo, call: combined.call, callNoController: combined.callNoController, callWrongController: combined.callWrongController });
check(combined.minigame.reason === "A minigame is already running." && combined.minigame.remedy.id === "minigame.stop" && compound(combined.bartender, ["A minigame is running.", "The Kitchen bar is already serving or mixing a drink."]), "minigame and bartender metadata retains every independent runtime conflict", { minigame: combined.minigame, bartender: combined.bartender });
check(combined.car && combined.car.gear.reason === "The manual transmission is not selected." && combined.car.gear.remedy.id === "car.transmission.set" && combined.car.range.reason === "The automatic transmission is not selected." && combined.car.range.remedy.id === "car.transmission.set" && combined.cinema.reason === "No Cinema film is loaded." && !combined.cinema.remedy, "transmission and media prerequisites remain exact without dashboard or room blockers", { car: combined.car, cinema: combined.cinema });
check(combined.routeUnavailable && !combined.routeUnavailable.available && combined.routeUnavailable.reason === "The Bathroom surface cannot be opened." && !combined.routeUnavailable.remedy, "discovery reports a missing canonical room route without side effects or a fabricated remedy", combined.routeUnavailable);
check(a.failedRoute && !a.failedRoute.ok && a.failedRoute.code === "NOT_AVAILABLE" && a.failedRoute.message === "The Bathroom surface could not be opened." && a.failedRoute.availability && a.failedRoute.availability.reason === a.failedRoute.message && a.failedRoute.versionStable && a.failedRoute.room === "kitchen", "an unexpected surface-routing refusal returns a structured exact NOT_AVAILABLE result without mutation", a.failedRoute);
check(a.fixtureRoute && a.fixtureRoute.result && a.fixtureRoute.result.ok && a.fixtureRoute.result.value.activated && a.fixtureRoute.room === "bathroom" && a.fixtureRoute.open && a.fixtureRoute.hits === 1 && a.fixtureRoute.version === 1 && a.fixtureRoute.events.length === 1 && a.fixtureRoute.events[0].id === "bathroom.fixture.activate" && a.fixtureRoute.events[0].source === "test", "fresh-Kitchen Bathroom fixture invocation opens the visible room, uses its owner, and records one typed action", a.fixtureRoute);
check(a.upperRoute && a.upperRoute.result && a.upperRoute.result.ok && a.upperRoute.room === "garden" && a.upperRoute.events.length === 1 && a.upperRoute.events[0].id === "interaction.activate" && a.upperRoute.events[0].source === "upper-test", "a routed upper-room interaction settles and retains typed action identity", a.upperRoute);
check(a.lowerRoute && a.lowerRoute.result && a.lowerRoute.result.ok && a.lowerRoute.result.value.activated && a.lowerRoute.room === "bedroom" && /tidied/.test(a.lowerRoute.wardrobe) && a.lowerRoute.events.length === 1 && a.lowerRoute.events[0].id === "bedroom.prop.activate" && a.lowerRoute.events[0].source === "lower-test", "a second lower-room prop routes visibly through its existing owner", a.lowerRoute);
check(a.missingCloser && a.missingCloser.detail && !a.missingCloser.detail.available && a.missingCloser.detail.reason === "The Bathroom surface cannot be opened because the Bedroom surface cannot be closed." && !a.missingCloser.detail.remedy && a.missingCloser.result && !a.missingCloser.result.ok && a.missingCloser.result.code === "NOT_AVAILABLE" && a.missingCloser.versionStable && a.missingCloser.room === "bedroom" && a.missingCloser.stage === "office" && a.missingCloser.bedroom && !a.missingCloser.bathroom, "a missing active lower-room closer blocks discovery and invocation before any partial pan or second surface", a.missingCloser);
var concurrentTyped = a.concurrentRoute && a.concurrentRoute.events.filter(function(event){return /^concurrent-/.test(event.source);});
check(a.concurrentRoute && a.concurrentRoute.results.every(function(entry){return entry&&entry.ok&&entry.value&&entry.value.activated;}) && a.concurrentRoute.first && a.concurrentRoute.first.activated && a.concurrentRoute.first.room === "bedroom" && /open/.test(a.concurrentRoute.first.table) && a.concurrentRoute.room === "bathroom" && a.concurrentRoute.towelHits === 1 && a.concurrentRoute.version >= 2 && concurrentTyped.length === 2 && concurrentTyped[0].id === "bedroom.prop.activate" && concurrentTyped[0].source === "concurrent-bedroom" && concurrentTyped[1].id === "bathroom.fixture.activate" && concurrentTyped[1].source === "concurrent-bathroom", "concurrent routed actions invoke both owners in order and retain distinct state identities", a.concurrentRoute);
var conflictTyped = a.conflictRoute && a.conflictRoute.events.filter(function(event){return /^conflict-/.test(event.source);});
check(a.conflictRoute && a.conflictRoute.results[0] && a.conflictRoute.results[0].ok && a.conflictRoute.results[0].value.started && a.conflictRoute.results[1] && !a.conflictRoute.results[1].ok && a.conflictRoute.results[1].code === "NOT_AVAILABLE" && /already running/.test(a.conflictRoute.results[1].message) && a.conflictRoute.room === "bedroom" && a.conflictRoute.state && a.conflictRoute.state.phase !== "idle" && a.conflictRoute.version === 1 && conflictTyped.length === 1 && conflictTyped[0].id === "bedroom.tic-tac-toe.start" && conflictTyped[0].source === "conflict-one", "queued conflicting actions revalidate after routing and dispatch only the first owner once", a.conflictRoute);
check(a.longQueue && a.longQueue.started && a.longQueue.followerBeforeRelease && a.longQueue.follower && a.longQueue.follower.ok && a.longQueue.follower.value.activated && a.longQueue.followerRoom === "bathroom" && a.longQueue.longResult && a.longQueue.longResult.ok, "a routed owner's long lifecycle remains awaitable without holding the route-dispatch queue", a.longQueue);
check(a.rosterRoute && a.rosterRoute.upper.result.ok && a.rosterRoute.upper.room === "office" && a.rosterRoute.upper.open && a.rosterRoute.lower.result.ok && a.rosterRoute.lower.result.value.room === "bathroom" && a.rosterRoute.lower.room === "bathroom" && a.rosterRoute.lower.open && a.rosterRoute.setter.result.ok && a.rosterRoute.setter.result.value.open && a.rosterRoute.setter.room === "bedroom" && a.rosterRoute.setter.open && a.rosterRoute.result && a.rosterRoute.result.ok && a.rosterRoute.room === "garden" && a.rosterRoute.open && a.rosterRoute.events.some(function(event){return event.id === "interaction.activate" && event.source === "roster-route";}), "room.go, lower-room setters, and routed actions use canonical roster-preserving navigation", a.rosterRoute);
check(a.dashboard && a.dashboard.ok && a.afterDashboard && a.afterDashboard.room === "entrance" && a.afterDashboard.phase === 1 && !a.afterDashboard.secondRound && a.afterDashboard.engineWithoutOpener && a.afterDashboard.dashboardWithoutOpener, "opening the car performs its explicit Phase-1 navigation and an already-visible HUD needs no opener", a.afterDashboard);
check(a.chooser && a.chooser.ok && a.chooserOpen && a.chooserOpen.opened && a.chooserOpen.state.routeChooserOpen && a.chooserStarted && a.chooserStarted.active && a.chooserStarted.route === "banff" && a.chooserExit && a.chooserExit.ok, "the visible route chooser works in Phase 1 through its normal route button", { chooser: a.chooser, opened: a.chooserOpen, started: a.chooserStarted });
check(a.start && a.start.ok && a.start.value.started && a.during && a.during.active && a.during.route === "abraham" && a.during.pause && !a.during.startAgain && a.during.phase === 1, "a direct selected Road Trip starts in Phase 1 and then enforces active-trip exclusivity", { start: a.start, during: a.during });
check(a.during && a.during.startAgainDetail && a.during.startAgainDetail.reason === "A Road Trip is already active." && a.during.startAgainDetail.remedy.id === "roadtrip.exit", "runtime exclusivity updates its reason and remedy when a Road Trip starts", a.during && a.during.startAgainDetail);
check(a.during && compound(a.during.startNoController, ["A Road Trip is already active.", "The Road Trip controller is not ready."]), "Road Trip exit is not advertised when the start controller would remain unavailable", a.during && a.during.startNoController);
check(a.during && compound(a.during.startNoExit, ["A Road Trip is already active."]), "Road Trip exit is not advertised when the exit controller cannot clear the active trip", a.during && a.during.startNoExit);
check(a.exit && a.exit.ok && a.afterRoadtrip && !a.afterRoadtrip.active && !a.afterRoadtrip.pause && !a.afterRoadtrip.camp && a.afterRoadtrip.phase === 1 && !a.afterRoadtrip.secondRound, "Road Trip exits cleanly and leaves finite/lifecycle gates intact in Phase 1", { exit: a.exit, after: a.afterRoadtrip });
check(a.kitchen && a.kitchen.room === "kitchen" && a.kitchen.cocktail && a.kitchen.mixer && a.kitchen.flair && a.kitchen.invaders, "Kitchen discovery exposes both local and routable actions", a.kitchen);
check(a.garden && a.garden.room === "garden" && a.garden.phase === 1 && a.garden.roster && a.garden.moment && a.garden.kids && a.garden.rainbow && a.garden.dj && a.garden.slow, "live Party actions ignore story phase and routable activities ignore the inspected room", a.garden);
check(a.office && a.office.room === "office" && a.office.phase === 1 && a.office.call && a.office.invaders && a.office.flair && a.office.dj && a.office.slow, "Office discovery remains side-effect-free while reporting routable actions available", a.office);

console.log("");
if (failures) { console.log(failures + " check(s) failed."); process.exit(1); }
console.log("All API story-gate checks passed.");
