#!/usr/bin/env node
"use strict";

var lib = require("./lib");

var HARNESS = [
  '<pre id="__report">pending</pre>',
  '<script>(function(){',
  'var report={errors:[],steps:{}};function S(k,v){report.steps[k]=v;}',
  'window.addEventListener("load",function(){setTimeout(function(){run().catch(function(e){window.__errs.push(String(e&&e.stack||e));}).then(function(){report.errors=window.__errs;document.getElementById("__report").textContent=JSON.stringify(report);});},350);});',
  'async function run(){',
  ' var api=window.loft.api,oldMax=window.__maxUnlocked;window.__maxUnlocked=function(){return 4;};window.__secondRound=true;',
  ' var caps=api.capabilities(),groups=api.groups(),rooms=api.query("room.list"),game=api.query("game.status"),manifest=window.__chatApiManifest();',
  ' function D(id,args){var r=api.describe(id,args);return r.ok?r.value:null;}',
  ' var schemas={environment:D("environment.daylight.set",{on:null}),transmission:D("car.transmission.set",{mode:"auto"}),route:D("roadtrip.route.start",{route:"banff"}),stars:D("camping.stargazing.trace",{constellation:"ursa-major",star:3}),trip:D("trip.start",{variant:"molly"}),fishu:D("cuddly.fishu.speak",{}),activity:D("scene.activity.start",{activity:"rainbow"}),caption:D("caption.show",{text:"hello"}),garden:D("garden.set",{on:true}),kitchen:D("kitchen.coffee.make",{}),kill:D("app.kill",{app:"life",device:"monitor"}),presentation:D("presentation.card.show",{card:"title"}),previewBubble:D("bathroom.bubbles.preview",{on:false}),previewEnd:D("session.preview.end",{disposition:"entry"}),trailerStop:D("trailer.stop",{disposition:"entry"})};',
  ' var strictNames=["laser","party","guests","roster","fullscreen","smoker","bbq","smores","snowman","leafpile","blossomplay","sprinkler","kidsAsleep","smokerlid","phone","laptop","computer","cat","dog","irene","mouses","porsche","audio"];',
  ' var strict=strictNames.map(function(name){var value=window[name],rejected=false,callable=true;try{value.set(null);}catch(e){rejected=e instanceof TypeError;}try{value();}catch(e){callable=false;}return {name:name,type:typeof value,frozen:Object.isFrozen(value),status:typeof value.status==="function",set:typeof value.set==="function",rejected:rejected,callable:callable};});',
  ' var envNames=["blacklight","daylight","storm","rain","snow","overcast","wildfires","aurora","twilight"],env=[];',
  ' for(var i=0;i<envNames.length;i++){var name=envNames[i],value=window[name],before=value.mode(),on=value.set(true),onMode=value.mode(),off=value.set(false),offMode=value.mode(),auto=value.set(null),autoMode=value.mode(),stringRejected=false;try{value.set("auto");}catch(e){stringRejected=e instanceof TypeError;}env.push({name:name,frozen:Object.isFrozen(value),on:on,onMode:onMode,off:off,offMode:offMode,auto:auto,autoMode:autoMode,stringRejected:stringRejected,status:typeof value.status()==="boolean"});}',
  ' var pans=0,oldGo=window.goToStage;window.goToStage=function(){pans++;return oldGo.apply(this,arguments);};var partyPromise=window.loft.garden.set(true),partyImmediate=!!window.__gardenPartyOn;await partyPromise;await window.loft.garden.set(false);await window.loft.environment.daylight.set(null);window.goToStage=oldGo;',
  ' var navBar=await api.perform("room.go",{room:"bar"},{source:"test"}),barRoom=api.query("room.current"),navParty=await api.perform("room.go",{room:"party"},{source:"test"}),partyRoom=api.query("room.current");',
  ' var invalidAuto=await api.perform("environment.daylight.set",{on:"auto"},{source:"test"}),invalidGear=await api.perform("car.transmission.set",{mode:"automatic"},{source:"test"});',
  ' var help={all:window.help(),loft:window.help(window.loft),api:window.help(window.loft.api),apiInfo:window.help(window.loft.api.info),fixture:window.help(window.loft.bathroom.fixture.activate),partyMusic:window.help(window.loft.garden.music.next),kitchen:window.help(window.loft.kitchen),party:window.help(window.loft.party),weather:window.help(window.loft.weather),rain:window.help(window.loft.weather.rain),rainSet:window.help(window.loft.weather.rain.set),chest:window.help(window.loft.cuddly.chest),presentation:window.help(window.loft.presentation.card.show),string:window.help("kitchen"),legacy:window.help("dance")};',
  ' var localeHelp={ok:false},oldLocaleCompare=String.prototype.localeCompare,oldCapabilities=api.capabilities;try{String.prototype.localeCompare=function(){throw new Error("typed help consulted localeCompare");};localeHelp.rain=window.help(window.loft.weather.rain);api.capabilities=function(options){return oldCapabilities.call(api,options).map(function(cap){var copy=Object.assign({},cap);if(cap.id==="api.capabilities")copy.group="Alpha";else if(cap.id==="api.info")copy.group="Zulu";return copy;});};localeHelp.groupTie=window.help();localeHelp.ok=localeHelp.rain===help.rain;}catch(error){localeHelp.error=String(error&&error.message||error);}finally{api.capabilities=oldCapabilities;String.prototype.localeCompare=oldLocaleCompare;}',
  ' window.__openDropTerm();var consoleIn=document.getElementById("dropterm-in"),consoleOut=document.getElementById("dropterm-out");function consoleHelp(command){consoleOut.replaceChildren();consoleIn.focus();consoleIn.value=command;consoleIn.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true,cancelable:true}));return consoleOut.textContent;}var consoleHelpText={bare:consoleHelp("help"),call:consoleHelp("help()")};window.__closeDropTerm();',
  ' S("api",{caps:caps,groups:groups,rooms:rooms,game:game,manifest:manifest,schemas:schemas,strict:strict,env:env,aliases:{bar:window.loft.bar===window.loft.kitchen,party:window.loft.party===window.loft.garden,roomBar:barRoom,roomParty:partyRoom,navBar:navBar,navParty:navParty},namespace:{partyImmediate:partyImmediate,pans:pans,chest:typeof window.loft.cuddly.chest.set,apiInfo:typeof window.loft.api.info,apiInfoResult:window.loft.api.info(),oldChest:typeof window.chest,oldPirate:typeof window.piratebox,oldStatus:typeof window.loftstatus},invalid:{auto:invalidAuto,gear:invalidGear},help:help,localeHelp:localeHelp,consoleHelp:consoleHelpText});',
  ' window.__maxUnlocked=oldMax;',
  '}',
  '})();</script>'
].join("\n");

var failures = 0;
function check(ok, msg, detail) {
  if (ok) console.log("  ✓ " + msg);
  else { failures++; console.log("  ✗ " + msg + (detail ? "   [" + JSON.stringify(detail) + "]" : "")); }
}

console.log("loft-day.html API v4 surface:");
var result = lib.runPageSync("loft-day.html", HARNESS, 5200, { patchRaf: true });
if (!result) { console.log("  ✗ harness produced no report"); process.exit(1); }
var s = result.steps.api || {}, caps = s.caps || [], ids = caps.map(function (cap) { return cap.id; }), rooms = s.rooms && s.rooms.value || [];
check(result.errors.length === 0, "no uncaught page errors", result.errors);
check(caps.length >= 130 && caps.every(function (cap) {
  return cap.id && cap.group && (cap.kind === "query" || cap.kind === "action") && Array.isArray(cap.argOrder) &&
    (cap.completion === "instant" || cap.completion === "finite") && cap.description && cap.returns && cap.returns.type === "envelope" &&
    cap.availability && typeof cap.availability.available === "boolean" && cap.available === cap.availability.available;
}), "the API exposes a stable, fully described grouped typed catalogue", { count: caps.length });
check(caps.filter(function (cap) { return !cap.available; }).every(function (cap) { return typeof cap.availability.reason === "string" && cap.availability.reason.length > 0; }), "every currently unavailable catalogue row gives an exact reason", caps.filter(function (cap) { return !cap.available && !(cap.availability && cap.availability.reason); }).map(function (cap) { return cap.id; }));
check(caps.filter(function (cap) { return cap.availability.remedy; }).every(function (cap) { var remedy = cap.availability.remedy, target = caps.find(function (entry) { return entry.id === remedy.id; }); return target && target.kind === "action" && remedy.args && typeof remedy.args === "object" && !Array.isArray(remedy.args); }), "every advertised remedy names a registered typed action with object arguments", caps.filter(function (cap) { return cap.availability.remedy; }).map(function (cap) { return { id: cap.id, remedy: cap.availability.remedy }; }));
check(Array.isArray(s.groups) && s.groups.length >= 15 && s.groups.join("\0") === s.groups.slice().sort().join("\0") && s.groups.includes("Entrance / Car") && s.groups.includes("Road Trip") && s.groups.includes("Camping") && s.groups.includes("Presentation / Trailer"), "capability groups are stable, sorted, and cover the terminal act plus bounded presentation layer", s.groups);
check(rooms.length === 10 && rooms[0].id === "kitchen" && rooms[5].id === "bathroom" && rooms[9].id === "entrance" && rooms[0].aliases.includes("bar") && rooms[1].aliases.includes("party"), "room catalogue covers both floors and canonical aliases", rooms);
check(s.game && s.game.ok && s.game.value.unlocked_rooms.length === 10 && s.game.value.unlocked_rooms.includes("entrance"), "game status reports all unlocked upper and lower rooms", s.game);
check(["app.kill","app.python.status","caption.show","cuddly.chest.status","cuddly.chest.set","car.status","car.control.set","roadtrip.status","roadtrip.preview.show","camping.fire.place","camping.stew.select","camping.stargazing.trace","camping.finale.advance","session.preview.begin","session.preview.end","trailer.status","trailer.play","trailer.stop","presentation.reduced.status","presentation.card.show","presentation.card.hide","presentation.caption.show","presentation.chapter.show","presentation.cut","presentation.point","game.reset"].every(function (id) { return ids.includes(id); }), "room-owned controls, Python readiness, app Kill, bounded presentation, trailer, terminal act, and preview lifecycle are typed", ids.length);
check(s.schemas && s.schemas.environment.args.on.nullable && s.schemas.environment.argOrder.join(",") === "on" && s.schemas.environment.completion === "instant" && s.schemas.transmission.args.mode.enum.join(",") === "auto,manual" && s.schemas.route.args.route.enum.join(",") === "calgary,banff,abraham" && s.schemas.trip.completion === "finite" && s.schemas.fishu.completion === "finite" && s.schemas.activity.completion === "finite" && s.schemas.caption.completion === "instant" && s.schemas.caption.argOrder.join(",") === "text" && s.schemas.kill.completion === "finite" && s.schemas.kill.args.device.enum.join(",") === "current,phone,monitor" && s.schemas.presentation.args.card.enum.join(",") === "title,final" && !s.schemas.presentation.available && s.schemas.previewEnd.args.disposition.enum.join(",") === "restore,fresh,entry" && s.schemas.trailerStop.args.disposition.enum.join(",") === "restore,fresh,entry", "argument order, nullable ownership, entry disposition, presentation gates, enums, and lifecycle completion are mechanically discoverable", s.schemas);
check(s.schemas && s.schemas.presentation.availability && s.schemas.presentation.availability.reason === "The Trailer is not playing." && !s.schemas.presentation.availability.remedy && s.schemas.previewEnd.availability.reason === "No preview session is active." && !s.schemas.previewEnd.availability.remedy && s.schemas.previewBubble.availability.remedy.id === "session.preview.begin", "describe() exposes exact unavailable reasons and only honest typed remedies", { presentation: s.schemas && s.schemas.presentation, previewEnd: s.schemas && s.schemas.previewEnd, previewBubble: s.schemas && s.schemas.previewBubble });
check(s.schemas.garden.aliases.includes("party.set") && s.schemas.kitchen.aliases.includes("bar.coffee.make") && caps.every(function (cap) { return Array.isArray(cap.aliases); }), "canonical room aliases are mechanically discoverable without duplicate capability ids", { garden: s.schemas.garden.aliases, kitchen: s.schemas.kitchen.aliases });
check((s.strict || []).every(function (entry) { return entry.type === "object" && entry.frozen && entry.status && entry.set && entry.rejected && !entry.callable; }), "non-environment boolean controls are strict frozen status/set objects", s.strict);
check((s.env || []).length === 9 && s.env.every(function (entry) { return entry.frozen && entry.on === true && entry.onMode === "on" && entry.off === false && entry.offMode === "off" && entry.autoMode === "auto" && entry.stringRejected && entry.status; }), "environment controls accept only true, false, or null and report effective state plus mode", s.env);
check(s.aliases && s.aliases.bar && s.aliases.party && s.aliases.roomBar.value === "kitchen" && s.aliases.roomParty.value === "garden", "bar and party are identity aliases while room results stay canonical", s.aliases);
check(s.namespace && s.namespace.partyImmediate && s.namespace.pans === 0 && s.namespace.chest === "function" && s.namespace.oldChest === "undefined" && s.namespace.oldPirate === "undefined" && s.namespace.oldStatus === "undefined", "namespace setters mutate immediately without publishing compatibility globals", s.namespace);
check(s.namespace && s.namespace.apiInfo === "function" && s.namespace.apiInfoResult.ok && typeof s.namespace.apiInfoResult.value.stateVersion === "number", "non-conflicting API capabilities remain callable from the JavaScript namespace tree", s.namespace);
check(s.invalid && !s.invalid.auto.ok && s.invalid.auto.code === "INVALID_ARGUMENT" && !s.invalid.gear.ok && s.invalid.gear.code === "INVALID_ARGUMENT", "string auto and invented controller values fail validation", s.invalid);
check(s.help && s.help.all === s.help.loft && /Loft typed API/.test(s.help.all) && /loft\.kitchen \(alias: loft\.bar\)/.test(s.help.all) && /loft\.garden \(alias: loft\.party\)/.test(s.help.all) && /loft\.weather/.test(s.help.all) && !/loft\.weather\.rain/.test(s.help.all) && !/\.set\(/.test(s.help.all) && !/legacy/i.test(s.help.all), "bare help and help(loft) stay concise at the top-level namespace boundary", s.help);
check(s.help && /loft\.weather\.rain — namespace/.test(s.help.weather) && !/loft\.weather\.rain\.set/.test(s.help.weather) && /loft\.weather\.rain\.set/.test(s.help.rain) && /boolean\|null/.test(s.help.rainSet) && /automatic environment/.test(s.help.rainSet), "namespace help drills one level at a time and leaf help gives the exact typed contract", s.help);
check(s.help && /loft\.kitchen/.test(s.help.kitchen) && /alias: loft\.bar/.test(s.help.kitchen) && /loft\.kitchen\.coffee — namespace/.test(s.help.kitchen) && !/loft\.kitchen\.coffee\.make/.test(s.help.kitchen) && /loft\.garden/.test(s.help.party) && /alias: loft\.party/.test(s.help.party) && /loft\.cuddly\.chest\.status/.test(s.help.chest) && /loft\.cuddly\.chest\.set/.test(s.help.chest) && s.help.string === s.help.kitchen && /dance\(/.test(s.help.legacy), "string, namespace, alias, nested object, and direct legacy help remain discoverable", s.help);
check(s.help && /loft\.api\.info/.test(s.help.api) && /loft\.api\.info\(\).*Current API state revision/.test(s.help.apiInfo), "API namespace help includes its registered non-transport capability", s.help);
check(s.help && /unavailable: The Trailer is not playing\./.test(s.help.presentation) && !/remedy:/.test(s.help.presentation), "typed leaf help presents the current exact gate without fabricating a remedy", s.help && s.help.presentation);
check(s.help && !/unavailable:/.test(s.help.fixture) && /unavailable: The Garden Party is not running\./.test(s.help.partyMusic) && /remedy: loft\.api\.perform\("garden\.set", \{"on":true\}\)/.test(s.help.partyMusic), "typed leaf help distinguishes routable actions from a real one-step remedy", s.help && { fixture: s.help.fixture, partyMusic: s.help.partyMusic });
check(s.localeHelp && s.localeHelp.ok && !s.localeHelp.error && /Alpha: loft\.api/.test(s.localeHelp.groupTie) && /loft\.weather\.rain\.set[\s\S]*loft\.weather\.rain\.status/.test(s.localeHelp.rain), "typed help ordering is fixed even when the host locale comparator is unavailable", s.localeHelp);
check(s.consoleHelp && [s.consoleHelp.bare, s.consoleHelp.call].every(function (text) {
  return /Loft typed API/.test(text) && /loft\.weather/.test(text) && /help\(loft\.weather\)/.test(text);
}), "bare help and help() print the concise typed map in the monitor console", s.consoleHelp);
check(s.manifest && !Object.prototype.hasOwnProperty.call(s.manifest, "version") && s.manifest.typed.length === caps.length && s.manifest.typed.every(function (entry) { return entry.id && entry.kind && Array.isArray(entry.argOrder) && Array.isArray(entry.aliases) && entry.completion && entry.returns && entry.availability && typeof entry.availability.available === "boolean"; }) && !Object.prototype.hasOwnProperty.call(s.manifest, "globals"), "assistant manifest stays compact and carries registry-derived availability metadata", s.manifest && { count: s.manifest.typed && s.manifest.typed.length, primitives: s.manifest.primitives && s.manifest.primitives.length });

console.log("");
if (failures) { console.log(failures + " check(s) failed."); process.exit(1); }
console.log("All checks passed (" + caps.length + " capabilities).");
