#!/usr/bin/env node
"use strict";

var lib = require("./lib");

var HARNESS = [
  '<pre id="__report">pending</pre>',
  '<script>(function(){',
  'var report={errors:[],steps:{}};function S(k,v){report.steps[k]=v;}',
  'window.addEventListener("load",function(){setTimeout(function(){run().catch(function(e){window.__errs.push(String(e&&e.stack||e));}).then(function(){report.errors=window.__errs;document.getElementById("__report").textContent=JSON.stringify(report);});},350);});',
  'async function run(){',
  ' var api=window.loft.api,oldMax=window.__maxUnlocked;window.__maxUnlocked=function(){return 4;};window.__secondRound=true;',
  ' var caps=api.capabilities(),groups=api.groups(),rooms=api.query("room.list"),game=api.query("game.status"),manifest=window.__chatApiManifest();',
  ' function D(id,args){var r=api.describe(id,args);return r.ok?r.value:null;}',
  ' var schemas={environment:D("environment.daylight.set",{on:null}),transmission:D("car.transmission.set",{mode:"auto"}),route:D("roadtrip.route.start",{route:"banff"}),stars:D("camping.stargazing.trace",{constellation:"ursa-major",star:3}),trip:D("trip.start",{variant:"molly"}),fishu:D("cuddly.fishu.speak",{}),rumi:D("poetry.rumi.read",{}),activity:D("scene.activity.start",{activity:"rainbow"}),caption:D("caption.show",{text:"hello"}),garden:D("garden.set",{on:true}),kitchen:D("kitchen.coffee.make",{}),minigame:D("minigame.start",{game:"block-party"}),kill:D("app.kill",{app:"life",device:"monitor"}),presentation:D("presentation.card.show",{card:"title"}),previewBubble:D("bathroom.bubbles.preview",{on:false}),previewEnd:D("session.preview.end",{disposition:"entry"}),trailerStop:D("trailer.stop",{disposition:"entry"})};',
  ' var legacyNames=Object.keys(window.__loftControllers||{}).concat(["help","T","LOFT_CODE_SNIPPETS","harfbuzz","googlefonts","localfonts","localfont","display_svg","clear_canvas"]).filter(function(name,index,names){return name!=="stop"&&names.indexOf(name)===index;}).sort();',
  ' var legacy=legacyNames.map(function(name){return {name:name,type:typeof window[name]};});',
  ' var envPaths=[["environment","blacklight"],["environment","daylight"],["weather","storm"],["weather","rain"],["weather","snow"],["weather","overcast"],["weather","wildfires"],["sky","aurora"],["sky","twilight"]],env=[];',
  ' for(var i=0;i<envPaths.length;i++){var path=envPaths[i],value=window.loft[path[0]][path[1]],on=await value.set(true),onStatus=value.status(),off=await value.set(false),offStatus=value.status(),auto=await value.set(null),autoStatus=value.status(),bad=await value.set("auto");env.push({name:path.join("."),on:on,onStatus:onStatus,off:off,offStatus:offStatus,auto:auto,autoStatus:autoStatus,bad:bad});}',
  ' var pans=0,oldGo=window.__goToStage;window.__goToStage=function(){pans++;return oldGo.apply(this,arguments);};var partyPromise=window.loft.garden.set(true),partyImmediate=!!window.__gardenPartyOn;await partyPromise;await window.loft.garden.set(false);await window.loft.environment.daylight.set(null);window.__goToStage=oldGo;',
  ' var navBar=await api.perform("room.go",{room:"bar"},{source:"test"}),barRoom=api.query("room.current"),navParty=await api.perform("room.go",{room:"party"},{source:"test"}),partyRoom=api.query("room.current");',
  ' var invalidAuto=await api.perform("environment.daylight.set",{on:"auto"},{source:"test"}),invalidGear=await api.perform("car.transmission.set",{mode:"automatic"},{source:"test"});',
  ' var help={all:window.loft.help(),loft:window.loft.help(window.loft),api:window.loft.help(window.loft.api),apiInfo:window.loft.help(window.loft.api.info),fixture:window.loft.help(window.loft.bathroom.fixture.activate),partyMusic:window.loft.help(window.loft.garden.music.next),kitchen:window.loft.help(window.loft.kitchen),party:window.loft.help(window.loft.party),weather:window.loft.help(window.loft.weather),rain:window.loft.help(window.loft.weather.rain),rainSet:window.loft.help(window.loft.weather.rain.set),chest:window.loft.help(window.loft.cuddly.chest),presentation:window.loft.help(window.loft.presentation.card.show),svgClear:window.loft.help(window.loft.presentation.svg.clear),font:window.loft.help(window.loft.typography.font),googleList:window.loft.help(window.loft.fonts.google.list),string:window.loft.help("kitchen"),missing:window.loft.help("dance")};',
  ' var localeHelp={ok:false},oldLocaleCompare=String.prototype.localeCompare,oldCapabilities=api.capabilities;try{String.prototype.localeCompare=function(){throw new Error("typed help consulted localeCompare");};localeHelp.rain=window.loft.help(window.loft.weather.rain);api.capabilities=function(options){return oldCapabilities.call(api,options).map(function(cap){var copy=Object.assign({},cap);if(cap.id==="api.capabilities")copy.group="Alpha";else if(cap.id==="api.info")copy.group="Zulu";return copy;});};localeHelp.groupTie=window.loft.help();localeHelp.ok=localeHelp.rain===help.rain;}catch(error){localeHelp.error=String(error&&error.message||error);}finally{api.capabilities=oldCapabilities;String.prototype.localeCompare=oldLocaleCompare;}',
  ' window.__openDropTerm();var consoleIn=document.getElementById("dropterm-in"),consoleOut=document.getElementById("dropterm-out");function consoleHelp(command){consoleOut.replaceChildren();consoleIn.focus();consoleIn.value=command;consoleIn.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true,cancelable:true}));return consoleOut.textContent;}var consoleHelpText={bare:consoleHelp("help"),public:consoleHelp("loft.help()")};window.__closeDropTerm();',
  ' var birthdayList=window.loft.calendar.birthday.list(),birthdayShow=await window.loft.calendar.birthday.show("marketa"),birthdayNext=await window.loft.calendar.birthday.next(),cakeCalled=null,oldCake=window.__loftControllers.cake;window.__loftControllers.cake=function(who){cakeCalled=who;return "cake "+who;};var birthdayCake=await window.loft.calendar.birthday.cake("marketa");window.__loftControllers.cake=oldCake;',
  ' var seasonList=window.loft.environment.season.list(),seasonInitial=window.loft.environment.season.status(),seasonSet=await window.loft.environment.season.set("summer"),seasonSummer=window.loft.environment.season.status(),seasonReset=await window.loft.environment.season.reset(),seasonAuto=window.loft.environment.season.status();',
  ' var shareCalled=0,oldShare=window.__shareCard;window.__shareCard=function(){shareCalled++;return Promise.resolve(true);};var shareOpen=await window.loft.share.card.open();window.__shareCard=oldShare;',
  ' var hafez=window.loft.poetry.hafez.read();',
  ' var dateInitial=window.loft.calendar.date.status(),dateSet=await window.loft.calendar.date.set("2027-05-01"),dateWedding=window.loft.calendar.date.status(),dateReset=await window.loft.calendar.date.reset(),dateRestored=window.loft.calendar.date.status();',
  ' var timeInitial=window.loft.calendar.time.status(),timeSet=await window.loft.calendar.time.set({hours:13,minutes:45}),timeChosen=window.loft.calendar.time.status(),moment=window.loft.calendar.moment(),timeReset=await window.loft.calendar.time.reset(),timeRestored=window.loft.calendar.time.status();',
  ' var balcony=document.getElementById("stage-balcony"),oldEclipse=window.__runBalconyEclipse,eclipseStarted=false;window.__runBalconyEclipse=function(){var effect=balcony.classList.contains("dusk")?"lunar":"solar";eclipseStarted=true;balcony.classList.add(effect+"-eclipse");setTimeout(function(){balcony.classList.remove(effect+"-eclipse");},80);};var eclipse=await window.loft.sky.eclipse.play(),eclipseClass=balcony.classList.contains(eclipse.value.effect+"-eclipse");window.__runBalconyEclipse=oldEclipse;if(window.__clearBalconyEclipse)window.__clearBalconyEclipse();',
  ' var autocomplete=(window.__loftCommands?window.__loftCommands():[]).map(function(command){return command.name;});',
  ' S("api",{caps:caps,groups:groups,rooms:rooms,game:game,manifest:manifest,schemas:schemas,legacy:legacy,env:env,aliases:{bar:window.loft.bar===window.loft.kitchen,party:window.loft.party===window.loft.garden,roomBar:barRoom,roomParty:partyRoom,navBar:navBar,navParty:navParty},namespace:{partyImmediate:partyImmediate,pans:pans,chest:typeof window.loft.cuddly.chest.set,apiInfo:typeof window.loft.api.info,apiInfoResult:window.loft.api.info(),oldChest:typeof window.chest,oldPirate:typeof window.piratebox,oldStatus:typeof window.loftstatus},invalid:{auto:invalidAuto,gear:invalidGear},help:help,localeHelp:localeHelp,consoleHelp:consoleHelpText,calendar:{list:birthdayList,show:birthdayShow,next:birthdayNext,cake:birthdayCake,cakeCalled:cakeCalled},season:{list:seasonList,initial:seasonInitial,set:seasonSet,summer:seasonSummer,reset:seasonReset,auto:seasonAuto},share:{open:shareOpen,called:shareCalled},poetry:{hafez:hafez},date:{initial:dateInitial,set:dateSet,wedding:dateWedding,reset:dateReset,restored:dateRestored},time:{initial:timeInitial,set:timeSet,chosen:timeChosen,moment:moment,reset:timeReset,restored:timeRestored},eclipse:{result:eclipse,started:eclipseStarted,classApplied:eclipseClass,room:window.__currentStageName,legacy:typeof window.eclipse},autocomplete:autocomplete});',
  ' window.__maxUnlocked=oldMax;',
  '}',
  '})();</script>'
].join("\n");

var failures = 0;
function check(ok, msg, detail) {
  if (ok) console.log("  ✓ " + msg);
  else { failures++; console.log("  ✗ " + msg + (detail ? "   [" + JSON.stringify(detail) + "]" : "")); }
}

console.log("loft-day.html API v4 surface:");
var result = lib.runPageSync("loft-day.html", HARNESS, 5200, { patchRaf: true });
if (!result) { console.log("  ✗ harness produced no report"); process.exit(1); }
var s = result.steps.api || {}, caps = s.caps || [], ids = caps.map(function (cap) { return cap.id; }), rooms = s.rooms && s.rooms.value || [];
check(result.errors.length === 0, "no uncaught page errors", result.errors);
check(caps.length >= 130 && caps.every(function (cap) {
  return cap.id && cap.group && (cap.kind === "query" || cap.kind === "action") && Array.isArray(cap.argOrder) &&
    (cap.completion === "instant" || cap.completion === "finite") && cap.description && cap.returns && cap.returns.type === "envelope" &&
    cap.availability && typeof cap.availability.available === "boolean" && cap.available === cap.availability.available;
}), "the API exposes a stable, fully described grouped typed catalogue", { count: caps.length });
check(caps.filter(function (cap) { return !cap.available; }).every(function (cap) { return typeof cap.availability.reason === "string" && cap.availability.reason.length > 0; }), "every currently unavailable catalogue row gives an exact reason", caps.filter(function (cap) { return !cap.available && !(cap.availability && cap.availability.reason); }).map(function (cap) { return cap.id; }));
check(caps.filter(function (cap) { return cap.availability.remedy; }).every(function (cap) { var remedy = cap.availability.remedy, target = caps.find(function (entry) { return entry.id === remedy.id; }); return target && target.kind === "action" && remedy.args && typeof remedy.args === "object" && !Array.isArray(remedy.args); }), "every advertised remedy names a registered typed action with object arguments", caps.filter(function (cap) { return cap.availability.remedy; }).map(function (cap) { return { id: cap.id, remedy: cap.availability.remedy }; }));
check(Array.isArray(s.groups) && s.groups.length >= 15 && s.groups.join("\0") === s.groups.slice().sort().join("\0") && s.groups.includes("Entrance / Car") && s.groups.includes("Road Trip") && s.groups.includes("Camping") && s.groups.includes("Presentation / Trailer"), "capability groups are stable, sorted, and cover the terminal act plus bounded presentation layer", s.groups);
check(rooms.length === 10 && rooms[0].id === "kitchen" && rooms[5].id === "bathroom" && rooms[9].id === "entrance" && rooms[0].aliases.includes("bar") && rooms[1].aliases.includes("party"), "room catalogue covers both floors and canonical aliases", rooms);
check(s.game && s.game.ok && s.game.value.unlocked_rooms.length === 10 && s.game.value.unlocked_rooms.includes("entrance"), "game status reports all unlocked upper and lower rooms", s.game);
check(["app.kill","app.python.status","caption.show","cuddly.chest.status","cuddly.chest.set","car.status","car.control.set","roadtrip.status","roadtrip.preview.show","camping.fire.place","camping.stew.select","camping.stargazing.trace","camping.finale.advance","session.preview.begin","session.preview.end","trailer.status","trailer.play","trailer.stop","presentation.reduced.status","presentation.card.show","presentation.card.hide","presentation.caption.show","presentation.chapter.show","presentation.cut","presentation.point","game.reset","calendar.date.status","calendar.date.set","calendar.date.reset","calendar.time.status","calendar.time.set","calendar.time.reset","calendar.moment","calendar.birthday.list","calendar.birthday.next","calendar.birthday.show","calendar.birthday.cake","environment.season.list","environment.season.status","environment.season.next","environment.season.set","environment.season.reset","share.card.open","poetry.hafez.read","poetry.rumi.read","sky.eclipse.play"].every(function (id) { return ids.includes(id); }), "room-owned controls, calendar, birthday/season/share/poetry, eclipse, Python readiness, app Kill, bounded presentation, trailer, terminal act, and preview lifecycle are typed", ids.length);
check(s.schemas && s.schemas.environment.args.on.nullable && s.schemas.environment.argOrder.join(",") === "on" && s.schemas.environment.completion === "instant" && s.schemas.transmission.args.mode.enum.join(",") === "auto,manual" && s.schemas.route.args.route.enum.join(",") === "calgary,banff,abraham" && s.schemas.trip.completion === "finite" && s.schemas.fishu.completion === "finite" && !s.schemas.rumi.available && s.schemas.rumi.availability.reason === "The quiet nighttime Cuddly fairy is not present." && s.schemas.activity.completion === "finite" && s.schemas.caption.completion === "instant" && s.schemas.caption.argOrder.join(",") === "text" && s.schemas.minigame.args.game.enum.includes("block-party") && s.schemas.kill.completion === "finite" && s.schemas.kill.args.device.enum.join(",") === "current,phone,monitor" && s.schemas.presentation.args.card.enum.join(",") === "title,final" && !s.schemas.presentation.available && s.schemas.previewEnd.args.disposition.enum.join(",") === "restore,fresh,entry" && s.schemas.trailerStop.args.disposition.enum.join(",") === "restore,fresh,entry", "argument order, nullable ownership, entry disposition, presentation gates, poetry availability, enums, and lifecycle completion are mechanically discoverable", s.schemas);
check(s.schemas && s.schemas.presentation.availability && s.schemas.presentation.availability.reason === "The Trailer is not playing." && !s.schemas.presentation.availability.remedy && s.schemas.previewEnd.availability.reason === "No preview session is active." && !s.schemas.previewEnd.availability.remedy && s.schemas.previewBubble.availability.remedy.id === "session.preview.begin", "describe() exposes exact unavailable reasons and only honest typed remedies", { presentation: s.schemas && s.schemas.presentation, previewEnd: s.schemas && s.schemas.previewEnd, previewBubble: s.schemas && s.schemas.previewBubble });
check(s.schemas.garden.aliases.includes("party.set") && s.schemas.kitchen.aliases.includes("bar.coffee.make") && caps.every(function (cap) { return Array.isArray(cap.aliases); }), "canonical room aliases are mechanically discoverable without duplicate capability ids", { garden: s.schemas.garden.aliases, kitchen: s.schemas.kitchen.aliases });
check((s.legacy || []).length >= 140 && s.legacy.every(function (entry) { return entry.type === "undefined"; }), "every private controller name plus retired helper, font, data, and help global remains absent from Window", s.legacy);
check((s.env || []).length === 9 && s.env.every(function (entry) { return entry.on.ok && entry.on.value.on === true && entry.onStatus.value.mode === "on" && entry.off.ok && entry.off.value.on === false && entry.offStatus.value.mode === "off" && entry.auto.ok && entry.autoStatus.value.mode === "auto" && typeof entry.autoStatus.value.on === "boolean" && !entry.bad.ok && entry.bad.code === "INVALID_ARGUMENT"; }), "typed environment controls accept only true, false, or null and report effective state plus mode", s.env);
check(s.aliases && s.aliases.bar && s.aliases.party && s.aliases.roomBar.value === "kitchen" && s.aliases.roomParty.value === "garden", "bar and party are identity aliases while room results stay canonical", s.aliases);
check(s.namespace && s.namespace.partyImmediate && s.namespace.pans === 0 && s.namespace.chest === "function" && s.namespace.oldChest === "undefined" && s.namespace.oldPirate === "undefined" && s.namespace.oldStatus === "undefined", "namespace setters mutate immediately without publishing compatibility globals", s.namespace);
check(s.namespace && s.namespace.apiInfo === "function" && s.namespace.apiInfoResult.ok && typeof s.namespace.apiInfoResult.value.stateVersion === "number", "non-conflicting API capabilities remain callable from the JavaScript namespace tree", s.namespace);
check(s.invalid && !s.invalid.auto.ok && s.invalid.auto.code === "INVALID_ARGUMENT" && !s.invalid.gear.ok && s.invalid.gear.code === "INVALID_ARGUMENT", "string auto and invented controller values fail validation", s.invalid);
check(s.help && s.help.all === s.help.loft && /Loft typed API/.test(s.help.all) && /loft\.kitchen \(alias: loft\.bar\)/.test(s.help.all) && /loft\.garden \(alias: loft\.party\)/.test(s.help.all) && /loft\.weather/.test(s.help.all) && !/loft\.weather\.rain/.test(s.help.all) && !/\.set\(/.test(s.help.all) && !/legacy/i.test(s.help.all), "loft.help() and loft.help(loft) stay concise at the top-level namespace boundary", s.help);
check(s.help && /loft\.weather\.rain — namespace/.test(s.help.weather) && !/loft\.weather\.rain\.set/.test(s.help.weather) && /loft\.weather\.rain\.set/.test(s.help.rain) && /boolean\|null/.test(s.help.rainSet) && /automatic environment/.test(s.help.rainSet), "namespace help drills one level at a time and leaf help gives the exact typed contract", s.help);
check(s.help && /loft\.kitchen/.test(s.help.kitchen) && /alias: loft\.bar/.test(s.help.kitchen) && /loft\.kitchen\.coffee — namespace/.test(s.help.kitchen) && !/loft\.kitchen\.coffee\.make/.test(s.help.kitchen) && /loft\.garden/.test(s.help.party) && /alias: loft\.party/.test(s.help.party) && /loft\.cuddly\.chest\.status/.test(s.help.chest) && /loft\.cuddly\.chest\.set/.test(s.help.chest) && s.help.string === s.help.kitchen && /no help for 'dance'/.test(s.help.missing), "string, namespace, alias, and nested typed help remain discoverable without legacy prose", s.help);
check(s.help && /loft\.api\.info/.test(s.help.api) && /loft\.api\.info\(\).*Current API state revision/.test(s.help.apiInfo), "API namespace help includes its registered non-transport capability", s.help);
check(s.help && /loft\.presentation\.svg\.clear\(\)/.test(s.help.svgClear) && /loft\.typography\.font\(bytes\)/.test(s.help.font) && /loft\.fonts\.google\.list\(query\?\)/.test(s.help.googleList), "native helper leaves have exact discoverable signatures", s.help);
check(s.help && /unavailable: The Trailer is not playing\./.test(s.help.presentation) && !/remedy:/.test(s.help.presentation), "typed leaf help presents the current exact gate without fabricating a remedy", s.help && s.help.presentation);
check(s.help && !/unavailable:/.test(s.help.fixture) && /unavailable: The Garden Party is not running\./.test(s.help.partyMusic) && /remedy: loft\.api\.perform\("garden\.set", \{"on":true\}\)/.test(s.help.partyMusic), "typed leaf help distinguishes routable actions from a real one-step remedy", s.help && { fixture: s.help.fixture, partyMusic: s.help.partyMusic });
check(s.localeHelp && s.localeHelp.ok && !s.localeHelp.error && /Alpha: loft\.api/.test(s.localeHelp.groupTie) && /loft\.weather\.rain\.set[\s\S]*loft\.weather\.rain\.status/.test(s.localeHelp.rain), "typed help ordering is fixed even when the host locale comparator is unavailable", s.localeHelp);
check(s.consoleHelp && /ReferenceError: help is not defined/.test(s.consoleHelp.bare) && /Loft typed API/.test(s.consoleHelp.public) && /loft\.weather/.test(s.consoleHelp.public) && /loft\.help\(loft\.weather\)/.test(s.consoleHelp.public), "the console rejects bare help and prints the typed map only through loft.help()", s.consoleHelp);
check(s.manifest && !Object.prototype.hasOwnProperty.call(s.manifest, "version") && s.manifest.typed.length === caps.length && s.manifest.typed.every(function (entry) { return entry.id && entry.kind && Array.isArray(entry.argOrder) && Array.isArray(entry.aliases) && entry.completion && entry.returns && entry.availability && typeof entry.availability.available === "boolean"; }) && !Object.prototype.hasOwnProperty.call(s.manifest, "globals"), "assistant manifest stays compact and carries registry-derived availability metadata", s.manifest && { count: s.manifest.typed && s.manifest.typed.length, primitives: s.manifest.primitives && s.manifest.primitives.length });
check(s.calendar && s.calendar.list.ok && s.calendar.list.value.length > 10 && s.calendar.list.value[0].id === "marketa" && s.calendar.show.ok && s.calendar.show.value.id === "marketa" && s.calendar.next.ok && s.calendar.next.value.id && s.calendar.cake.ok && s.calendar.cakeCalled === "marketa", "birthday discovery, show, next, and cake behavior run only through loft.calendar.birthday", s.calendar);
check(s.season && s.season.list.ok && s.season.list.value.includes("summer") && s.season.list.value.includes("auto") && s.season.set.ok && s.season.set.value.season === "summer" && s.season.summer.ok && s.season.summer.value === "summer" && s.season.reset.ok && s.season.auto.ok && s.season.auto.value === "auto", "season discovery, selection, and reset run only through loft.environment.season", s.season);
check(s.share && s.share.called === 1 && s.share.open.ok && s.share.open.value.opened, "share-card behavior runs only through loft.share.card", s.share);
check(s.poetry && s.poetry.hafez.ok && /^📖 /.test(s.poetry.hafez.value), "Hafez readings run only through loft.poetry.hafez.read", s.poetry);
check(s.date && s.date.set.ok && s.date.set.value.date.year === 2027 && s.date.set.value.date.month === 5 && s.date.set.value.date.day === 1 && s.date.wedding.value.overridden && s.date.reset.ok && !s.date.restored.value.overridden, "calendar date status, set, and reset stay under loft.calendar.date", s.date);
check(s.time && s.time.set.ok && s.time.set.value.time.hours === 13 && s.time.set.value.time.minutes === 45 && s.time.chosen.value.overridden && s.time.moment.ok && / 13:45$/.test(s.time.moment.value.iso) && s.time.reset.ok && !s.time.restored.value.overridden, "calendar time status, set, reset, and resolved moment stay under loft.calendar", s.time);
check(s.eclipse && s.eclipse.result.ok && s.eclipse.result.value.room === "balcony" && s.eclipse.result.value.completed && /^(solar|lunar)$/.test(s.eclipse.result.value.effect) && s.eclipse.started && !s.eclipse.classApplied && s.eclipse.room === "balcony" && s.eclipse.legacy === "undefined", "the eclipse is routed to the Balcony and settles only after its finite sky lifecycle through loft.sky.eclipse.play", s.eclipse);
check(s.autocomplete && s.autocomplete.every(function (name) { return name.indexOf("loft.") === 0; }) && caps.every(function (cap) { return s.autocomplete.includes("loft." + cap.id); }) && s.autocomplete.includes("loft.calendar.birthday.show") && s.autocomplete.includes("loft.environment.season.set") && s.autocomplete.includes("loft.share.card.open") && !s.autocomplete.includes("birthday") && !s.autocomplete.includes("season") && !s.autocomplete.includes("sharecard"), "Console and Code autocomplete expose only the live loft.* tree, including every registered capability and the new namespaces", s.autocomplete);

console.log("");
if (failures) { console.log(failures + " check(s) failed."); process.exit(1); }
console.log("All checks passed (" + caps.length + " capabilities).");
