#!/usr/bin/env node
"use strict";

var lib = require("./lib");

var HARNESS = [
  '<pre id="__report">pending</pre>',
  '<script>(function(){',
  'var report={errors:[],steps:{}};function S(k,v){report.steps[k]=v;}function D(id,args){var r=window.loft.api.describe(id,args||{});return r.ok?r.value.availability:null;}function A(id,args){var d=D(id,args);return !!(d&&d.available);}function room(){var r=window.loft.api.query("room.current");return r.ok?r.value:null;}',
  'window.addEventListener("load",function(){setTimeout(function(){run().catch(function(e){window.__errs.push(String(e&&e.stack||e));}).then(function(){report.errors=window.__errs;document.getElementById("__report").textContent=JSON.stringify(report);});},350);});',
  'async function run(){',
  ' var api=window.loft.api,oldMax=window.__maxUnlocked;window.__maxUnlocked=function(){return 0;};window.__secondRound=false;',
  ' var lower=["bathroom","dungeon","cinema","bedroom","entrance"],fresh={phase:api.query("game.status").value.phase,count:api.capabilities().length,roomGo:A("room.go",{room:"balcony"}),car:A("car.dashboard.set",{open:true}),roadtripStart:A("roadtrip.start"),roadtripChooser:A("roadtrip.chooser.open"),roadtripRoute:A("roadtrip.route.start",{route:"banff"}),lower:lower.map(function(name){return [name,A(name+".set",{open:true})];}),runtime:{roster:A("roster.set",{open:true}),fixture:A("bathroom.fixture.activate",{fixture:"sink"}),camp:A("camping.fire.open"),pause:A("roadtrip.pause.set",{on:true}),moment:A("garden.moment.start",{moment:"toasts"}),call:A("call.video.start",{contact:"prague"}),flair:A("minigame.start",{game:"flair-catch"}),invaders:A("minigame.start",{game:"invaders"})},metadata:{fixture:D("bathroom.fixture.activate",{fixture:"sink"}),pause:D("roadtrip.pause.set",{on:true}),partyMusic:D("garden.music.next"),invaders:D("minigame.start",{game:"invaders"})}};',
  ' var combined={preview:{bathroom:D("bathroom.bubbles.preview",{on:true}),bedroom:D("bedroom.tic-tac-toe.preview",{on:true}),office:D("office.invaders.preview",{on:true})},party:{slow:D("garden.dance.request",{style:"slow"}),dj:D("garden.dj.set",{dj:"sina"})},car:{gear:D("car.gear.set",{gear:1})},cinema:D("cinema.playback.set",{playing:true})};',
  ' var oldPreviewBegin=window.__loftPreviewBegin;window.__loftPreviewBegin=undefined;combined.preview.noController=D("bathroom.bubbles.preview",{on:false});window.__loftPreviewBegin=oldPreviewBegin;',
  ' var oldMoment=window.__toastsOn;window.__toastsOn=true;combined.party.moment=D("garden.moment.start",{moment:"cake"});window.__toastsOn=oldMoment;',
  ' var oldPhotog=window.__photogSnap;window.__photogSnap=undefined;combined.photo=D("photo.take");window.__photogSnap=oldPhotog;',
  ' var oldPartySet=window.__setPartyMode,oldParty=window.party;window.__setPartyMode=undefined;window.party=undefined;combined.party.noController=D("garden.music.next");window.__setPartyMode=oldPartySet;window.party=oldParty;',
  ' var oldPhoneState=window.__chatPhoneState;window.__chatPhoneState=function(){return {open:true,call:"madla"};};combined.call=D("call.video.start",{contact:"prague"});var oldLaptopCall=window.__laptopCall,oldMonitorApp=window.__openMonitorApp;window.__laptopCall=undefined;window.__openMonitorApp=undefined;combined.callNoController=D("call.video.start",{contact:"prague"});window.__openMonitorApp=oldMonitorApp;window.__chatPhoneState=oldPhoneState;combined.callWrongController=D("call.video.start",{contact:"prague"});window.__laptopCall=oldLaptopCall;',
  ' var oldFlairState=window.__flairState,oldAmbient=window.__ambientMaking,oldStage=window.currentStageName;window.__flairState=function(){return {active:true};};window.__ambientMaking=function(){return true;};window.currentStageName="office";combined.minigame=D("minigame.start",{game:"flair-catch"});combined.bartender=D("kitchen.cocktail.make",{drink:"negroni"});window.currentStageName=oldStage;window.__flairState=oldFlairState;window.__ambientMaking=oldAmbient;',
  ' var deniedFixture=await api.perform("bathroom.fixture.activate",{fixture:"sink"},{source:"test"});',
  ' var dashboard=await api.perform("car.dashboard.set",{open:true},{source:"test"}),afterDashboard={room:room(),phase:api.query("game.status").value.phase,secondRound:!!window.__secondRound};',
  ' await api.perform("car.transmission.set",{mode:"manual"},{source:"test"});await api.perform("car.dashboard.set",{open:false},{source:"test"});combined.car.range=D("car.range.set",{range:"D"});await api.perform("car.dashboard.set",{open:true},{source:"test"});await api.perform("car.transmission.set",{mode:"auto"},{source:"test"});',
  ' var chooser=await api.perform("roadtrip.chooser.open",{},{source:"test"}),chooserOpen={opened:chooser.ok&&chooser.value.opened,state:api.query("roadtrip.status").value};document.getElementById("entrance-roadtrip-route-banff").dispatchEvent(new MouseEvent("click",{bubbles:true,cancelable:true}));var chooserStarted={active:api.query("roadtrip.status").value.active,route:api.query("roadtrip.status").value.route};var chooserExit=await api.perform("roadtrip.exit",{}, {source:"test"});',
  ' var start=await api.perform("roadtrip.route.start",{route:"abraham"},{source:"test"}),during={active:api.query("roadtrip.status").value.active,route:api.query("roadtrip.status").value.route,pause:A("roadtrip.pause.set",{on:true}),startAgain:A("roadtrip.start"),startAgainDetail:D("roadtrip.start"),phase:api.query("game.status").value.phase};',
  ' var oldRoadtripStart=window.__entranceRoadtripApiStart;window.__entranceRoadtripApiStart=undefined;during.startNoController=D("roadtrip.start");window.__entranceRoadtripApiStart=oldRoadtripStart;',
  ' var oldRoadtripExit=window.__exitEntranceRoadtrip;window.__exitEntranceRoadtrip=undefined;during.startNoExit=D("roadtrip.start");window.__exitEntranceRoadtrip=oldRoadtripExit;',
  ' var exit=await api.perform("roadtrip.exit",{}, {source:"test"}),afterRoadtrip={active:api.query("roadtrip.status").value.active,pause:A("roadtrip.pause.set",{on:true}),camp:A("camping.fire.open"),phase:api.query("game.status").value.phase,secondRound:!!window.__secondRound};',
  ' var bathroom=await api.perform("room.go",{room:"bathroom"},{source:"test"}),bathroomReady={room:room(),fixture:A("bathroom.fixture.activate",{fixture:"sink"}),fixtureDetail:D("bathroom.fixture.activate",{fixture:"sink"}),phase:api.query("game.status").value.phase};',
  ' await api.perform("room.go",{room:"kitchen"},{source:"test"});var kitchen={room:room(),cocktail:A("kitchen.cocktail.make",{drink:"negroni"}),mixer:A("kitchen.mixer.start",{recipe:"yale"}),flair:A("minigame.start",{game:"flair-catch"}),invaders:A("minigame.start",{game:"invaders"})};',
  ' await api.perform("room.go",{room:"garden"},{source:"test"});await api.perform("garden.set",{on:true},{source:"test"});window.__secondRound=false;var garden={room:room(),phase:api.query("game.status").value.phase,roster:A("roster.set",{open:true}),moment:A("garden.moment.start",{moment:"toasts"}),kids:A("scene.activity.start",{activity:"kids-chase"}),rainbow:A("scene.activity.start",{activity:"rainbow"}),dj:A("garden.dj.set",{dj:"danesh"}),slow:A("garden.dance.request",{style:"slow"})};',
  ' await api.perform("room.go",{room:"office"},{source:"test"});window.__secondRound=false;var office={room:room(),phase:api.query("game.status").value.phase,call:A("call.video.start",{contact:"prague"}),invaders:A("minigame.start",{game:"invaders"}),flair:A("minigame.start",{game:"flair-catch"}),dj:A("garden.dj.set",{dj:"sina"}),slow:A("garden.dance.request",{style:"slow"})};',
  ' await api.perform("garden.set",{on:false},{source:"test"});window.__maxUnlocked=oldMax;S("audit",{fresh:fresh,combined:combined,deniedFixture:deniedFixture,dashboard:dashboard,afterDashboard:afterDashboard,chooser:chooser,chooserOpen:chooserOpen,chooserStarted:chooserStarted,chooserExit:chooserExit,start:start,during:during,exit:exit,afterRoadtrip:afterRoadtrip,bathroom:bathroom,bathroomReady:bathroomReady,kitchen:kitchen,garden:garden,office:office});',
  '}',
  '})();</script>'
].join("\n");

var failures = 0;
function check(ok, msg, detail) {
  if (ok) console.log("  ✓ " + msg);
  else { failures++; console.log("  ✗ " + msg + (detail ? "   [" + JSON.stringify(detail) + "]" : "")); }
}

console.log("loft-day.html typed API story-gate audit:");
var result = lib.runPageSync("loft-day.html", HARNESS, 10500, { patchRaf: true });
if (!result) { console.log("  ✗ harness produced no report"); process.exit(1); }
var a = result.steps.audit || {}, fresh = a.fresh || {};
var combined = a.combined || {};
function compound(detail, parts) {
  return detail && !detail.available && !detail.remedy && parts.every(function (part) { return detail.reason.indexOf(part) >= 0; });
}
check(result.errors.length === 0, "no uncaught page errors", result.errors);
check(fresh.count >= 195, "the catalogue contains the audited 195-capability baseline and any later extensions", fresh.count);
check(fresh.phase === 1 && fresh.roomGo && fresh.car && fresh.roadtripStart && fresh.roadtripChooser && fresh.roadtripRoute && (fresh.lower || []).every(function (entry) { return entry[1]; }), "navigation, every lower room, the car, and every Road Trip entry are available in a fresh Phase 1 game", fresh);
check(fresh.runtime && fresh.runtime.roster && !fresh.runtime.fixture && !fresh.runtime.camp && !fresh.runtime.pause && !fresh.runtime.moment && !fresh.runtime.call && fresh.runtime.flair && !fresh.runtime.invaders, "story-independent controls and true active-surface gates reflect the fresh Kitchen state", fresh.runtime);
check(fresh.metadata && fresh.metadata.fixture.reason === "The Bathroom is not open." && fresh.metadata.fixture.remedy.id === "room.go" && fresh.metadata.fixture.remedy.args.room === "bathroom" && fresh.metadata.partyMusic.reason === "The Garden Party is not running." && fresh.metadata.partyMusic.remedy.id === "garden.set" && fresh.metadata.partyMusic.remedy.args.on === true && fresh.metadata.invaders.reason === "The Office is not open." && fresh.metadata.invaders.remedy.id === "room.go", "room and inactive-session gates publish exact machine-readable reasons and typed remedies", fresh.metadata);
check(fresh.metadata && fresh.metadata.pause.reason === "No Road Trip is active." && !Object.prototype.hasOwnProperty.call(fresh.metadata.pause, "remedy"), "gates with no honest single-step remedy publish a reason without inventing one", fresh.metadata && fresh.metadata.pause);
check(combined.preview && compound(combined.preview.bathroom, ["No preview session is active.", "The Bathroom is not open."]) && compound(combined.preview.bedroom, ["No preview session is active.", "The Bedroom is not open."]) && compound(combined.preview.office, ["No preview session is active.", "The Office is not open."]), "preview actions report inactive-session plus wrong-room blockers without an insufficient remedy", combined.preview);
check(combined.preview && compound(combined.preview.noController, ["No preview session is active."]), "preview begin is not advertised when its controller cannot establish the required session", combined.preview && combined.preview.noController);
check(combined.party && compound(combined.party.slow, ["The Garden Party is not running.", "The Garden is not open."]) && compound(combined.party.dj, ["The Garden Party is not running.", "The Garden is not open."]) && compound(combined.party.moment, ["The Garden is not open.", "Another Garden Party moment is still running."]), "Party actions report independent room, Party, and active-moment blockers together", combined.party);
check(combined.party && compound(combined.party.noController, ["The Garden Party is not running."]), "Party start is not advertised when its controller cannot clear the gate", combined.party && combined.party.noController);
check(compound(combined.photo, ["The Garden Party is not running.", "The photographer is not ready."]) && compound(combined.call, ["The Office is not open.", "Another call is active or ringing."]) && compound(combined.callNoController, ["The Office is not open.", "Another call is active or ringing.", "The video-call controller is not ready."]) && compound(combined.callWrongController, ["The Office is not open.", "The video-call controller is not ready."]), "missing or contact-mismatched controllers cannot leave Party or call remedies that clear only another blocker", { photo: combined.photo, call: combined.call, callNoController: combined.callNoController, callWrongController: combined.callWrongController });
check(compound(combined.minigame, ["A minigame is already running.", "The Kitchen is not open."]) && compound(combined.bartender, ["The Kitchen is not open.", "A minigame is running.", "The Kitchen bar is already serving or mixing a drink."]), "minigame and bartender metadata retains every independent runtime conflict", { minigame: combined.minigame, bartender: combined.bartender });
check(combined.car && compound(combined.car.gear, ["The car dashboard is not open.", "The manual transmission is not selected."]) && compound(combined.car.range, ["The car dashboard is not open.", "The automatic transmission is not selected."]) && compound(combined.cinema, ["The Cinema is not open.", "No Cinema film is loaded."]), "dashboard/mode and Cinema room/media combinations do not advertise partial remedies", { car: combined.car, cinema: combined.cinema });
check(a.deniedFixture && !a.deniedFixture.ok && a.deniedFixture.code === "NOT_AVAILABLE" && a.deniedFixture.message === "The Bathroom is not open." && a.deniedFixture.availability && a.deniedFixture.availability.remedy.id === "room.go", "NOT_AVAILABLE failures carry the same exact availability metadata as discovery", a.deniedFixture);
check(a.dashboard && a.dashboard.ok && a.afterDashboard && a.afterDashboard.room === "entrance" && a.afterDashboard.phase === 1 && !a.afterDashboard.secondRound, "opening the car performs its explicit navigation while Phase 1 is active", a.afterDashboard);
check(a.chooser && a.chooser.ok && a.chooserOpen && a.chooserOpen.opened && a.chooserOpen.state.routeChooserOpen && a.chooserStarted && a.chooserStarted.active && a.chooserStarted.route === "banff" && a.chooserExit && a.chooserExit.ok, "the visible route chooser works in Phase 1 through its normal route button", { chooser: a.chooser, opened: a.chooserOpen, started: a.chooserStarted });
check(a.start && a.start.ok && a.start.value.started && a.during && a.during.active && a.during.route === "abraham" && a.during.pause && !a.during.startAgain && a.during.phase === 1, "a direct selected Road Trip starts in Phase 1 and then enforces active-trip exclusivity", { start: a.start, during: a.during });
check(a.during && a.during.startAgainDetail && a.during.startAgainDetail.reason === "A Road Trip is already active." && a.during.startAgainDetail.remedy.id === "roadtrip.exit", "runtime exclusivity updates its reason and remedy when a Road Trip starts", a.during && a.during.startAgainDetail);
check(a.during && compound(a.during.startNoController, ["A Road Trip is already active.", "The Road Trip controller is not ready."]), "Road Trip exit is not advertised when the start controller would remain unavailable", a.during && a.during.startNoController);
check(a.during && compound(a.during.startNoExit, ["A Road Trip is already active."]), "Road Trip exit is not advertised when the exit controller cannot clear the active trip", a.during && a.during.startNoExit);
check(a.exit && a.exit.ok && a.afterRoadtrip && !a.afterRoadtrip.active && !a.afterRoadtrip.pause && !a.afterRoadtrip.camp && a.afterRoadtrip.phase === 1 && !a.afterRoadtrip.secondRound, "Road Trip exits cleanly and leaves finite/lifecycle gates intact in Phase 1", { exit: a.exit, after: a.afterRoadtrip });
check(a.bathroom && a.bathroom.ok && a.bathroomReady && a.bathroomReady.room === "bathroom" && a.bathroomReady.fixture, "direct lower-room navigation enables its room-owned actions from a fresh game", a.bathroomReady);
check(a.bathroomReady && a.bathroomReady.fixtureDetail && a.bathroomReady.fixtureDetail.available && !a.bathroomReady.fixtureDetail.reason && !a.bathroomReady.fixtureDetail.remedy, "availability metadata clears stale failure details after the owning room opens", a.bathroomReady && a.bathroomReady.fixtureDetail);
check(a.kitchen && a.kitchen.room === "kitchen" && a.kitchen.cocktail && a.kitchen.mixer && a.kitchen.flair && !a.kitchen.invaders, "fresh-game Kitchen actions are gated only by room ownership and runtime conflicts", a.kitchen);
check(a.garden && a.garden.room === "garden" && a.garden.phase === 1 && a.garden.roster && a.garden.moment && a.garden.kids && !a.garden.rainbow && a.garden.dj && a.garden.slow, "live Party actions ignore the story phase while retaining Garden ownership", a.garden);
check(a.office && a.office.room === "office" && a.office.phase === 1 && a.office.call && a.office.invaders && !a.office.flair && !a.office.dj && !a.office.slow, "Office actions ignore the story phase while Garden-owned physical actions do not pan there", a.office);

console.log("");
if (failures) { console.log(failures + " check(s) failed."); process.exit(1); }
console.log("All API story-gate checks passed.");
