#!/usr/bin/env node
// Monitor Chat UI + proxy contract. Weather leaves the desktop grid but remains reachable
// from Edmonton's menu-bar readout; Chat owns the tile and posts read-only game context.
"use strict";

var lib = require("./lib");

var HARNESS = [
  '<pre id="__report" style="position:fixed;left:-9999px">pending</pre>',
  '<script>(function(){',
  'function sleep(ms){return new Promise(function(r){setTimeout(r,ms);});}',
  'function click(el){if(el)el.dispatchEvent(new MouseEvent("click",{bubbles:true,cancelable:true}));}',
  'var report={errors:[],steps:{}}; function S(k,v){report.steps[k]=v;}',
  'window.addEventListener("load",function(){setTimeout(function(){run().catch(function(e){window.__errs.push("harness: "+String(e&&e.stack||e));}).then(function(){report.errors=window.__errs;document.getElementById("__report").textContent=JSON.stringify(report);});},350);});',
  'async function run(){',
  ' if(window.__goToStage)window.__goToStage("office"); await sleep(120);',
  ' var bbqCtx=window.__chatContext("when is the BBQ?"),brunchCtx=window.__chatContext("when is brunch?"),weddingCtx=window.__chatContext("when is the wedding?");window.__gardenPartyOn=true;window.__partyStartedAt=Date.now()-125000;var latePartyCtx=window.__chatContext("hello");window.__gardenPartyOn=false;window.__partyStartedAt=null;S("calendarKnowledge",{bbq:bbqCtx.apps.calendar&&bbqCtx.apps.calendar.weddings,brunch:brunchCtx.apps.calendar&&brunchCtx.apps.calendar.weddings,wedding:weddingCtx.apps.calendar&&weddingCtx.apps.calendar.weddings,partyElapsed:latePartyCtx.party_elapsed_seconds,albumQuery:window.loft.api.query("album.list").value,tattooQuery:window.loft.api.query("tattoos.catalog").value});',
  ' var mon=document.getElementById("office-monitor"); mon.classList.add("here","screen-on","show-caps");',
  ' var chatTile=document.getElementById("monitor-dock-chat");',
  ' S("tiles",{chat:!!chatTile,weather:!!document.getElementById("monitor-dock-weather"),icon:chatTile&&chatTile.querySelector("use")&&chatTile.querySelector("use").getAttribute("href")});',
  ' var challengeN=0,turnstileRemoveN=0,turnstileOptions=null; window.turnstile={render:function(host,opts){turnstileOptions=opts;var panel=document.createElement("div");panel.className="test-turnstile-panel";panel.textContent="Success!";host.appendChild(panel);return "test-widget";},remove:function(){turnstileRemoveN++;},execute:function(){var token="test-turnstile-token-"+(++challengeN);setTimeout(function(){turnstileOptions.callback(token);},0);}};',
  ' click(chatTile); await sleep(100);',
  ' var input=document.getElementById("monitor-chat-input"), form=document.getElementById("monitor-chat-form"), log=document.getElementById("monitor-chat-log");',
  ' S("opened",{chat:mon.classList.contains("show-chat"),greeting:log.textContent,inputDir:input.getAttribute("dir"),endpoint:window.__monitorChatEndpoint,turnstileSitekey:window.__monitorChatTurnstileSitekey,prewarmChallenges:challengeN,turnstileRemoved:turnstileRemoveN,turnstileEmpty:!document.querySelector("#loft-chat-turnstile .test-turnstile-panel")});',
  ' window.__loftControllers.caption("A live custom clue.");',
  ' var fsArea=document.getElementById("hunt-fullscreen-area"),tsHost=document.getElementById("loft-chat-turnstile");fsArea.classList.add("is-fullscreen");window.__reparentChatTurnstileToFsHost();S("turnstileFullscreen",{parent:tsHost&&tsHost.parentNode&&tsHost.parentNode.id,centered:!!tsHost&&getComputedStyle(tsHost).top!=="auto"});fsArea.classList.remove("is-fullscreen");window.__reparentChatTurnstileToFsHost();',
  ' var captured=[], releases=[], oldFetch=window.fetch,actions=[];window.addEventListener("loft:statechange",function(e){actions.push(e.detail);});',
  ' window.fetch=function(url,opts){var n=captured.length;captured.push({url:String(url),method:opts&&opts.method,headers:opts&&opts.headers,body:opts&&opts.body});return new Promise(function(resolve){releases.push(function(){var replies=[{text:"سلام، من اینجا هستم.",action:null},{text:"دنبال می‌کنم.",action:null},{text:"Let’s go.",action:{id:"room.go",args:{room:"garden"}}},{text:"Puff!",action:{id:"cuddly.fishu.speak"}},{text:"All done.",action:{id:"not.a.real.action"}}];resolve(new Response(JSON.stringify({reply:JSON.stringify(replies[n]||{text:"Done.",action:null})}),{status:200,headers:{"Content-Type":"application/json"}}));});});};',
  ' input.value="سلام"; input.dispatchEvent(new Event("input",{bubbles:true})); form.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true})); await sleep(30);',
  ' S("pending",{thinking:/Thinking|Přemýšlím/.test(log.textContent),enabled:!input.disabled,captured:captured.length,challenges:challengeN});',
  ' input.value="ادامه بده"; input.dispatchEvent(new Event("input",{bubbles:true})); form.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true})); await sleep(30);',
  ' S("followup",{shown:/ادامه بده/.test(log.textContent),requestsBeforeFirstReply:captured.length,inputEnabled:!input.disabled});',
  ' if(releases[0])releases.shift()(); await sleep(150); S("queuePump",{requests:captured.length}); if(releases[0])releases.shift()(); await sleep(150);',
  ' var first=captured[0], second=captured[1], payload=first?JSON.parse(first.body):null, payload2=second?JSON.parse(second.body):null, messages=log.querySelectorAll(".chat-msg"); var last=messages[messages.length-1];',
  ' S("request",{url:first&&first.url,method:first&&first.method,message:payload&&payload.message,language:payload&&payload.language,turnstileToken:payload&&payload.turnstile_token,context:payload&&payload.context,history:payload&&payload.history,secondHistory:payload2&&payload2.history});',
  ' S("persian",{text:last&&last.textContent,dir:last&&last.getAttribute("dir"),computed:last&&getComputedStyle(last).direction,history:window.__monitorChatHistory&&window.__monitorChatHistory(),fits:document.getElementById("monitor-chat-wrap").scrollWidth<=document.getElementById("monitor-chat-wrap").clientWidth});',
  ' click(document.getElementById("monitor-chat-close")); await sleep(30); mon.classList.add("show-caps"); click(chatTile); await sleep(60);',
  ' S("retained",{open:mon.classList.contains("show-chat"),reply:/سلام، من/.test(log.textContent)});',
  ' window.__setLang("cs"); await sleep(30); S("czech",{title:document.querySelector(".chat-bar-title").textContent,greeting:log.querySelector(".chat-msg.assistant").textContent,reply:/سلام، من/.test(log.textContent)});',
  ' window.__toggleDropTerm(); await sleep(30); var dtIn=document.getElementById("dropterm-in"), dtOut=document.getElementById("dropterm-out"); dtIn.value=\'loft.app.open("chat")\'; dtIn.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true,cancelable:true})); await sleep(80); S("consoleApp",{open:mon.classList.contains("show-chat"),requests:captured.length,inputEmpty:!dtIn.value,output:dtOut.textContent}); window.__toggleDropTerm();var actionPromise=window.__monitorChatAsk("Take me to the garden/party.");await sleep(30);if(releases[0])releases.shift()();await actionPromise;await sleep(40);S("action",{room:window.__currentStageName,events:actions.slice(),history:window.__monitorChatHistory&&window.__monitorChatHistory()});var fishuCalls=0;window.__speakFishu=function(){fishuCalls++;return true;};var fishuPromise=window.__monitorChatAsk("Fišü!");await sleep(30);if(releases[0])releases.shift()();await fishuPromise;await sleep(40);var fishuPayload=captured[3]?JSON.parse(captured[3].body):null;S("fishu",{calls:fishuCalls,room:window.__currentStageName,payload:fishuPayload,events:actions.slice()});var failedActionPromise=window.__monitorChatAsk("Do an unknown thing.");await sleep(30);if(releases[0])releases.shift()();var failedActionReply=await failedActionPromise;await sleep(40);var failedHistory=window.__monitorChatHistory();S("actionFailure",{reply:failedActionReply,last:failedHistory[failedHistory.length-1]&&failedHistory[failedHistory.length-1].text,shown:log.textContent});window.fetch=oldFetch;',
  ' var oldSnap=window.__photogSnap,oldParty=window.__gardenPartyOn,photoCalls=[];window.__gardenPartyOn=true;window.__photogSnap=function(room,silent,force){photoCalls.push({room:room,silent:silent,force:force});return {id:909};};var photoResult=await window.loft.api.perform("photo.take",{}, {source:"messages-chat"});S("photoAction",{result:photoResult,calls:photoCalls,events:actions.slice()});window.__photogSnap=oldSnap;window.__gardenPartyOn=oldParty;',
  ' var oldNextParty=window.__nextPartyDance,oldExtendParty=window.__extendPartyLifecycle,nextPartyCalls=0,extendPartyCalls=0;window.__gardenPartyOn=true;window.__nextPartyDance=function(){nextPartyCalls++;window.__partyDance="salsa";return true;};window.__extendPartyLifecycle=function(){extendPartyCalls++;return true;};var partyCaps=window.loft.api.capabilities({kind:"action",available:true}).map(function(x){return x.id;});var partyNextResult=await window.loft.api.perform("garden.music.next",{}, {source:"messages-chat"});var partyExtendResult=await window.loft.api.perform("garden.extend",{}, {source:"charlie-chat"});var wrongSkipResult=await window.loft.api.perform("music.skip",{}, {source:"messages-chat"});S("partyNext",{result:partyNextResult,extendResult:partyExtendResult,wrong:wrongSkipResult,calls:nextPartyCalls,extendCalls:extendPartyCalls,caps:partyCaps,events:actions.slice()});window.__nextPartyDance=oldNextParty;window.__extendPartyLifecycle=oldExtendParty;window.__gardenPartyOn=oldParty;',
  ' await window.loft.api.perform("environment.daylight.set",{on:true},{source:"test-setup"});var dayNightResult=await window.loft.api.perform("environment.daylight.set",{on:false},{source:"messages-chat"}),nightApplied=document.getElementById("stage-balcony").classList.contains("dusk");await window.loft.api.perform("environment.daylight.set",{on:true},{source:"test-reset"});S("dayNightAction",{result:dayNightResult,nightApplied:nightApplied,events:actions.slice()});',
  ' window.__secondRound=false;var phaseOneTripCaps=window.loft.api.capabilities({kind:"action",available:true}).map(function(x){return x.id;});window.__secondRound=true;window.__gardenPartyOn=true;var partyTripCaps=window.loft.api.capabilities({kind:"action",available:true}).map(function(x){return x.id;});var heavyTripResult=await window.loft.api.perform("trip.start",{variant:"ketamine"},{source:"messages-chat"});var beforeTrip=window.loft.api.query("trip.status");window.__gardenPartyOn=false;var oldHasFocus=document.hasFocus;Object.defineProperty(document,"hasFocus",{value:function(){return false;},configurable:true});var mollyTripPromise=window.loft.api.perform("trip.start",{variant:"molly"},{source:"charlie-chat"});await sleep(40);var duringTrip=window.loft.api.query("trip.status");var secondTripResult=await window.loft.api.perform("trip.start",{variant:"acid"},{source:"charlie-chat"});var mollyTripResult=await mollyTripPromise;Object.defineProperty(document,"hasFocus",{value:oldHasFocus,configurable:true});S("tripAction",{phaseOneCaps:phaseOneTripCaps,partyCaps:partyTripCaps,heavy:heavyTripResult,before:beforeTrip,molly:mollyTripResult,during:duringTrip,second:secondTripResult,room:window.__currentStageName,events:actions.slice()});',
  ' if(window.__resetMonitorAppState)window.__resetMonitorAppState("chat"); await sleep(30); S("killed",{closed:!mon.classList.contains("show-chat"),history:window.__monitorChatHistory&&window.__monitorChatHistory().length});',
  ' mon.classList.add("show-caps"); click(document.getElementById("monitor-desk-weather")); await sleep(40); S("toolbarWeather",mon.classList.contains("show-weather")); if(window.__closeMonitorWeather)window.__closeMonitorWeather();',
  ' mon.classList.add("show-caps"); var weatherResult=window.__openMonitorApp&&window.__openMonitorApp("weather"); S("weatherHidden",{result:weatherResult,open:mon.classList.contains("show-weather")});',
  ' var tower=document.getElementById("office-pc-desk-trio"); if(tower)tower.classList.add("on"); mon.classList.add("here","screen-on","show-caps"); var chatResult=window.__openMonitorApp&&window.__openMonitorApp("chat"); await sleep(1100); S("consoleChat",{result:chatResult,open:mon.classList.contains("show-chat")});',
  '}',
  '})();</script>'
].join("\n");

var failures = 0;
function check(ok, msg, detail) { if (ok) console.log("  ✓ " + msg); else { failures++; console.log("  ✗ " + msg + (detail ? "   [" + JSON.stringify(detail) + "]" : "")); } }

console.log("rsvp.html monitor Chat:");
var r = lib.runPageSync("rsvp.html", HARNESS, 15000, { patchRaf: true });
if (!r) { console.log("  ✗ harness produced no report"); process.exit(1); }
var s = r.steps;
check(r.errors.length === 0, "no uncaught page errors", r.errors);
check(s.tiles.chat && !s.tiles.weather && s.tiles.icon === "#dicon-chat", "Chat replaces Weather in the desktop grid with its own icon", s.tiles);
check(s.opened.chat && /I’m Charlie/.test(s.opened.greeting) && /know this loft/.test(s.opened.greeting) && s.opened.inputDir === "auto", "Chat opens with Charlie's welcome and direction-aware input", s.opened);
check(s.opened.prewarmChallenges === 1, "opening Chat pre-warms one Turnstile token", s.opened);
check(s.opened.turnstileRemoved === 1 && s.opened.turnstileEmpty, "a completed Turnstile challenge removes its success panel immediately", s.opened);
check(s.turnstileFullscreen.parent === "hunt-fullscreen-area" && s.turnstileFullscreen.centered, "the Turnstile host follows the game into fullscreen and stays viewport-centered", s.turnstileFullscreen);
check(s.opened.endpoint === "https://marketa.behdad.org/chat", "Chat exposes the exact Cloudflare proxy endpoint", s.opened.endpoint);
check(/^0x/.test(s.opened.turnstileSitekey || ""), "Chat exposes the public Turnstile site key", s.opened.turnstileSitekey);
check(s.pending.thinking && s.pending.enabled && s.pending.captured === 1 && s.pending.challenges === 1, "the first message consumes the pre-warmed token without another challenge", s.pending);
check(s.followup.shown && s.followup.inputEnabled && s.followup.requestsBeforeFirstReply === 1 && s.queuePump.requests === 2, "follow-ups queue in the UI and send in order after the active reply", { followup: s.followup, pump: s.queuePump });
check(s.request.url === "https://marketa.behdad.org/chat" && s.request.method === "POST" && s.request.message === "سلام" && s.request.language === "auto", "Worker receives a JSON POST with the message and automatic-language contract", s.request);
check(s.request.turnstileToken === "test-turnstile-token-1", "Chat attaches a fresh Turnstile token to the Worker request", s.request.turnstileToken);
check(s.request.secondHistory && s.request.secondHistory.length === 2 && s.request.secondHistory[1].role === "assistant", "queued follow-up includes the preceding reply as context", s.request.secondHistory);
check(s.calendarKnowledge.bbq && s.calendarKnowledge.bbq.length === 4 && s.calendarKnowledge.brunch.length === 4 && s.calendarKnowledge.wedding.length === 4 && s.calendarKnowledge.bbq.some(function(e){return e.id === "edmonton-day2" && e.start_local === "20270502T160000";}) && s.calendarKnowledge.brunch.some(function(e){return e.id === "prague-day2" && e.start_local === "20270711T110000";}) && s.calendarKnowledge.partyElapsed >= 124 && s.calendarKnowledge.partyElapsed <= 127 && Array.isArray(s.calendarKnowledge.albumQuery) && s.calendarKnowledge.albumQuery.length && Array.isArray(s.calendarKnowledge.tattooQuery) && s.calendarKnowledge.tattooQuery.length, "BBQ, brunch, and wedding questions retrieve all canonical events, party time is contextual, and direct app queries keep their catalogs", s.calendarKnowledge);
check(s.request.context && s.request.context.room === "office" && s.request.context.phase === 1 && Array.isArray(s.request.context.unlocked_rooms) && s.request.context.date && s.request.context.time && typeof s.request.context.session.seconds === "number" && s.request.context.actions_available.indexOf("room.go") >= 0 && s.request.context.actions_available.indexOf("app.open") >= 0 && /Call Prague/.test(s.request.context.instructions.office) && /not the game/.test(s.request.context.instructions.party_exit_hint) && /tell us/.test(s.request.context.instructions.rsvp_exit) && s.request.context.current_hint === "A live custom clue." && s.request.context.current_hint_key === null, "request includes the rendered current instruction, the complete localized instruction catalog, and available action IDs", s.request.context);
check(s.persian.text === "دنبال می‌کنم." && s.persian.dir === "auto" && s.persian.computed === "rtl" && s.persian.fits, "Persian response paints RTL without horizontal overflow", s.persian);
check(s.persian.history.length === 4 && s.persian.history.map(function (m) { return m.role; }).join(",") === "user,assistant,user,assistant", "queued turns settle into conversational order", s.persian.history);
check(s.retained.open && s.retained.reply, "ordinary close and reopen retains the conversation", s.retained);
check(s.czech.title === "chat" && /Jsem Charlie/.test(s.czech.greeting) && /Znám tenhle loft/.test(s.czech.greeting) && s.czech.reply, "site-language switch localizes Charlie's welcome without altering the conversation", s.czech);
check(s.consoleApp.open && s.consoleApp.requests === 2 && s.consoleApp.inputEmpty && /loft\.app\.open/.test(s.consoleApp.output), "the JavaScript console opens Chat only through loft.app.open() without inventing a chat command dialect", s.consoleApp);
check(s.action.room === "garden" && s.action.events.some(function(e){return e.id === "room.go" && e.args.room === "garden" && e.source === "charlie-chat";}) && s.action.history[s.action.history.length - 1].text === "Let’s go.", "a structured Charlie action executes through loft.api without leaking JSON into history", s.action);
check(s.fishu.calls === 1 && s.fishu.room === "garden" && s.fishu.payload.context.actions_available.indexOf("cuddly.fishu.speak") >= 0 && s.fishu.events.some(function(e){return e.id === "cuddly.fishu.speak" && e.source === "charlie-chat";}), "a Fishu chat action speaks without moving the visitor", s.fishu);
check(/All done/.test(s.actionFailure.reply) && /nepodařilo/.test(s.actionFailure.reply) && s.actionFailure.last === s.actionFailure.reply && /nepodařilo/.test(s.actionFailure.shown), "a failed Charlie action visibly corrects the reply and records the outcome in history", s.actionFailure);
check(s.photoAction.result.ok && s.photoAction.result.value.photo_id === 909 && s.photoAction.calls.length === 1 && s.photoAction.calls[0].force === true && s.photoAction.events.some(function(e){return e.id === "photo.take" && e.source === "messages-chat";}), "the photo.take capability makes one forced current-room Aspen shot through the typed API", s.photoAction);
check(s.partyNext.result.ok && s.partyNext.calls === 1 && s.partyNext.caps.indexOf("garden.music.next") >= 0 && s.partyNext.caps.indexOf("music.skip") < 0 && !s.partyNext.wrong.ok && s.partyNext.wrong.code === "NOT_AVAILABLE" && s.partyNext.events.some(function(e){return e.id === "garden.music.next" && e.source === "messages-chat";}), "during a party, the API exposes and runs the party-tune transport instead of the guitar playlist skip", s.partyNext);
check(s.partyNext.extendResult.ok && s.partyNext.extendCalls === 1 && s.partyNext.caps.indexOf("garden.extend") >= 0 && s.partyNext.events.some(function(e){return e.id === "garden.extend" && e.source === "charlie-chat";}), "during a party, the typed API can explicitly extend the lifecycle", s.partyNext);
check(s.dayNightAction.result.ok && s.dayNightAction.result.value.on === false && s.dayNightAction.result.value.mode === "off" && s.dayNightAction.nightApplied && s.dayNightAction.events.some(function(e){return e.id === "environment.daylight.set" && e.args.on === false && e.source === "messages-chat";}), "the typed API changes the loft between day and night", s.dayNightAction);
check(s.tripAction.phaseOneCaps.indexOf("trip.start") >= 0 && s.tripAction.phaseOneCaps.indexOf("trip.next") >= 0 && s.tripAction.partyCaps.indexOf("trip.start") >= 0 && s.tripAction.partyCaps.indexOf("trip.next") >= 0 && !s.tripAction.heavy.ok && s.tripAction.heavy.code === "NOT_AVAILABLE" && !s.tripAction.before.value.active, "magic-box trip actions are scriptable in either phase while a named heavy party trip remains refused without substitution", s.tripAction);
check(s.tripAction.molly.ok && !s.tripAction.molly.value.active && s.tripAction.molly.value.variant === "molly" && s.tripAction.during.ok && s.tripAction.during.value.active && s.tripAction.during.value.variant === "molly" && s.tripAction.room === "garden" && !s.tripAction.second.ok && s.tripAction.second.code === "NOT_AVAILABLE" && s.tripAction.events.some(function(e){return e.id === "trip.start" && e.args.variant === "molly" && e.source === "charlie-chat";}), "the typed API tolerates unreliable mobile focus, reports the live trip, blocks mixing, and settles on completion", s.tripAction);
check(s.killed.closed && s.killed.history === 0, "Kill closes Chat and clears retained conversation state", s.killed);
check(s.toolbarWeather === true && /weather/.test(s.weatherHidden.result || "") && !s.weatherHidden.open, "Weather opens from Edmonton toolbar without joining the desktop grid", { toolbar: s.toolbarWeather, hidden: s.weatherHidden });
check(s.consoleChat.open && /chat/.test(s.consoleChat.result || ""), "the private monitor-app seam can still open Chat for focused UI tests", s.consoleChat);

console.log("");
if (failures) { console.log(failures + " check(s) failed."); process.exit(1); }
console.log("All checks passed.");
