#!/usr/bin/env node
// Messages is a chronological group chat with contextual reply + read-state actions.
"use strict";

var lib = require("./lib");

var HARNESS = [
  '<pre id="__report" style="position:fixed;left:-9999px">pending</pre>',
  '<script>(function(){',
  'function sleep(ms){return new Promise(function(r){setTimeout(r,ms);});}',
  'var report={errors:[],steps:{}};function S(k,v){report.steps[k]=v;}',
  'function menuLabels(){return [].slice.call(document.querySelectorAll(".message-read-ctx button span")).map(function(x){return x.textContent;});}',
  'function menuButtons(){return document.querySelectorAll(".message-read-ctx button");}',
  'function context(row){var r=row.getBoundingClientRect();var e=new MouseEvent("contextmenu",{bubbles:true,cancelable:true,clientX:r.left+10,clientY:r.top+10});return !row.dispatchEvent(e);}',
  'function latestUnread(){var rows=window.__chatMessagesKnowledge();for(var i=rows.length-1;i>=0;i--)if(!rows[i].read)return rows[i].id;return null;}',
  'window.addEventListener("load",function(){setTimeout(function(){run().catch(function(e){window.__errs.push("harness: "+String(e&&e.stack||e));}).then(function(){report.errors=window.__errs;document.getElementById("__report").textContent=JSON.stringify(report);});},300);});',
  'async function run(){',
  ' window.__secondRound=true;if(window.__goToStage)window.__goToStage("garden");await sleep(80);window.__deliverPhoneMessage("invaders");await sleep(40);var thumb=document.querySelector(".msg-thumb.show"),thumbAct=thumb&&thumb.querySelector(".msg-thumb-act");var thumbAction=!!(thumb&&thumb.classList.contains("actionable")&&thumbAct&&getComputedStyle(thumbAct).display!=="none");if(thumb)thumb.click();await sleep(100);var notifBody=document.querySelector(".phone-app-body"),notifRow=document.querySelector(".pm-msg-row[data-message-id=invaders]");var nbr=notifBody&&notifBody.getBoundingClientRect(),nrr=notifRow&&notifRow.getBoundingClientRect();S("notification_open",{app:!!document.querySelector(".phone-shell.pm-app .pm-messages"),room:window.__currentStageName,row:!!notifRow,visible:!!(nbr&&nrr&&nrr.bottom>nbr.top&&nrr.top<nbr.bottom),unread:!!(notifRow&&notifRow.classList.contains("unread")),action:thumbAction});',
  ' var directInput=document.querySelector(".pm-msg-input");directInput.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true,cancelable:true}));await sleep(260);S("notification_escape",{phone:!!document.querySelector(".phone-backdrop.show")});window.__openMessagesAt("invaders");await sleep(40);directInput=document.querySelector(".pm-msg-input");directInput.dispatchEvent(new KeyboardEvent("keydown",{key:"/",bubbles:true,cancelable:true}));var directSearch=document.activeElement;directSearch.dispatchEvent(new KeyboardEvent("keydown",{key:"Backspace",bubbles:true,cancelable:true}));await sleep(20);S("notification_backspace_one",{phone:!!document.querySelector(".phone-backdrop.show"),active:document.activeElement&&document.activeElement.className});document.activeElement.dispatchEvent(new KeyboardEvent("keydown",{key:"Backspace",bubbles:true,cancelable:true}));await sleep(260);S("notification_backspace_two",{phone:!!document.querySelector(".phone-backdrop.show")});window.__openMessagesAt("invaders");await sleep(60);notifRow=document.querySelector(".pm-msg-row[data-message-id=invaders]");var notifAct=notifRow&&notifRow.querySelector(".pm-msg-act"),notifBubble=notifRow&&notifRow.querySelector(".pm-msg-bubble");if(notifRow)notifRow.click();await sleep(30);S("notification_read",{room:window.__currentStageName,phone:!!document.querySelector(".phone-backdrop.show"),unread:!!(notifRow&&notifRow.classList.contains("unread")),action:!!notifAct,bubbleAction:!!(notifBubble&&notifBubble.classList.contains("actionable"))});if(notifBubble)notifBubble.click();await sleep(80);S("notification_bubble_inert",{room:window.__currentStageName,phone:!!document.querySelector(".phone-backdrop.show")});if(notifAct)notifAct.click();await sleep(850);S("notification_action",{room:window.__currentStageName,phone:!!document.querySelector(".phone-backdrop.show")});',
  ' window.__secondRound=true;window.__deliverPhoneMessage("cue_mail");if(window.__hideMessageThumb)window.__hideMessageThumb();window.__loftControllers.phone.open("messages");await sleep(100);',
  ' var maskBody=document.querySelector(".phone-app-body"),maskTop=document.querySelector(".pm-msg-top"),maskBottom=document.querySelector(".pm-msg-composebar"),maskBodyRect=maskBody.getBoundingClientRect(),maskTopRect=maskTop.getBoundingClientRect(),maskBottomRect=maskBottom.getBoundingClientRect();S("sticky_masks",{top:maskTopRect.top<=maskBodyRect.top+1,bottom:maskBottomRect.bottom>=maskBodyRect.bottom-1,topBg:getComputedStyle(maskTop).backgroundColor,bottomBg:getComputedStyle(maskBottom).backgroundColor,noShortScroll:maskBody.scrollHeight<=maskBody.clientHeight+1,scrollHeight:maskBody.scrollHeight,clientHeight:maskBody.clientHeight});',
  ' S("keyboard_open",{active:document.activeElement&&document.activeElement.className,app:!!document.querySelector(".phone-shell.pm-app")});',
  ' document.activeElement.dispatchEvent(new KeyboardEvent("keydown",{key:"/",bubbles:true,cancelable:true}));await sleep(10);S("composer_slash_search",{active:document.activeElement&&document.activeElement.className,selected:document.activeElement&&document.activeElement.selectionStart===0});',
  ' var slashComposer=document.querySelector(".pm-msg-input");slashComposer.focus();slashComposer.value="hello";slashComposer.dispatchEvent(new Event("input",{bubbles:true}));var slashEvent=new KeyboardEvent("keydown",{key:"/",bubbles:true,cancelable:true});slashComposer.dispatchEvent(slashEvent);S("composer_slash_literal",{active:document.activeElement&&document.activeElement.className,prevented:slashEvent.defaultPrevented,draft:slashComposer.value});slashComposer.value="";slashComposer.dispatchEvent(new Event("input",{bubbles:true}));',
  ' document.activeElement.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true,cancelable:true}));await sleep(10);S("keyboard_escape",{active:document.activeElement&&document.activeElement.className,app:!!document.querySelector(".phone-shell.pm-app")});',
  ' document.activeElement.dispatchEvent(new KeyboardEvent("keydown",{key:"/",bubbles:true,cancelable:true}));await sleep(10);S("keyboard_search",{active:document.activeElement&&document.activeElement.className,selected:document.activeElement&&document.activeElement.selectionStart===0});',
  ' var row=document.querySelector(".pm-msg-row[data-message-id=cue_mail]"),fsArea=document.getElementById("hunt-fullscreen-area");fsArea.classList.add("is-fullscreen");context(row);var fsMenu=document.querySelector(".message-read-ctx"),fsRect=fsMenu.getBoundingClientRect(),fsHit=document.elementFromPoint(fsRect.left+6,fsRect.top+6);S("fullscreen_menu",{parent:fsMenu.parentNode.className,hit:!!(fsHit&&fsHit.closest&&fsHit.closest(".message-read-ctx"))});fsArea.classList.remove("is-fullscreen");var prevented=context(row);S("unread_menu",{prevented:prevented,labels:menuLabels(),reactionCount:document.querySelectorAll(".ctx-reaction").length,unread:row.classList.contains("unread"),app:document.querySelector(".pah-title").textContent});document.querySelector(".ctx-reaction").click();await sleep(20);row=document.querySelector(".pm-msg-row[data-message-id=cue_mail]");S("reaction",{chips:[].slice.call(row.querySelectorAll(".pm-msg-reaction")).map(function(x){return x.textContent;}),unread:row.classList.contains("unread")});context(row);S("read_menu",{labels:menuLabels()});',
  ' menuButtons()[2].click();await sleep(20);row=document.querySelector(".pm-msg-row[data-message-id=cue_mail]");S("marked_unread",{unread:row.classList.contains("unread"),latest:latestUnread()});',
  ' context(row);S("unread_menu_again",{labels:menuLabels()});menuButtons()[2].click();await sleep(20);row=document.querySelector(".pm-msg-row[data-message-id=cue_mail]");S("marked_read",{unread:row.classList.contains("unread"),latest:latestUnread(),app:document.querySelector(".pah-title").textContent});',
  ' var aiResolve=null,asked=null;window.__currentStageName="garden";window.__whoIsHere=function(room){return room==="garden"?[{name:"Bahareh"},{name:"Irene"}]:room==="kitchen"?[{name:"Pouria"}]:[];};window.__djB=true;window.__monitorGroupChatAsk=function(display,group,replyDisplay){asked={display:display,group:group,replyDisplay:replyDisplay};return new Promise(function(resolve){aiResolve=resolve;});};',
  ' context(row);menuButtons()[0].click();await sleep(20);var replying=document.querySelector(".pm-msg-replying");var composer=document.querySelector(".pm-msg-input");S("reply_selected",{show:replying.classList.contains("show"),text:replying.textContent,read:!document.querySelector(".pm-msg-row[data-message-id=cue_mail]").classList.contains("unread"),plus:!!document.querySelector(".pm-msg-compose"),unreadInTitle:!!document.querySelector(".pm-msg-title .pm-msg-unread")});',
  ' composer.value="Save me a dance!";composer.dispatchEvent(new Event("input",{bubbles:true}));document.querySelector(".pm-msg-form").dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));await sleep(30);var ids=[].slice.call(document.querySelectorAll(".pm-msg-row")).map(function(x){return x.getAttribute("data-message-id");});var liveInput=document.querySelector(".pm-msg-input");S("waiting",{ids:ids,pending:!!document.querySelector(".pm-msg-row.pending"),thinking:/Charlie is thinking/i.test(document.querySelector(".pm-messages").textContent),inputEnabled:!!liveInput&&!liveInput.disabled,asked:asked,privateHistory:window.__monitorChatHistory&&window.__monitorChatHistory()});',
  ' aiResolve(JSON.stringify({sender:"Bahareh",text:"Of course. I saved you one!",reply_to_id:"invaders",action:{id:"app.open",args:{app:"album"}}}));await sleep(40);ids=[].slice.call(document.querySelectorAll(".pm-msg-row")).map(function(x){return x.getAttribute("data-message-id");});var outgoing=document.querySelector(".pm-msg-row.outgoing"),crew=document.querySelector(".pm-msg-row[data-message-id=reply_ai_1]"),crewQuote=crew&&crew.querySelector(".pm-msg-quote"),crewAct=crew&&crew.querySelector(".pm-msg-act"),crewBubble=crew&&crew.querySelector(".pm-msg-bubble");S("answered",{ids:ids,outgoing:outgoing&&outgoing.querySelector(".pm-msg-text").textContent,quote:outgoing&&outgoing.querySelector(".pm-msg-quote").textContent,sender:crew&&crew.querySelector(".pm-msg-from").textContent,crew:crew&&crew.querySelector(".pm-msg-text").textContent,crewQuote:crewQuote&&crewQuote.textContent,pending:!!document.querySelector(".pm-msg-row.pending"),action:!!crewAct,bubbleAction:!!(crewBubble&&crewBubble.classList.contains("actionable")),albumBefore:!!document.querySelector(".pm-album")});if(crewBubble)crewBubble.click();await sleep(50);S("crew_bubble_inert",{messages:!!document.querySelector(".phone-backdrop.show .pm-messages"),album:!!document.querySelector(".phone-backdrop.show .pm-album")});if(crewAct)crewAct.click();await sleep(50);S("crew_action",{album:!!document.querySelector(".phone-backdrop.show .pm-album")});document.querySelector(".pnav-back").click();await sleep(40);S("crew_action_back",{messages:!!document.querySelector(".phone-backdrop.show .pm-messages"),home:!!document.querySelector(".phone-shell.pm-home")});outgoing=document.querySelector(".pm-msg-row.outgoing");crew=document.querySelector(".pm-msg-row[data-message-id=reply_ai_1]");crewQuote=crew&&crew.querySelector(".pm-msg-quote");context(outgoing);S("outgoing_menu",{labels:menuLabels()});var answerSearch=document.querySelector(".pm-ms-input"),answerUnread=document.querySelector(".pm-msg-unread-chk");answerSearch.value="saved";answerSearch.dispatchEvent(new Event("input",{bubbles:true}));answerUnread.checked=true;answerUnread.dispatchEvent(new Event("change",{bubbles:true}));if(crewQuote)crewQuote.click();await sleep(40);var jumped=document.querySelector(".pm-msg-row[data-message-id=invaders]");S("reply_jump",{target:!!jumped,highlight:!!(jumped&&jumped.classList.contains("reply-jump")),search:answerSearch.value,unreadOnly:answerUnread.checked});',
  ' var apiAsked=[];window.__monitorGroupChatAsk=function(text){apiAsked.push(text);var joke=/pun/i.test(text);return Promise.resolve(JSON.stringify({sender:joke?"Behdad":"Danesh",text:joke?"I have one.":"Here you go.",reply_to_id:null,action:null}));};var apiResult=await window.loft.message.send("Tell me a pun.");await sleep(40);window.__toggleDropTerm();await sleep(20);var apiConsoleIn=document.getElementById("dropterm-in");apiConsoleIn.value=\'loft.message.send("DJ, slow song please.")\';apiConsoleIn.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true,cancelable:true}));await sleep(50);var apiOut=[].slice.call(document.querySelectorAll(".pm-msg-row.outgoing .pm-msg-text")).map(function(x){return x.textContent;}).slice(-2),apiFrom=[].slice.call(document.querySelectorAll(".pm-msg-row[data-message-id^=reply_ai_] .pm-msg-from")).map(function(x){return x.textContent;}).slice(-2);S("message_api",{result:apiResult,asked:apiAsked,outgoing:apiOut,from:apiFrom,console:document.getElementById("dropterm-out").textContent});window.__toggleDropTerm();',
  ' var djNextCalls=0;window.__monitorGroupChatAsk=function(){return Promise.resolve(JSON.stringify({sender:"Danesh",text:"I have your next song — tap this.",reply_to_id:null,action:{id:"garden.music.next",args:{}}}));};window.__nextPartyDance=function(){djNextCalls++;return true;};if(window.__setPartyMode)window.__setPartyMode(true,true);if(window.__goToStage)window.__goToStage("office");window.__openMessagesAt(null);await sleep(40);window.__loftControllers.message("DJ, what should we hear next?");await sleep(60);var djRows=document.querySelectorAll(".pm-msg-row[data-message-id^=reply_ai_]"),djRow=djRows[djRows.length-1],djAct=djRow&&djRow.querySelector(".pm-msg-act");S("dj_song_suggested",{action:!!djAct,room:window.__currentStageName,phone:!!document.querySelector(".phone-backdrop.show")});if(djAct)djAct.click();await sleep(80);S("dj_song_accepted",{room:window.__currentStageName,phone:!!document.querySelector(".phone-backdrop.show"),calls:djNextCalls});window.__loftControllers.phone.open("messages");await sleep(40);',
  ' window.__monitorGroupChatAsk=function(){return Promise.resolve(JSON.stringify({sender:"behdad",text:"The espresso machine awaits — tap this and I’ll take you there.",reply_to_id:null,action:{id:"kitchen.coffee.make",args:{}}}));};if(window.__setPartyMode)window.__setPartyMode(true,true);if(window.__setDayNight)window.__setDayNight(true);if(window.__goToStage)window.__goToStage("garden");window.__openMessagesAt(null);await sleep(40);window.__loftControllers.message("Can I make a coffee?");await sleep(60);var coffeeRows=document.querySelectorAll(".pm-msg-row[data-message-id^=reply_ai_]"),coffeeRow=coffeeRows[coffeeRows.length-1],coffeeAct=coffeeRow&&coffeeRow.querySelector(".pm-msg-act");S("coffee_suggested",{action:!!coffeeAct,room:window.__currentStageName,party:!!window.__gardenPartyOn,night:document.getElementById("stage-balcony").classList.contains("dusk"),phone:!!document.querySelector(".phone-backdrop.show")});if(coffeeAct)coffeeAct.click();await sleep(80);S("coffee_accepted",{room:window.__currentStageName,party:!!window.__gardenPartyOn,night:document.getElementById("stage-balcony").classList.contains("dusk"),phone:!!document.querySelector(".phone-backdrop.show")});window.__loftControllers.phone.open("messages");await sleep(40);',
  ' window.__monitorGroupChatAsk=function(){return Promise.resolve(JSON.stringify({sender:"Charlie",text:"I can try that.",reply_to_id:null,action:{id:"not.a.real.action"}}));};window.__loftControllers.message("Do an unknown thing.");await sleep(60);var failedRows=document.querySelectorAll(".pm-msg-row[data-message-id^=reply_ai_]"),failedRow=failedRows[failedRows.length-1],failedAct=failedRow&&failedRow.querySelector(".pm-msg-act");if(failedAct)failedAct.click();await sleep(60);failedRow=document.querySelector(".pm-msg-row[data-message-id="+failedRow.getAttribute("data-message-id")+"]");S("crew_action_failed",{phone:!!document.querySelector(".phone-backdrop.show"),messages:!!document.querySelector(".pm-messages"),error:failedRow&&failedRow.querySelector(".pm-msg-action-error")&&failedRow.querySelector(".pm-msg-action-error").textContent,retry:!!(failedRow&&failedRow.querySelector(".pm-msg-act"))});',
  ' var fishuCalls=0;window.__speakFishu=function(){fishuCalls++;return true;};window.__monitorGroupChatAsk=function(){return Promise.resolve(JSON.stringify({sender:"Charlie",text:"Fishu heard you — tap this.",reply_to_id:null,action:{id:"cuddly.fishu.speak",args:{}}}));};if(window.__goToStage)window.__goToStage("garden");window.__loftControllers.phone.open("messages");await sleep(40);window.__loftControllers.message("Fishu!");await sleep(60);var fishuRows=document.querySelectorAll(".pm-msg-row[data-message-id^=reply_ai_]"),fishuRow=fishuRows[fishuRows.length-1],fishuAct=fishuRow&&fishuRow.querySelector(".pm-msg-act");if(fishuAct)fishuAct.click();await sleep(820);S("fishu_action",{room:window.__currentStageName,phone:!!document.querySelector(".phone-backdrop.show"),calls:fishuCalls});window.__loftControllers.phone.open("messages");await sleep(40);',
  ' window.__deliverPhoneMessage("kids_asleep");await sleep(30);var sleepRow=document.querySelector(".pm-msg-row[data-message-id=kids_asleep]");S("kids_sleep_info",{asleep:!!window.__kidsAsleep,late:!!window.__kidsLateParty,action:!!(sleepRow&&sleepRow.querySelector(".pm-msg-act"))});window.__deliverPhoneMessage("kids_loose");await sleep(30);var wakeRow=document.querySelector(".pm-msg-row[data-message-id=kids_loose]");S("kids_wake_info",{asleep:!!window.__kidsAsleep,action:!!(wakeRow&&wakeRow.querySelector(".pm-msg-act"))});',
  ' document.documentElement.lang="cs";if(window.__refreshPhoneText)window.__refreshPhoneText();await sleep(20);row=document.querySelector(".pm-msg-row[data-message-id=cue_mail]");context(row);S("czech",{labels:menuLabels(),placeholder:document.querySelector(".pm-msg-input").getAttribute("placeholder")});',
  ' if(window.__hideMessageReadMenu)window.__hideMessageReadMenu();window.__loftControllers.phone.open("calendar");await sleep(40);var shell=document.querySelector(".phone-shell");shell.dispatchEvent(new KeyboardEvent("keydown",{key:"/",bubbles:true,cancelable:true}));await sleep(30);S("calendar_search",{active:document.activeElement&&document.activeElement.className,on:!!document.querySelector(".calx-search-btn.is-on")});',
  ' document.querySelector(".pnav-home").click();await sleep(20);var dragTile=document.querySelector(".phone-app-tile"),dragRect=dragTile.getBoundingClientRect();dragTile.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:7,button:0,clientX:dragRect.left+10,clientY:dragRect.top+10}));window.dispatchEvent(new PointerEvent("pointermove",{bubbles:true,cancelable:true,pointerId:7,buttons:1,clientX:dragRect.left+30,clientY:dragRect.top+25}));var selEvt=new Event("selectstart",{bubbles:true,cancelable:true});dragTile.querySelector(".pat-label").dispatchEvent(selEvt);S("icon_drag",{ghost:!!document.querySelector(".phone-drag-ghost"),selectionBlocked:selEvt.defaultPrevented,userSelect:getComputedStyle(dragTile).userSelect});window.dispatchEvent(new PointerEvent("pointerup",{bubbles:true,cancelable:true,pointerId:7,button:0,clientX:dragRect.left+30,clientY:dragRect.top+25}));var touchHome=document.querySelector(".phone-home");touchHome.style.height="150px";touchHome.style.flex="none";var touchTile=document.querySelector(".phone-app-tile"),touchRect=touchTile.getBoundingClientRect();touchHome.scrollTop=0;touchTile.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:8,pointerType:"touch",button:0,clientX:touchRect.left+10,clientY:touchRect.top+30}));window.dispatchEvent(new PointerEvent("pointermove",{bubbles:true,cancelable:true,pointerId:8,pointerType:"touch",buttons:1,clientX:touchRect.left+10,clientY:touchRect.top-30}));S("icon_touch_scroll",{scrollTop:touchHome.scrollTop,ghost:!!document.querySelector(".phone-drag-ghost")});window.dispatchEvent(new PointerEvent("pointerup",{bubbles:true,cancelable:true,pointerId:8,pointerType:"touch",button:0,clientX:touchRect.left+10,clientY:touchRect.top-30}));touchHome.style.height="";touchHome.style.flex="";',
  ' if(window.__closePhoneModal)window.__closePhoneModal(true);await sleep(260);document.body.dispatchEvent(new KeyboardEvent("keydown",{key:"/",bubbles:true,cancelable:true}));await sleep(40);S("slash_open",{messages:!!document.querySelector(".phone-backdrop.show .pm-messages")});shell=document.querySelector(".phone-shell");if(shell){shell.focus();shell.dispatchEvent(new KeyboardEvent("keydown",{key:"/",bubbles:true,cancelable:true}));}await sleep(20);S("slash_in_messages",{phone:!!document.querySelector(".phone-backdrop.show"),active:document.activeElement&&document.activeElement.className});if(document.activeElement)document.activeElement.dispatchEvent(new KeyboardEvent("keydown",{key:"/",bubbles:true,cancelable:true}));await sleep(260);S("slash_close",{phone:!!document.querySelector(".phone-backdrop.show")});',
  ' window.__openMessagesAt("cue_cocktails");await sleep(40);window.__runMsgAction("cue_cocktails");await sleep(40);S("cocktail_link",{cocktails:!!document.querySelector(".phone-backdrop.show .pm-ck-feat")});document.querySelector(".pnav-back").click();await sleep(40);S("cocktail_back",{messages:!!document.querySelector(".phone-backdrop.show .pm-messages"),home:!!document.querySelector(".phone-shell.pm-home")});document.querySelector(".pnav-back").click();await sleep(260);S("cocktail_back_close",{phone:!!document.querySelector(".phone-backdrop.show")});',
  '}',
  '})();</script>'
].join("\n");

var failures = 0;
function check(ok, msg, detail) {
  if (ok) console.log("  ✓ " + msg);
  else { failures++; console.log("  ✗ " + msg + (detail ? "   [" + JSON.stringify(detail) + "]" : "")); }
}

console.log("rsvp.html message read/unread context menu:");
var r = lib.runPageSync("rsvp.html", HARNESS, 7000, { patchRaf: true });
if (!r) { console.log("  ✗ harness produced no report"); process.exit(1); }
var s = r.steps;
check(r.errors.length === 0, "no uncaught page errors", r.errors);
check(s.notification_open.app && s.notification_open.room === "garden" && s.notification_open.row && s.notification_open.visible && s.notification_open.unread && s.notification_open.action, "an actionable notification shows its arrow; tapping the card still opens and positions the unread message without running it", s.notification_open);
check(!s.notification_escape.phone && s.notification_backspace_one.phone && s.notification_backspace_one.active === "pm-ms-input" && s.notification_backspace_two.phone, "Escape closes directly opened Messages while repeated Backspace leaves its empty search open and focused", {escape:s.notification_escape,one:s.notification_backspace_one,two:s.notification_backspace_two});
check(s.notification_read.room === "garden" && s.notification_read.phone && !s.notification_read.unread && s.notification_read.action && !s.notification_read.bubbleAction, "tapping row chrome marks it read while only the action arrow remains actionable", s.notification_read);
check(s.notification_bubble_inert.room === "garden" && s.notification_bubble_inert.phone &&
  s.notification_action.room === "office" && !s.notification_action.phone,
  "the message bubble stays inert and only its arrow runs the linked action",
  { bubble: s.notification_bubble_inert, arrow: s.notification_action });
check(s.keyboard_open.active === "pm-msg-input" && s.keyboard_open.app, "Messages opens with the composer focused", s.keyboard_open);
check(s.sticky_masks.top && s.sticky_masks.bottom && s.sticky_masks.noShortScroll && !/rgba\([^)]*,\s*0\s*\)/.test(s.sticky_masks.topBg) && !/rgba\([^)]*,\s*0\s*\)/.test(s.sticky_masks.bottomBg), "sticky Messages controls mask both screen edges without creating a scrollbar for a short thread", s.sticky_masks);
check(s.composer_slash_search.active === "pm-ms-input" && s.composer_slash_search.selected, "/ moves an empty composer directly to Messages search", s.composer_slash_search);
check(s.composer_slash_literal.active === "pm-msg-input" && !s.composer_slash_literal.prevented && s.composer_slash_literal.draft === "hello", "/ remains literal when the composer already has a draft", s.composer_slash_literal);
check(/phone-shell/.test(s.keyboard_escape.active) && s.keyboard_escape.app, "first Escape blurs the composer without leaving Messages", s.keyboard_escape);
check(s.keyboard_search.active === "pm-ms-input" && s.keyboard_search.selected, "/ focuses and selects the Messages search field after leaving the composer", s.keyboard_search);
check(/phone-backdrop/.test(s.fullscreen_menu.parent) && s.fullscreen_menu.hit, "the message context menu stays above the phone inside fullscreen", s.fullscreen_menu);
check(s.unread_menu.prevented && s.unread_menu.unread && s.unread_menu.labels.join("|") === "Reply…|Copy|Mark as read." && s.unread_menu.reactionCount === 5, "an unread row offers Reply, Copy, read state, and five reactions", s.unread_menu);
check(s.reaction.chips.join("|") === "👍" && !s.reaction.unread, "a selected reaction appears compactly and reads through its message", s.reaction);
check(s.read_menu.labels.join("|") === "Reply…|Copy|Mark as unread.", "a read row offers Reply, Copy, and Mark as unread", s.read_menu);
check(s.marked_unread.unread && s.marked_unread.latest === "cue_mail", "marking unread restores unread state and count", s.marked_unread);
check(s.unread_menu_again.labels.join("|") === "Reply…|Copy|Mark as read." && !s.marked_read.unread && s.marked_read.latest === null && /messages/i.test(s.marked_read.app), "marking read catches up through the selected message without opening it", { menu: s.unread_menu_again, state: s.marked_read });
check(s.reply_selected.show && /Bahareh/.test(s.reply_selected.text) && s.reply_selected.read && !s.reply_selected.plus && s.reply_selected.unreadInTitle, "Reply targets the message, marks it read, removes +, and keeps unread-only in the title", s.reply_selected);
check(s.waiting.ids.join(",") === "invaders,cue_mail,reply_user_1" && !s.waiting.pending && !s.waiting.thinking && s.waiting.inputEnabled, "the visitor message appears immediately with no thinking placeholder and the composer remains usable", s.waiting);
check(s.waiting.asked && s.waiting.asked.display === "Save me a dance!" && s.waiting.asked.group.reply_to.id === "cue_mail" && s.waiting.asked.group.reply_to.sender === "Bahareh" && /did you check the mail/i.test(s.waiting.asked.group.reply_to.text) && s.waiting.asked.group.reply_to.reactions.join("|") === "👍" && s.waiting.asked.group.recent_messages.every(function(m){return typeof m.id === "string" && Array.isArray(m.reactions);}) && s.waiting.asked.group.current_dj === "Danesh" && s.waiting.asked.group.people_here.join("|") === "Bahareh|Irene" && s.waiting.asked.group.locations.kitchen.join("|") === "Pouria" && typeof s.waiting.asked.group.playtime.seconds === "number" && /^\d+:\d{2}$/.test(s.waiting.asked.group.playtime.display), "the group responder receives reactions, addressable recent messages, the reply target, room locations, and Clock playtime", s.waiting.asked);
check(s.waiting.asked && s.waiting.asked.group.cast.some(function(p){return p.name === "Ali" && p.role === "best man";}) && s.waiting.asked.group.cast.some(function(p){return p.name === "Bahareh" && /herds/.test(p.notes);}) && s.waiting.asked.group.cast.some(function(p){return p.name === "Behdad" && /dad jokes/.test(p.notes);}) && s.waiting.asked.group.cast.some(function(p){return p.name === "Irene" && p.can_message && p.message_frequency === "rare";}) && s.waiting.asked.group.cast.some(function(p){return p.name === "Robin" && !p.can_message;}) && s.waiting.asked.group.cast.some(function(p){return p.name === "Markéta" && /Behdad/.test(p.relationship);}), "the group responder receives cast humor and child-sender rules alongside roles and relationships", s.waiting.asked && s.waiting.asked.group.cast);
check(Array.isArray(s.waiting.privateHistory) && s.waiting.privateHistory.length === 0, "the wedding-thread exchange stays out of Charlie's private chat history", s.waiting.privateHistory);
check(s.answered.ids.join(",") === "invaders,cue_mail,reply_user_1,reply_ai_1" && s.answered.outgoing === "Save me a dance!" && /Bahareh:/.test(s.answered.quote) && s.answered.sender === "Bahareh" && /saved you one/.test(s.answered.crew) && /behdad:.*aliens/i.test(s.answered.crewQuote) && !s.answered.pending && s.answered.action && !s.answered.bubbleAction && !s.answered.albumBefore, "the asynchronous crew answer can quote an earlier message and suggest an arrow action without executing it", s.answered);
check(s.crew_bubble_inert.messages && !s.crew_bubble_inert.album && s.crew_action.album && s.crew_action_back.messages && !s.crew_action_back.home, "only an actionable crew reply arrow opens its linked phone app, whose Back returns to Messages", { bubble: s.crew_bubble_inert, action: s.crew_action, back: s.crew_action_back });
check(s.outgoing_menu.labels.join("|") === "Reply…|Copy", "sent-message rows also expose Reply and Copy instead of swallowing right-click", s.outgoing_menu);
check(s.reply_jump.target && s.reply_jump.highlight && s.reply_jump.search === "" && !s.reply_jump.unreadOnly, "tapping a reply quote reveals, scrolls to, and highlights the original message", s.reply_jump);
check(s.message_api.result && s.message_api.result.ok && s.message_api.result.value.accepted && s.message_api.asked.join("|") === "Tell me a pun.|DJ, slow song please." && s.message_api.outgoing.join("|") === s.message_api.asked.join("|") && s.message_api.from.join("|") === "behdad|Danesh" && /loft\.message\.send/.test(s.message_api.console), "loft.message.send() works directly and through the JavaScript console, posts as the player, and styles behdad lowercase in Messages", s.message_api);
check(s.dj_song_suggested.action && s.dj_song_suggested.room === "office" && s.dj_song_suggested.phone && s.dj_song_accepted.room === "garden" && !s.dj_song_accepted.phone && s.dj_song_accepted.calls === 1, "accepting a DJ song offer closes Messages, pans to the party room, and advances the music", { suggested: s.dj_song_suggested, accepted: s.dj_song_accepted });
check(s.coffee_suggested.action && s.coffee_suggested.room === "garden" && s.coffee_suggested.party && s.coffee_suggested.night && s.coffee_suggested.phone, "a coffee reply suggests an action without changing the current party scene", s.coffee_suggested);
check(s.coffee_accepted.room === "garden" && !s.coffee_accepted.party && !s.coffee_accepted.night && !s.coffee_accepted.phone, "accepting the coffee reply ends the party and restores day without forcing a room change", s.coffee_accepted);
check(s.crew_action_failed.phone && s.crew_action_failed.messages && !s.crew_action_failed.error && s.crew_action_failed.retry, "an unavailable crew suggestion remains visible and retryable without inventing an error", s.crew_action_failed);
check(s.fishu_action.room === "balcony" && s.fishu_action.phone && s.fishu_action.calls === 0, "an unavailable Fishu suggestion leaves Messages and the current room intact", s.fishu_action);
check(!s.kids_sleep_info.asleep && !s.kids_sleep_info.late && !s.kids_sleep_info.action, "the kids-asleep announcement stays informational when its occasion is inactive", s.kids_sleep_info);
check(!s.kids_wake_info.asleep && !s.kids_wake_info.action, "the kids-awake announcement applies its state on arrival and remains informational", s.kids_wake_info);
check(s.czech.labels.join("|") === "Odpovědět…|Kopírovat|Označit jako nepřečtené." && /svatební partě/.test(s.czech.placeholder), "context actions and composer follow the Czech UI language", s.czech);
check(s.calendar_search.active === "calx-search-input" && s.calendar_search.on, "/ enters and focuses Calendar search even before its field exists", s.calendar_search);
check(s.icon_drag.ghost && s.icon_drag.selectionBlocked && s.icon_drag.userSelect === "none", "dragging a phone app icon cannot start native text selection", s.icon_drag);
check(s.icon_touch_scroll.scrollTop > 0 && !s.icon_touch_scroll.ghost, "a quick touch-drag beginning on an app icon scrolls the launcher instead of rearranging it", s.icon_touch_scroll);
check(!s.slash_open.messages && !s.slash_in_messages.phone && !s.slash_close.phone, "/ stays inert after the phone overlay closes", {open:s.slash_open,inApp:s.slash_in_messages,close:s.slash_close});
check(s.cocktail_link.cocktails && s.cocktail_back.messages && !s.cocktail_back.home && !s.cocktail_back_close.phone, "a message-linked phone app returns to Messages first, then preserves the overlay's direct-close behavior", {link:s.cocktail_link,back:s.cocktail_back,close:s.cocktail_back_close});

console.log("");
if (failures) { console.log(failures + " check(s) failed."); process.exit(1); }
console.log("All checks passed.");
