#!/usr/bin/env node
// Messages is a chronological group chat with contextual reply + read-state actions.
"use strict";

var lib = require("./lib");

var HARNESS = [
  '<pre id="__report" style="position:fixed;left:-9999px">pending</pre>',
  '<script>(function(){',
  'function sleep(ms){return new Promise(function(r){setTimeout(r,ms);});}',
  'var report={errors:[],steps:{}};function S(k,v){report.steps[k]=v;}',
  'function menuLabels(){return [].slice.call(document.querySelectorAll(".message-read-ctx button span")).map(function(x){return x.textContent;});}',
  'function menuButtons(){return document.querySelectorAll(".message-read-ctx button");}',
  'function context(row){var r=row.getBoundingClientRect();var e=new MouseEvent("contextmenu",{bubbles:true,cancelable:true,clientX:r.left+10,clientY:r.top+10});return !row.dispatchEvent(e);}',
  'window.addEventListener("load",function(){setTimeout(function(){run().catch(function(e){window.__errs.push("harness: "+String(e&&e.stack||e));}).then(function(){report.errors=window.__errs;document.getElementById("__report").textContent=JSON.stringify(report);});},300);});',
  'async function run(){',
  ' window.__secondRound=true;if(window.goToStage)window.goToStage("garden");await sleep(80);window.__deliverPhoneMessage("invaders");await sleep(40);var thumb=document.querySelector(".msg-thumb.show");if(thumb)thumb.click();await sleep(100);var notifBody=document.querySelector(".phone-app-body"),notifRow=document.querySelector(".pm-msg-row[data-message-id=invaders]");var nbr=notifBody&&notifBody.getBoundingClientRect(),nrr=notifRow&&notifRow.getBoundingClientRect();S("notification_open",{app:!!document.querySelector(".phone-shell.pm-app .pm-messages"),room:window.currentStageName,row:!!notifRow,visible:!!(nbr&&nrr&&nrr.bottom>nbr.top&&nrr.top<nbr.bottom),unread:!!(notifRow&&notifRow.classList.contains("unread"))});',
  ' var directInput=document.querySelector(".pm-msg-input");directInput.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true,cancelable:true}));await sleep(260);S("notification_escape",{phone:!!document.querySelector(".phone-backdrop.show")});window.__openMessagesAt("invaders");await sleep(40);directInput=document.querySelector(".pm-msg-input");directInput.dispatchEvent(new KeyboardEvent("keydown",{key:"/",bubbles:true,cancelable:true}));var directSearch=document.activeElement;directSearch.dispatchEvent(new KeyboardEvent("keydown",{key:"Backspace",bubbles:true,cancelable:true}));await sleep(20);S("notification_backspace_one",{phone:!!document.querySelector(".phone-backdrop.show"),active:document.activeElement&&document.activeElement.className});document.activeElement.dispatchEvent(new KeyboardEvent("keydown",{key:"Backspace",bubbles:true,cancelable:true}));await sleep(260);S("notification_backspace_two",{phone:!!document.querySelector(".phone-backdrop.show")});window.__openMessagesAt("invaders");await sleep(60);notifRow=document.querySelector(".pm-msg-row[data-message-id=invaders]");var notifAct=notifRow&&notifRow.querySelector(".pm-msg-act");if(notifRow)notifRow.click();await sleep(30);S("notification_read",{room:window.currentStageName,phone:!!document.querySelector(".phone-backdrop.show"),unread:!!(notifRow&&notifRow.classList.contains("unread")),action:!!notifAct});if(notifAct)notifAct.click();await sleep(850);S("notification_action",{room:window.currentStageName,phone:!!document.querySelector(".phone-backdrop.show")});',
  ' window.__secondRound=true;window.__deliverPhoneMessage("cue_mail");if(window.__hideMessageThumb)window.__hideMessageThumb();window.phone("messages");await sleep(100);',
  ' S("keyboard_open",{active:document.activeElement&&document.activeElement.className,app:!!document.querySelector(".phone-shell.pm-app")});',
  ' document.activeElement.dispatchEvent(new KeyboardEvent("keydown",{key:"/",bubbles:true,cancelable:true}));await sleep(10);S("composer_slash_search",{active:document.activeElement&&document.activeElement.className,selected:document.activeElement&&document.activeElement.selectionStart===0});',
  ' var slashComposer=document.querySelector(".pm-msg-input");slashComposer.focus();slashComposer.value="hello";slashComposer.dispatchEvent(new Event("input",{bubbles:true}));var slashEvent=new KeyboardEvent("keydown",{key:"/",bubbles:true,cancelable:true});slashComposer.dispatchEvent(slashEvent);S("composer_slash_literal",{active:document.activeElement&&document.activeElement.className,prevented:slashEvent.defaultPrevented,draft:slashComposer.value});slashComposer.value="";slashComposer.dispatchEvent(new Event("input",{bubbles:true}));',
  ' document.activeElement.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true,cancelable:true}));await sleep(10);S("keyboard_escape",{active:document.activeElement&&document.activeElement.className,app:!!document.querySelector(".phone-shell.pm-app")});',
  ' document.activeElement.dispatchEvent(new KeyboardEvent("keydown",{key:"/",bubbles:true,cancelable:true}));await sleep(10);S("keyboard_search",{active:document.activeElement&&document.activeElement.className,selected:document.activeElement&&document.activeElement.selectionStart===0});',
  ' var row=document.querySelector(".pm-msg-row[data-message-id=cue_mail]"),fsArea=document.getElementById("hunt-fullscreen-area");fsArea.classList.add("is-fullscreen");context(row);var fsMenu=document.querySelector(".message-read-ctx"),fsRect=fsMenu.getBoundingClientRect(),fsHit=document.elementFromPoint(fsRect.left+6,fsRect.top+6);S("fullscreen_menu",{parent:fsMenu.parentNode.className,hit:!!(fsHit&&fsHit.closest&&fsHit.closest(".message-read-ctx"))});fsArea.classList.remove("is-fullscreen");var prevented=context(row);S("unread_menu",{prevented:prevented,labels:menuLabels(),reactionCount:document.querySelectorAll(".ctx-reaction").length,unread:row.classList.contains("unread"),app:document.querySelector(".pah-title").textContent});document.querySelector(".ctx-reaction").click();await sleep(20);row=document.querySelector(".pm-msg-row[data-message-id=cue_mail]");S("reaction",{chips:[].slice.call(row.querySelectorAll(".pm-msg-reaction")).map(function(x){return x.textContent;})});context(row);',
  ' menuButtons()[2].click();await sleep(20);row=document.querySelector(".pm-msg-row[data-message-id=cue_mail]");S("marked_read",{unread:row.classList.contains("unread"),latest:window.__latestUnreadMessage(),app:document.querySelector(".pah-title").textContent});',
  ' context(row);S("read_menu",{labels:menuLabels()});menuButtons()[2].click();await sleep(20);row=document.querySelector(".pm-msg-row[data-message-id=cue_mail]");S("marked_unread",{unread:row.classList.contains("unread"),latest:window.__latestUnreadMessage()});',
  ' var aiResolve=null,asked=null;window.currentStageName="garden";window.__whoIsHere=function(room){return room==="garden"?[{name:"Bahareh"},{name:"Irene"}]:room==="kitchen"?[{name:"Pouria"}]:[];};window.__djB=true;window.__monitorGroupChatAsk=function(display,group,replyDisplay){asked={display:display,group:group,replyDisplay:replyDisplay};return new Promise(function(resolve){aiResolve=resolve;});};',
  ' context(row);menuButtons()[0].click();await sleep(20);var replying=document.querySelector(".pm-msg-replying");var composer=document.querySelector(".pm-msg-input");S("reply_selected",{show:replying.classList.contains("show"),text:replying.textContent,read:!document.querySelector(".pm-msg-row[data-message-id=cue_mail]").classList.contains("unread"),plus:!!document.querySelector(".pm-msg-compose"),unreadInTitle:!!document.querySelector(".pm-msg-title .pm-msg-unread")});',
  ' composer.value="Save me a dance!";composer.dispatchEvent(new Event("input",{bubbles:true}));document.querySelector(".pm-msg-form").dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));await sleep(30);var ids=[].slice.call(document.querySelectorAll(".pm-msg-row")).map(function(x){return x.getAttribute("data-message-id");});var liveInput=document.querySelector(".pm-msg-input");S("waiting",{ids:ids,pending:!!document.querySelector(".pm-msg-row.pending"),thinking:/Charlie is thinking/i.test(document.querySelector(".pm-messages").textContent),inputEnabled:!!liveInput&&!liveInput.disabled,asked:asked,privateHistory:window.__monitorChatHistory&&window.__monitorChatHistory()});',
  ' aiResolve(JSON.stringify({sender:"Bahareh",text:"Of course. I saved you one!",reply_to_id:"invaders",action:{id:"app.open",args:{app:"album"}}}));await sleep(40);ids=[].slice.call(document.querySelectorAll(".pm-msg-row")).map(function(x){return x.getAttribute("data-message-id");});var outgoing=document.querySelector(".pm-msg-row.outgoing"),crew=document.querySelector(".pm-msg-row[data-message-id=reply_ai_1]"),crewQuote=crew&&crew.querySelector(".pm-msg-quote"),crewAct=crew&&crew.querySelector(".pm-msg-act");S("answered",{ids:ids,outgoing:outgoing&&outgoing.querySelector(".pm-msg-text").textContent,quote:outgoing&&outgoing.querySelector(".pm-msg-quote").textContent,sender:crew&&crew.querySelector(".pm-msg-from").textContent,crew:crew&&crew.querySelector(".pm-msg-text").textContent,crewQuote:crewQuote&&crewQuote.textContent,pending:!!document.querySelector(".pm-msg-row.pending"),action:!!crewAct,albumBefore:!!document.querySelector(".pm-album")});if(crewAct)crewAct.click();await sleep(50);S("crew_action",{album:!!document.querySelector(".phone-backdrop.show .pm-album")});document.querySelector(".pnav-back").click();await sleep(40);S("crew_action_back",{messages:!!document.querySelector(".phone-backdrop.show .pm-messages"),home:!!document.querySelector(".phone-shell.pm-home")});outgoing=document.querySelector(".pm-msg-row.outgoing");crew=document.querySelector(".pm-msg-row[data-message-id=reply_ai_1]");crewQuote=crew&&crew.querySelector(".pm-msg-quote");context(outgoing);S("outgoing_menu",{labels:menuLabels()});var answerSearch=document.querySelector(".pm-ms-input"),answerUnread=document.querySelector(".pm-msg-unread-chk");answerSearch.value="saved";answerSearch.dispatchEvent(new Event("input",{bubbles:true}));answerUnread.checked=true;answerUnread.dispatchEvent(new Event("change",{bubbles:true}));if(crewQuote)crewQuote.click();await sleep(40);var jumped=document.querySelector(".pm-msg-row[data-message-id=invaders]");S("reply_jump",{target:!!jumped,highlight:!!(jumped&&jumped.classList.contains("reply-jump")),search:answerSearch.value,unreadOnly:answerUnread.checked});',
  ' var apiAsked=[];window.__monitorGroupChatAsk=function(text){apiAsked.push(text);var joke=/pun/i.test(text);return Promise.resolve(JSON.stringify({sender:joke?"Behdad":"Danesh",text:joke?"I have one.":"Here you go.",reply_to_id:null,action:null}));};var apiResult=window.message("Tell me a pun.");await sleep(40);window.__toggleDropTerm();await sleep(20);var apiConsoleIn=document.getElementById("dropterm-in");apiConsoleIn.value="/message DJ, slow song please.";apiConsoleIn.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true,cancelable:true}));await sleep(50);var apiOut=[].slice.call(document.querySelectorAll(".pm-msg-row.outgoing .pm-msg-text")).map(function(x){return x.textContent;}).slice(-2),apiFrom=[].slice.call(document.querySelectorAll(".pm-msg-row[data-message-id^=reply_ai_] .pm-msg-from")).map(function(x){return x.textContent;}).slice(-2);S("message_api",{result:apiResult,asked:apiAsked,outgoing:apiOut,from:apiFrom,console:document.getElementById("dropterm-out").textContent});window.__toggleDropTerm();',
  ' document.documentElement.lang="cs";if(window.refreshPhoneText)window.refreshPhoneText();await sleep(20);row=document.querySelector(".pm-msg-row[data-message-id=cue_mail]");context(row);S("czech",{labels:menuLabels(),placeholder:document.querySelector(".pm-msg-input").getAttribute("placeholder")});',
  ' if(window.__hideMessageReadMenu)window.__hideMessageReadMenu();window.phone("calendar");await sleep(40);var shell=document.querySelector(".phone-shell");shell.dispatchEvent(new KeyboardEvent("keydown",{key:"/",bubbles:true,cancelable:true}));await sleep(30);S("calendar_search",{active:document.activeElement&&document.activeElement.className,on:!!document.querySelector(".calx-search-btn.is-on")});',
  ' document.querySelector(".pnav-home").click();await sleep(20);var dragTile=document.querySelector(".phone-app-tile"),dragRect=dragTile.getBoundingClientRect();dragTile.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:7,button:0,clientX:dragRect.left+10,clientY:dragRect.top+10}));window.dispatchEvent(new PointerEvent("pointermove",{bubbles:true,cancelable:true,pointerId:7,buttons:1,clientX:dragRect.left+30,clientY:dragRect.top+25}));var selEvt=new Event("selectstart",{bubbles:true,cancelable:true});dragTile.querySelector(".pat-label").dispatchEvent(selEvt);S("icon_drag",{ghost:!!document.querySelector(".phone-drag-ghost"),selectionBlocked:selEvt.defaultPrevented,userSelect:getComputedStyle(dragTile).userSelect});window.dispatchEvent(new PointerEvent("pointerup",{bubbles:true,cancelable:true,pointerId:7,button:0,clientX:dragRect.left+30,clientY:dragRect.top+25}));',
  ' if(window.__closePhoneModal)window.__closePhoneModal(true);await sleep(260);document.body.dispatchEvent(new KeyboardEvent("keydown",{key:"/",bubbles:true,cancelable:true}));await sleep(40);S("slash_open",{messages:!!document.querySelector(".phone-backdrop.show .pm-messages")});shell=document.querySelector(".phone-shell");if(shell)shell.focus();shell.dispatchEvent(new KeyboardEvent("keydown",{key:"/",bubbles:true,cancelable:true}));await sleep(20);S("slash_in_messages",{phone:!!document.querySelector(".phone-backdrop.show"),active:document.activeElement&&document.activeElement.className});document.activeElement.dispatchEvent(new KeyboardEvent("keydown",{key:"/",bubbles:true,cancelable:true}));await sleep(260);S("slash_close",{phone:!!document.querySelector(".phone-backdrop.show")});',
  ' window.__openMessagesAt("cue_cocktails");await sleep(40);window.__runMsgAction("cue_cocktails");await sleep(40);S("cocktail_link",{cocktails:!!document.querySelector(".phone-backdrop.show .pm-ck-feat")});document.querySelector(".pnav-back").click();await sleep(40);S("cocktail_back",{messages:!!document.querySelector(".phone-backdrop.show .pm-messages"),home:!!document.querySelector(".phone-shell.pm-home")});document.querySelector(".pnav-back").click();await sleep(260);S("cocktail_back_close",{phone:!!document.querySelector(".phone-backdrop.show")});',
  '}',
  '})();</script>'
].join("\n");

var failures = 0;
function check(ok, msg, detail) {
  if (ok) console.log("  \u2713 " + msg);
  else { failures++; console.log("  \u2717 " + msg + (detail ? "   [" + JSON.stringify(detail) + "]" : "")); }
}

console.log("rsvp.html message read/unread context menu:");
var r = lib.runPageSync("rsvp.html", HARNESS, 4000, { patchRaf: true });
if (!r) { console.log("  \u2717 harness produced no report"); process.exit(1); }
var s = r.steps;
check(r.errors.length === 0, "no uncaught page errors", r.errors);
check(s.notification_open.app && s.notification_open.room === "garden" && s.notification_open.row && s.notification_open.visible && s.notification_open.unread, "tapping a notification opens and positions its unread message without running the action", s.notification_open);
check(!s.notification_escape.phone && s.notification_backspace_one.phone && s.notification_backspace_one.active === "pm-msg-input" && !s.notification_backspace_two.phone, "Escape closes directly opened Messages; empty search then takes two Backspaces (composer, close)", {escape:s.notification_escape,one:s.notification_backspace_one,two:s.notification_backspace_two});
check(s.notification_read.room === "garden" && s.notification_read.phone && !s.notification_read.unread && s.notification_read.action, "tapping a message only marks it read and leaves its explicit action available", s.notification_read);
check(s.notification_action.room === "office" && !s.notification_action.phone, "the separate message action control runs the linked action", s.notification_action);
check(s.keyboard_open.active === "pm-msg-input" && s.keyboard_open.app, "Messages opens with the composer focused", s.keyboard_open);
check(s.composer_slash_search.active === "pm-ms-input" && s.composer_slash_search.selected, "/ moves an empty composer directly to Messages search", s.composer_slash_search);
check(s.composer_slash_literal.active === "pm-msg-input" && !s.composer_slash_literal.prevented && s.composer_slash_literal.draft === "hello", "/ remains literal when the composer already has a draft", s.composer_slash_literal);
check(/phone-shell/.test(s.keyboard_escape.active) && s.keyboard_escape.app, "first Escape blurs the composer without leaving Messages", s.keyboard_escape);
check(s.keyboard_search.active === "pm-ms-input" && s.keyboard_search.selected, "/ focuses and selects the Messages search field after leaving the composer", s.keyboard_search);
check(/phone-backdrop/.test(s.fullscreen_menu.parent) && s.fullscreen_menu.hit, "the message context menu stays above the phone inside fullscreen", s.fullscreen_menu);
check(s.unread_menu.prevented && s.unread_menu.unread && s.unread_menu.labels.join("|") === "Reply…|Copy message|Mark as read." && s.unread_menu.reactionCount === 5, "an unread row offers Reply, Copy, read state, and five reactions", s.unread_menu);
check(s.reaction.chips.join("|") === "👍", "a selected reaction appears compactly beneath its message", s.reaction);
check(!s.marked_read.unread && s.marked_read.latest === null && /messages/i.test(s.marked_read.app), "marking read updates state without opening the message", s.marked_read);
check(s.read_menu.labels.join("|") === "Reply…|Copy message|Mark as unread.", "a read row offers Reply, Copy, and Mark as unread", s.read_menu);
check(s.marked_unread.unread && s.marked_unread.latest === "cue_mail", "marking unread restores unread state and count", s.marked_unread);
check(s.reply_selected.show && /Bahareh/.test(s.reply_selected.text) && s.reply_selected.read && !s.reply_selected.plus && s.reply_selected.unreadInTitle, "Reply targets the message, marks it read, removes +, and keeps unread-only in the title", s.reply_selected);
check(s.waiting.ids.join(",") === "invaders,cue_mail,reply_user_1" && !s.waiting.pending && !s.waiting.thinking && s.waiting.inputEnabled, "the visitor message appears immediately with no thinking placeholder and the composer remains usable", s.waiting);
check(s.waiting.asked && s.waiting.asked.display === "Save me a dance!" && s.waiting.asked.group.reply_to.id === "cue_mail" && s.waiting.asked.group.reply_to.sender === "Bahareh" && /did you check the mail/i.test(s.waiting.asked.group.reply_to.text) && s.waiting.asked.group.reply_to.reactions.join("|") === "👍" && s.waiting.asked.group.recent_messages.every(function(m){return typeof m.id === "string" && Array.isArray(m.reactions);}) && s.waiting.asked.group.current_dj === "Danesh" && s.waiting.asked.group.people_here.join("|") === "Bahareh|Irene" && s.waiting.asked.group.locations.kitchen.join("|") === "Pouria" && typeof s.waiting.asked.group.playtime.seconds === "number" && /^\d+:\d{2}$/.test(s.waiting.asked.group.playtime.display), "the group responder receives reactions, addressable recent messages, the reply target, room locations, and Clock playtime", s.waiting.asked);
check(s.waiting.asked && s.waiting.asked.group.cast.some(function(p){return p.name === "Ali" && p.role === "best man";}) && s.waiting.asked.group.cast.some(function(p){return p.name === "Bahareh" && /herds/.test(p.notes);}) && s.waiting.asked.group.cast.some(function(p){return p.name === "Behdad" && /dad jokes/.test(p.notes);}) && s.waiting.asked.group.cast.some(function(p){return p.name === "Irene" && p.can_message && p.message_frequency === "rare";}) && s.waiting.asked.group.cast.some(function(p){return p.name === "Robin" && !p.can_message;}) && s.waiting.asked.group.cast.some(function(p){return p.name === "Markéta" && /Behdad/.test(p.relationship);}), "the group responder receives cast humor and child-sender rules alongside roles and relationships", s.waiting.asked && s.waiting.asked.group.cast);
check(Array.isArray(s.waiting.privateHistory) && s.waiting.privateHistory.length === 0, "the wedding-thread exchange stays out of Charlie's private chat history", s.waiting.privateHistory);
check(s.answered.ids.join(",") === "invaders,cue_mail,reply_user_1,reply_ai_1" && s.answered.outgoing === "Save me a dance!" && /Bahareh:/.test(s.answered.quote) && s.answered.sender === "Bahareh" && /saved you one/.test(s.answered.crew) && /behdad:.*invaders/i.test(s.answered.crewQuote) && !s.answered.pending && s.answered.action && !s.answered.albumBefore, "the asynchronous crew answer can quote an earlier message and suggest an action without executing it", s.answered);
check(s.crew_action.album && s.crew_action_back.messages && !s.crew_action_back.home, "pressing a crew reply action opens its linked phone app, whose Back returns to Messages", { action: s.crew_action, back: s.crew_action_back });
check(s.outgoing_menu.labels.join("|") === "Reply…|Copy message", "sent-message rows also expose Reply and Copy instead of swallowing right-click", s.outgoing_menu);
check(s.reply_jump.target && s.reply_jump.highlight && s.reply_jump.search === "" && !s.reply_jump.unreadOnly, "tapping a reply quote reveals, scrolls to, and highlights the original message", s.reply_jump);
check(/^📱 You:/.test(s.message_api.result || "") && s.message_api.asked.join("|") === "Tell me a pun.|DJ, slow song please." && s.message_api.outgoing.join("|") === s.message_api.asked.join("|") && s.message_api.from.join("|") === "behdad|Danesh" && /You: DJ, slow song please\./.test(s.message_api.console), "message(text) and /message text both post as the player, use asynchronous crew replies, and style behdad lowercase in Messages", s.message_api);
check(s.czech.labels.join("|") === "Odpov\u011bd\u011bt…|Kop\u00edrovat zpr\u00e1vu|Ozna\u010dit jako nep\u0159e\u010dten\u00e9." && /svatebn\u00ed part\u011b/.test(s.czech.placeholder), "context actions and composer follow the Czech UI language", s.czech);
check(s.calendar_search.active === "calx-search-input" && s.calendar_search.on, "/ enters and focuses Calendar search even before its field exists", s.calendar_search);
check(s.icon_drag.ghost && s.icon_drag.selectionBlocked && s.icon_drag.userSelect === "none", "dragging a phone app icon cannot start native text selection", s.icon_drag);
check(s.slash_open.messages && s.slash_in_messages.phone && s.slash_in_messages.active === "pm-ms-input" && !s.slash_close.phone, "/ opens Messages globally, focuses search in-app, then closes it from an empty search field", {open:s.slash_open,inApp:s.slash_in_messages,close:s.slash_close});
check(s.cocktail_link.cocktails && s.cocktail_back.messages && !s.cocktail_back.home && !s.cocktail_back_close.phone, "a message-linked phone app returns to Messages first, then preserves the overlay's direct-close behavior", {link:s.cocktail_link,back:s.cocktail_back,close:s.cocktail_back_close});

console.log("");
if (failures) { console.log(failures + " check(s) failed."); process.exit(1); }
console.log("All checks passed.");
