[sdl]
autolock=true

[dosbox]
machine=svga_s3
memsize=16

[cpu]
core=auto
cycles=auto

[mixer]
nosound=true

[midi]
mpu401=none
mididevice=none

[sblaster]
sbtype=none

[gus]
gus=false

[speaker]
pcspeaker=false
tandy=off
disney=false

[autoexec]
@echo off
mount c .
c:
cd \NIBBLES
NIBBLES.EXE
cd \
echo.
echo Nibbles ended. The DOS prompt is yours.
